### ISSUE TITLE
Entering email address into box and clicking 'register' gives no indication of success

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#10]
_From @talumbau on July 21, 2015 18:14_

The user should be taken to a 'check your email' page.

_Copied from original issue: OpenSourcePolicyCenter/webapp#237_

**Comment by ospc-auto** [comment]
_From @talumbau on July 21, 2015 18:19_

cc @mistakevin @amfarrell @zrisher

**Comment by ospc-auto** [comment]
_From @talumbau on July 24, 2015 18:6_

LGTM. +1

**Comment by talumbau** [comment]
this is resolved with the new registration flow.
