### ISSUE TITLE
New field for real estate deduction haircut 

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/webapp-public#106]
A new field needs to be added for `_ID_RealEstate_HC`, right below "Deduction for state and local taxes haircut" in the same *State and Local Taxes* section. Default set to zero.

<img width="183" alt="screen shot 2015-11-20 at 2 38 43 pm" src="https://cloud.githubusercontent.com/assets/10549597/11309897/88a69396-8f94-11e5-83ce-6e2d31b0218c.png">

@MattHJensen Is that right?

**Comment by MattHJensen** [comment]
Looks right to me. @Amy-Xu, just fyi defaults will be populated automatically from current_law_policy.json just as the long names and other meta data are.

**Comment by MattHJensen** [comment]
Does the itemized deduction limitation also need to be modified for the new param @amy-xu?

**Comment by Amy-Xu** [comment]
Do you mean the phaseout or the surtax? If you mean the phaseout, I don't think so.

**Comment by MattHJensen** [comment]
Ahh, sorry, yes, meant the surtax.

**Comment by talumbau** [comment]
@Amy-Xu and @MattHJensen so then this feature is ready to be implemented, correct? No further changes other than what is currently described?

**Comment by Amy-Xu** [comment]
Just opened this [PR](https://github.com/open-source-economics/Tax-Calculator/pull/483).

It seems one more checkbox needs to be added at the end of itemized deduction section for real estate taxes paid.
<img width="687" alt="screen shot 2015-11-24 at 11 35 34 am" src="https://cloud.githubusercontent.com/assets/10549597/11373230/42843dc4-929f-11e5-9205-e42712c7ef76.png">
I have fixed the AllTaxesPaid issue in 'current_law_policy.json` to State & Local. The real estate taxes paid theoretically could come right after State & Local, and before casualty.

**Comment by Amy-Xu** [comment]
@talumbau I guess after the PR I mentioned above is merged, yes. Hopefully, let me double check right now.

**Comment by talumbau** [comment]
@Amy-Xu is it correct that the check boxes would be laid out like this:

```
"Medical", "State & Local", "Real Estate", "Casualty", "Miscellaneous", "Interest", "Charity"
```

in terms of order. Also, can you give me some kind of test case scenario with really high/unrealistic numbers so I can see the effect of these parameters?

**Comment by talumbau** [comment]
Oh it looks like I can use the tables you listed in https://github.com/open-source-economics/Tax-Calculator/pull/483 to see if I can sensical answers when I put this in the webapp. I will just do that thanks.

**Comment by Amy-Xu** [comment]
No problem. Sounds good. Thank you!
