### ISSUE TITLE
navigation buttons on TaxBrain input page do not work in Firefox

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#114]
These buttons do not work in Firefox:

![image](https://cloud.githubusercontent.com/assets/8301092/11857616/f49172a4-a427-11e5-8b61-43581010f34a.png)

![image](https://cloud.githubusercontent.com/assets/8301092/11857617/f9ddef3a-a427-11e5-8ffb-bd310813c18b.png)

Everything is fine in Chrome.

**Comment by talumbau** [comment]
FYI @johneo
