### ISSUE TITLE
Upon registration success, the success page text is pushed too far left

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#12]
_From @talumbau on July 21, 2015 18:9_

Here is what it looks like:

![screen shot 2015-07-21 at 1 08 29 pm](https://cloud.githubusercontent.com/assets/1891418/8808681/b5808d9a-2fa9-11e5-9cf0-db4aadc275ed.png)

It should be centered or at least look like the registration confirmation page

_Copied from original issue: OpenSourcePolicyCenter/webapp#235_

**Comment by ospc-auto** [comment]
_From @mistakevin on July 22, 2015 19:9_

Resolved by https://github.com/OpenSourcePolicyCenter/webapp/issues/241

**Comment by talumbau** [comment]
this is resolved in master now.
