### ISSUE TITLE
click back to inputs from the dynamic output page

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#129]
It would be nice to be able to click back to inputs from the dynamic output page, both the original input page and the dynamic input page. For example, I just got this link from @talumbau http://ospc-taxes5.herokuapp.com/dynamic/results/3/ and I wanted to check out how the policy reform was implemented. 

cc @talumbau, @jdebacker, @rickecon, @kerkphil

**Comment by MattHJensen** [comment]
Users might also want to click back to the microsim output page so that they can do a rough dynamic revenue analysis by applying the total tax difference percent change to the microsim revenue estimate.

**Comment by talumbau** [comment]
Agreed. Assigning to myself. Just for the curious, for that particular result, this was the original microsim:

https://ospc-taxes5.herokuapp.com/taxbrain/451/

**Comment by talumbau** [comment]
resolved via https://github.com/OpenSourcePolicyCenter/webapp-public/pull/131
