### ISSUE TITLE
Remove FEI parameter and note for payroll tax

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/webapp-public#137]
@talumbau found two things when I was doing my other task:

![capture](https://cloud.githubusercontent.com/assets/10549597/12520874/0825cffe-c115-11e5-8c27-b01143dd0da3.PNG)
This parameter won't work right due to lack of data. So we should remove this one from input page for now.

![capture1](https://cloud.githubusercontent.com/assets/10549597/12520896/27c39b52-c115-11e5-9370-fda59651a4d9.PNG)
This 'no payroll revenue' should also be taken off as we have payroll reported now.

Thank you! 
cc @MattHJensen

**Comment by talumbau** [comment]
closed via #142
