### ISSUE TITLE
max taxable earnings for social security weird results

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#138]
http://www.ospc.org/taxbrain/893/
http://www.ospc.org/taxbrain/894/

@martinholmer pointed out that both of these are bugs. There should be an increase in fica revenue and little change in individual income tax. Things look ok on tax-calculator.

@talumbau, could you take a look when you have a chance?

**Comment by talumbau** [comment]
I started to look in to this. I looked up the reforms that were submitted for the runs above and created a notebook to run them manually on my local machine. I also manually ran dropq and can verify that the results in 893 and 894 on the site are what I get when running dropq locally. Therefore, if there is an issue, we know that it's somewhere in dropq and not a display problem or mixup of data on the website.

I started with 893. This one specifies a large value for `_SS_Earnings_c`. The very large entry on the site is translated to 1e21. Technically the Benefit Surtax boolean flags always come through in the reform (even though they are the defaults), but just to make the run exactly like what is on the website, I included it in the notebook.

```
mvars = {}
myvars['_SS_Earnings_c'] = [1e+21]
myvars['_ID_BenefitSurtax_Switch'] = [[True, True, True, True, True, True, True]]
user_mods = {2015: myvars}
```

The results of running that reform for the year 2015 with the PUF are shown here:

http://nbviewer.jupyter.org/github/talumbau/Tax-Calculator/blob/diff_debug/docs/notebooks/Run_ss_max_diff.ipynb

@MattHJensen and/or @martinholmer do the results on this notebook conform to your expectations and do you get the same answer when running on your machine? I think we would need that as a starting point to start the debugging. My initial findings between taxbrain/893 and the notebook above are as follows:

 - Distributional table for base plan in the notebook matches the equivalent in taxbrain/893
 - Distributional table for user plan in the notebook matches the equivalent in taxbrain/893
 - Difference table for payroll tax in the notebook matches the equivalent in taxbrain/893
 - Difference table the combined payroll and ind. income tax in the notebook matches taxbrain/893
 - Difference table for ind. income tax in the notebook differs from taxbrain/893

So, as long as we all agree that what matches between the notebook above and what is on TaxBrain for run 893 is correct, I can focus on understanding what's going on for the difference table for ind. income tax. Please have a look and let me know. Thanks!

**Comment by martinholmer** [comment]
T.J. and Matt said to look at:
> http://www.ospc.org/taxbrain/893/
> http://www.ospc.org/taxbrain/894/

How do I look at these TaxBrain results?
When I click on the links (in Chrome on a Mac) nothing happens. 

cc @talumbau @MattHJensen

**Comment by talumbau** [comment]
@martinholmer if you click the link and wait a few seconds, the output tables should appear. Sometimes it takes between 8-10 seconds for all of the tables to load.

**Comment by martinholmer** [comment]
T.J. @talumbau, thanks ... guess I need to be more patient.

The second one (894) had a strange MTE value when I click back to the parameters.
Something like 2000.1111111.
I never entered such a value, but I did put in 9.9E99 to see what would happen.

cc @MattHJensen

**Comment by talumbau** [comment]
OK, @martinholmer I won't be able to debug the issue you are describing ("entering some value other than `2000.11111` and getting `2000.11111` as the value used in the microsim") unless you can tell me how to reproduce. Even if you are able to reproduce that issue, let's create a separate issue for that problem. For this issue, I'm interested in knowing if you or Matt or Amy can reproduce the results I'm showing in this link:

[http://nbviewer.jupyter.org/github/talumbau/Tax-Calculator/blob/diff_debug/docs/notebooks/Run_ss_max_diff.ipynb](http://nbviewer.jupyter.org/github/talumbau/Tax-Calculator/blob/diff_debug/docs/notebooks/Run_ss_max_diff.ipynb)

If you or Matt or Amy can reproduce and the values in that notebook make sense to you, I can focus on the table I noticed that was significantly different:

 - Difference table for ind. income tax in the notebook differs from taxbrain/893

I'm hoping that someone could look at the two tables and see if the one generated locally (in the notebook) makes sense and the one on the web app looks weird. I suspect that this is the key difference that will help show the problem.

cc @MattHJensen @Amy-Xu

**Comment by talumbau** [comment]
Looking more closely at `tdiff2015_iit` from the notebook and the equivalent table in in taxbrain/893, the total tax difference and average tax change in each decile seem to line up pretty well. The numbers reported in Tax Units with Tax Cut and Tax Units with Tax Increase are pretty far off and seem unlikely to be explained by the `dropq` algorithm.

**Comment by MattHJensen** [comment]
@talumbau, it seems like part of the problem may be stemming from tax-calculator. When we increase _SS_Earning_c, total revenue should go up, not down. See the relevant logic from `functions.py`:
 
    _fica_ss_head = max(0, FICA_ss_trt * min(SS_Earnings_c, e00200p +
                        max(0, _sey_p) * (1 - 0.5 * FICA_trt)))
    _fica_ss_spouse = max(0, FICA_ss_trt * min(SS_Earnings_c, e00200s +
                          max(0, _sey_s) * (1 - 0.5 * FICA_trt)))

Investigating further.

**Comment by martinholmer** [comment]
T.J., I appreciate all your work on this, but I'm way in over my head when I try to look at what you are doing in the notebook.  My simple observation to Matt on the phone the other day was this:

* when you put into TaxBrain an MTE of two billion (beginning in 2015), you get a reasonable result

but

* when your put a much larger integer in the box, you get FICA taxes **declining**, which is not a reasonable result.

cc @talumbau @MattHJensen

**Comment by martinholmer** [comment]
We now know that the cause of these problems was rooted in the Tax-Calculator, and have nothing to do with TaxBrain or dropQ.  See tax-calculator repository issue 589 and pull request 590 for details.  This webapp-public issue 138 should be closed.

cc @MattHJensen @talumbau

**Comment by MattHJensen** [comment]
Thanks @martinholmer. Closing.
