### ISSUE TITLE
Get behavior parameter working on Tax Brain

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/webapp-public#139]
@talumbau I recently [added behavior](https://github.com/open-source-economics/Tax-Calculator/pull/526) to capital gain for Tax-Calculator, which currently only includes the persistent field. This field should be linked to '_BE_CG_per' in behavior.json.

I went through drop Q again and don't feel the way it calling behavior needs any modification. But we should probably include this parameter in boolean [has_behavior](https://github.com/OpenSourcePolicyCenter/dropQ/blob/master/dropq/dropq.py#L327). Haven't tried on my local machine yet. Will keep you posted if I found anything else.

cc @MattHJensen

**Comment by MattHJensen** [comment]
Let's also drop the transitory field from TaxBrain.

**Comment by talumbau** [comment]
resolved via #145
