### ISSUE TITLE
Broken link on inputs page

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#14]
_From @talumbau on July 17, 2015 2:4_

<img width="286" alt="screen shot 2015-07-16 at 9 02 01 pm" src="https://cloud.githubusercontent.com/assets/1891418/8739180/1ba84108-2bfe-11e5-9a46-bebe7c7c580a.png">

This link in the bottom right of the inputs page is broken. @MattHJensen do you think it should link to something? If not, maybe we should remove it...

_Copied from original issue: OpenSourcePolicyCenter/webapp#230_

**Comment by ospc-auto** [comment]
_From @MattHJensen on July 17, 2015 13:9_

Could we move the user back to the top of the page and open the "what is taxbrain" dropdown when they click this link?

**Comment by talumbau** [comment]
there's just enough front end magic here that I think I should hand this off. The idea is that a click should:

- move to the top of the page
- toggle the 'What is TaxBrain' div defined in `input_form.html`.

cc @mistakevin @zrisher

**Comment by talumbau** [comment]
resolved via https://github.com/OpenSourcePolicyCenter/webapp-public/pull/47
