### ISSUE TITLE
Formatting on news.ospc.org

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#15]
_From @MattHJensen on July 6, 2015 20:21_

We will start our blog with one post, and no "other news". News.ospc.org should be formatted so that it looks good as we go from one, to two, to three (...) blog posts and no "other news". Removing the "other news" section entirely would be fine for now. 

_Copied from original issue: OpenSourcePolicyCenter/webapp#226_

**Comment by ospc-auto** [comment]
_From @talumbau on July 17, 2015 1:52_

@amfarrell per our convo this morning.

**Comment by MattHJensen** [comment]
I believe this one is resolved. @talumbau, I'll let you close it if you agree.

**Comment by talumbau** [comment]
agreed.
