### ISSUE TITLE
start year 2016, reform in second year, all zero results

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#163]
With start year == 2016, this reform:

![image](https://cloud.githubusercontent.com/assets/8301092/13324873/76702d12-dbad-11e5-8f3e-ea9be038a6d4.png)

Outputs all zeroes for revenue changes. 

http://www.ospc.org/taxbrain/1158/

A similar reform with start year == 2017 also outputs all zeroes for revenue changes 
http://www.ospc.org/taxbrain/1161/

With start year == 2015, everything looks fine:

http://www.ospc.org/taxbrain/1159/

Even with start year == 2015 and modifying values for 2015, 2016, and 2017:

![image](https://cloud.githubusercontent.com/assets/8301092/13325078/5ef7a93e-dbae-11e5-8e2a-3486692a2db6.png)

Everything looks fine:
http://www.ospc.org/taxbrain/1162/

I'll check this out on tax-calculator locally and see whether I can duplicate the problem there and then report back. 

Thanks to @martinholmer for pointing this problem out. 

cc @talumbau

**Comment by MattHJensen** [comment]
The 2015 start year is not immune to these problems either:

**Comment by talumbau** [comment]
resolved via https://github.com/OpenSourcePolicyCenter/webapp-public/pull/167
