### ISSUE TITLE
TaxBrain should have a "throttle" to keep site responsive under heavy load

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#164]
In a little while, we might have a lot of traffic to the TaxBrain site, if only for a short time. The hosting for the web page itself is quite scalable, and should be able to scale to meet anticipated demand (this will be tested using some tools and services over the next week or so). For the computational backend of TaxBrain though, there is a much smaller limit on the number of users we can simultaneously support. Even if we add 4x the amount of computational resources we are using right now, we could still only service a maximum of 5 simultaneous jobs. Additional jobs won't overwhelm the system, but the queue will be quite long. Many users, after 2-3 minutes of waiting, will simply give up and assume that the site is broken and leave the site while the "Please wait while calculations are running" screen is refreshing. Consider the case of 30 users submitting a job at all nearly the same time, with TaxBrain running with the ability to handle 5 simultaneous jobs. The first five jobs (jobs 1-5) immediately start processing, with an expected turnaround time of about 30 seconds. The second set of five jobs (jobs 6-10) received will all get a response in about 60 seconds (30s for one of the jobs ahead of it to clear, then 30s for the job itself to run). The total wait time for any job that is job 11-15 will be ~1min 30s, and so on, up to ~3 minutes for jobs 25-30.

This issue proposes a throttling mechanism that would, upon job submission, check to see if TaxBrain is experiencing a surge in traffic. If it is, instead of submitting the job, the user would get a small pop-up saying "We're sorry, TaxBrain is under heavy load right now. Please try again in a few minutes."

The throttling mechanism would simply be check "have more than X jobs been submitted in the last 30 seconds?", where `X` would be something like "three times the current maximum number of concurrent jobs".

I think it would be best if this is done in the AJAX style (cc @mistakevin) so that the user, upon hitting submit, would get a pop-up and stay on the same page if the job is rejected for reasons of current job load (as opposed to loading up a new page that has the bad news for the user)

This would be a reasonable way to not frustrate folks who submit a job (since we are setting a maximum on the time they will have to wait) and keep the overall site responsive under heavy load.

Thoughts? @MattHJensen @mistakevin

**Comment by MattHJensen** [comment]
Would it be significantly harder to take their email address if the wait is expected to be long and email them when the computation is finished?

**Comment by talumbau** [comment]
hmm.. not hard but somewhat time consuming. It would be most time consuming to have this as a feature for an arbitrary user. Less time consuming for a registered user. In any case, there still needs to be the code written that answers the question "are we undergoing a surge in traffic right now?" I can write that code and make sure it is of a form that can be called in the AJAX style with @mistakevin. Then, we could evaluate where we are in terms of timeline and see which one we should implement. How does that sound?

**Comment by MattHJensen** [comment]
That sounds good.

**Comment by talumbau** [comment]
this is resolved.
