### ISSUE TITLE
on results page, change AGI, Income -> Expanded Income

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#17]
_From @MattHJensen on June 25, 2015 12:51_

Once https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/260 is merged, we need to relabel tables on the results page of the webapp. 

Agi decile -> expanded income deciles
income bins -> expanded income bins 

We should also add a footnote or some other documentation:

Expanded income includes adjusted gross income plus non-taxable interest income, non-taxable social security benefits, and the employer share of FICA. Additional income components will be added over time. 
  

_Copied from original issue: OpenSourcePolicyCenter/webapp#218_

**Comment by talumbau** [comment]
closed via https://github.com/OpenSourcePolicyCenter/webapp-public/pull/39
