### ISSUE TITLE
If you click 'submit' and have not changed anything, you get an error

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#18]
_From @talumbau on June 24, 2015 19:13_

The result should be some kind of " you can't do that" page or general error message.

_Copied from original issue: OpenSourcePolicyCenter/webapp#217_

**Comment by ospc-auto** [comment]
_From @talumbau on June 24, 2015 19:13_

@MattHJensen, thoughts on what it should say?
@zrisher, thoughts on how to implement?

**Comment by ospc-auto** [comment]
_From @MattHJensen on June 24, 2015 19:28_

I don't see a major problem with dealing with this on an ad hoc basis, but we may also want to think of it as part of the bigger issue of form validation, so let me say something about that:

 There are some parameter values that will generate nonsensical results, and at some point we might want to build some warnings into the webapp. 

As an example, right now it doesn't really make sense to do anything that would *increase* the value of itemized deductions; we haven't imputed itemized deductions to people who currently pay standard deduction (see [tax-calculator issue 230](https://github.com/OpenSourcePolicyCenter/Tax-Calculator/issues/230)), and so anything that might encourage them to switch to itemizing won't be captured properly. This would be bad: 
![image](https://cloud.githubusercontent.com/assets/8301092/8339381/fd8abff0-1a84-11e5-8b56-0da8422c7c7c.png)

In many of these cases we might want to pop up a warning, or even block an action + pop up a warning, *before* the user hits submit. 

As to this particular issue, the warning could be: "You have not specified any tax-law changes. Please do so before submitting"

**Comment by ospc-auto** [comment]
_From @zrisher on June 24, 2015 19:52_

If a user runs the tax calculator without making any changes to the params, shouldn't they just get a run of the tax calc using current defaults? As a user, I would expect clicking the submit button without changing any parameters to get me to a results page where the difference between my plan and the default plan is zero for every field.

As for the field value controls, I think value ranges should probably be listed in parameter info returned from TaxCalc that we use to build the fields and form. Then we can parse it, add those field controls to the model, and use the normal field validation that's already in place to enforce.

**Comment by ospc-auto** [comment]
_From @MattHJensen on June 24, 2015 20:3_

>If a user runs the tax calculator without making any changes to the params, shouldn't they just get a run of the tax calc using current defaults? As a user, I would expect clicking the submit button without changing any parameters to get me to a results page where the difference between my plan and the default plan is zero for every field.

This is a good point. It would mean dealing with the divided by zero error in the table generators. 

>As for the field value controls, I think value ranges should probably be listed in parameter info returned from TaxCalc that we use to build the fields and form. Then we can parse it, add those field controls to the model, and use the normal field validation that's already in place to enforce.

Also makes sense. I think it would make sense to include the value ranges somehow in params.json. and on the parameter object. When someone is using the taxcalc API, it could return something like, "field is outside of the acceptable range, please use a value between x and y".

**Comment by ospc-auto** [comment]
_From @talumbau on June 24, 2015 20:14_

Hmm.. I have the opposite opinion on the first item. I have seen a couple of people go to the app, scroll through the big list of fields they can edit, then just instinctively hit 'submit'. If we do as you suggest, we invoke our whole computational engine (which admittedly won't do much but still must be called), and then they get a whole page of 0s. The new users I saw (who got the error message) did not understand at first that they had to put something in so that TaxBrain would show *differences* between existing law and the choices they put it. So, a page with a message (or even a pop-up message) that says "You're not doing it right" I think is more helpful than the actual full results of all 0s.

**Comment by ospc-auto** [comment]
_From @MattHJensen on June 24, 2015 20:21_

Ahh yes, I see your point T.J. I suppose the ideal situation would be to have a separate output page that just gives baseline information, but not the difference tables, user specified plan tables, or revenue tables. That seems like more work than is worth it right now, though. 

Which takes us back to giving an error message. The scenario you describe, of the user getting overwhelmed, might suggest that we should say something like "Please specify a tax-law change before submitting; maybe try repealing the deduction of state and local taxes by setting the haircut parameter to 1."

**Comment by ospc-auto** [comment]
_From @zrisher on June 24, 2015 20:32_

> If we do as you suggest, we invoke our whole computational engine (which admittedly won't do much but still must be called)

Once we put result-caching in place there's zero extra load from a user running a plan that's already been run once.

>  they get a whole page of 0s

The difference tables would be zero, but the latter tables would have useful data. But I agree it's a poor presentation in that case.

> The new users ... did not understand at first that they had to put something in so that TaxBrain would show differences between existing law and the choices they put it. So, a page with a message (or even a pop-up message) that says "You're not doing it right" I think is more helpful than the actual full results of all 0s.

I think once params-changed counts are in, it should be pretty obvious that you're getting a page with zero result "changes" because you haven't made any input changes.  Overall, I believe it would be most intuitive for the logic to run whether you make changes or not, but a validation message would be a fine stopping point until it's worthwhile to improve the delivery of results data in that case.

Either way though, I don't think the tax calculator should throw an error if your parameters are unchanged from defaults. There's still useful data to get out of it. Or if we truly considered that an error condition, and no one should ever run the calculator without changing params, it should raise a custom error that says that instead of passing along the division by zero error.

**Comment by ospc-auto** [comment]
_From @zrisher on June 24, 2015 20:44_

So TLDR I agree - let's do a custom validation error on the Django side if no params are changed, at least until we can put some work into designing the output for that case. But let's also improve (or better fix) the error returned from the tax calculator for people that aren't using it through the webapp.

**Comment by ospc-auto** [comment]
_From @talumbau on July 17, 2015 1:51_

@mistakevin care to take a swing at this one?

**Comment by ospc-auto** [comment]
_From @talumbau on July 20, 2015 16:14_

Initial issue fixed via https://github.com/OpenSourcePolicyCenter/webapp/pull/233. leaving open so that @zrisher @MattHJensen can comment/open additional issues as necessary. will eventually close.

**Comment by talumbau** [comment]
The immediate issue (no changes results in error) has been resolved and the follow-up conversation on inputs is better addressed in https://github.com/OpenSourcePolicyCenter/webapp-public/issues/46. Closing this one.
