### ISSUE TITLE
broken links on home page and news tab

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#181]
From the home page, www.ospc.org, the "news" link at the bottom right is broken. 

![image](https://cloud.githubusercontent.com/assets/8301092/13676899/ac4f7d44-e6b5-11e5-92c9-4783e07fa974.png)

From the news page, news.ospc.org, all of those links in the bottom right are either broken or direct to the wrong place. 

The "home" link should probably take us to www.ospc.org rather than to news.ospc.org. The other links return errors.

**Comment by talumbau** [comment]
the link on the homepage is fixed in master, just need to re-deploy to ospc.org. I'll tackle the links on news.ospc.org. These bugs indicate the need for Selenium testing, as these are harder to detect with the Django testing infrastructure.

**Comment by talumbau** [comment]
this error was due to a bad environment variable on the backend and a bad upload to news.ospc.org. It's fixed now but regular selenium testing seems like the right answer.
