### ISSUE TITLE
re-runnning results leads to 500 error

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#182]
I get a dynamic result
http://www.ospc.org/dynamic/behavior_results/21/

Then I click "edit parameters" 
http://www.ospc.org/dynamic/behavioral/edit/21/?start_year=2016

Then I try to rerun the simulation:
http://www.ospc.org/dynamic/behavioral/21/?start_year=2016

And I get a 500 internal server error. 

This problem does not exist for the static model. I am not sure if it does for the macro elast model; I haven't checked that yet. 

cc @talumbau @mistakevin

**Comment by talumbau** [comment]
resolved via https://github.com/OpenSourcePolicyCenter/webapp-public/pull/190
