### ISSUE TITLE
low priority - what is taxbrain dropdown odd formatting

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#183]
If I open he What is TaxBrain dropdown and scroll down a bit to see the text, the sidebar nav pops up over the what is taxbrain text.  

![image](https://cloud.githubusercontent.com/assets/8301092/13704685/291d58f4-e76b-11e5-8877-0b35c27de598.png)

**Comment by talumbau** [comment]
ping @mistakevin I can reproduce. let's chat when you have time.

**Comment by mistakevin** [comment]
@talumbau getting flatblocks content loading locally would help with this

**Comment by talumbau** [comment]
this page should help:

https://github.com/OpenSourcePolicyCenter/webapp-public/wiki/Loading-flatblocks-data

there is a `flatblocks.json` in the repo now. You should be able to do:

```
python manage.py loaddata flatblocks.json
```

let me know how that goes.

**Comment by mistakevin** [comment]
worked!
