### ISSUE TITLE
add docs to webapp on replicating results locally

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#19]
_From @MattHJensen on June 23, 2015 16:34_

answer: 'how can I get the same code from the web app on my local machine?' 

This will interact with: https://github.com/OpenSourcePolicyCenter/Tax-Calculator/issues/284

_Copied from original issue: OpenSourcePolicyCenter/webapp#216_

**Comment by ospc-auto** [comment]
_From @talumbau on July 17, 2015 1:59_

This should be a blurb that discussed how one can do `conda install -c ospc taxcalc`. Maybe a link to the getting started guide, or general info about conda.

**Comment by talumbau** [comment]
@MattHJensen, this might be just the text to put in the footer, now that we have a flat-block for the footer in #39. Do you think that's a reasonable place to put such a blurb?

**Comment by talumbau** [comment]
@MattHJensen This is the blurb I came up with for the results footer. Let me know if you want to go with this for the next release or if you prefer a different blurb. OSPC.org still has the lorum ipsum in the results footer, so this text would replace that

<img width="1094" alt="screen shot 2015-09-25 at 5 23 03 pm" src="https://cloud.githubusercontent.com/assets/1891418/10113465/4a91e922-63aa-11e5-8f8b-9d3a0d28c2ce.png">

**Comment by MattHJensen** [comment]
This looks good to me and then I might tinker before the 10/13 release.

**Comment by martinholmer** [comment]
@MattHJensen and @talumbau,
Are the "pre-built packages" going to include the 2009 PUF file as used by the TaxBrain webapp?  If not, isn't the phrase "want to run this code on your machine?" a little misleading?  I think most people would read that phrase as "want to run this analysis on your machine?".  I know that is not what it says --- "code" is not "analysis", but I think more than a few people will read it that way.  And unless the 2009 PUF is downloadable along with the code, they will be very disappointed.

**Comment by MattHJensen** [comment]
What if we drop the header? Actually, I had initially viewed this footer as a place to put some methodological footnotes for the tables; particularly a discussion of our expanded income measure and a discussion of calendar year vs. fiscal year. I could add those above the content starting "these results were generated...."  if we didn't have the header.

**Comment by talumbau** [comment]
We don't have a great answer here until we have a publicly available data set. This should happen fairly soon, but we'll want to have more extensive documentation than what would just be at the bottom of the TaxBrain results page.
