### ISSUE TITLE
Income and payroll do not sum up to combined liability

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/webapp-public#195]
In [my experiment](http://www.ospc.org/taxbrain/1629/) here, I added an itemized deduction surtax. Itemizers would be subject to an additional tax, amount equal to 10 times of their eligible itemized deductions if the original deduction is smaller than 2 times of their AGI. 

<img width="811" alt="screen shot 2016-03-15 at 11 13 36 am" src="https://cloud.githubusercontent.com/assets/10549597/13782802/0557316a-ea9f-11e5-9d17-380ff76b1f25.png">

This is a crazy experiment for sure, but somehow the income and payroll liabilities do not sum up to combined liability. 
<img width="1332" alt="screen shot 2016-03-15 at 11 13 19 am" src="https://cloud.githubusercontent.com/assets/10549597/13782842/3790bfa2-ea9f-11e5-9f3c-19a1d4b17c4d.png">

Something must be missing here. I'll look into this issue with my local tax-calculator first.

c.c. @MattHJensen @talumbau

**Comment by MattHJensen** [comment]
Thanks a lot @Amy-Xu. let us know what you find locally.

**Comment by Amy-Xu** [comment]
Update:
It seems we need one more line in the surtax function for updating combined liability. Currently in calc_all(), this surtax function is called after calc_one_year(), and only updates income liability leaving combined the same as baseline. 

Updating combine liability in the surtax function at least fixed this problem on my local Tax-Calculator. Would give it a try on my local dropq as well.

**Comment by MattHJensen** [comment]
I just merged https://github.com/open-source-economics/Tax-Calculator/pull/644, which should resolve this issue w a new taxcalc package.

**Comment by talumbau** [comment]
@Amy-Xu @MattHJensen this is has been resolved with the release ot `taxcalc` [0.6.2](https://github.com/open-source-economics/Tax-Calculator/releases/tag/0.6.2). For example, see [taxbrain/1719](http://www.ospc.org/taxbrain/1719/), which is a re-run of Amy's experiment.

**Comment by MattHJensen** [comment]
Thanks @talumbau and @amy-xu.
