### ISSUE TITLE
Internal server errors with growth related parameters

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/webapp-public#196]
<img width="724" alt="screen shot 2016-03-15 at 2 07 51 pm" src="https://cloud.githubusercontent.com/assets/10549597/13788738/6c5eabfa-eab7-11e5-81e7-a52aa6bd23b7.png">

These two parameters are giving me 500 internal server errors just now.

@talumbau @MattHJensen

**Comment by Amy-Xu** [comment]
A quick update, I don't see any error popping up so far (dropq or taxcalc), but will it be a problem if the `cdf_bin_table` and `pdf_bin_table` [here](https://github.com/OpenSourcePolicyCenter/dropQ/blob/master/dropq/dropq.py#L566) are empty? @talumbau

**Comment by talumbau** [comment]
@Amy-Xu @martinholmer I can reproduce and will be pushing a fix this morning.

**Comment by talumbau** [comment]
resolved via https://github.com/OpenSourcePolicyCenter/webapp-public/commit/bea7cdd9d134f1645aef2e38a601e4350e2cfaf4
