### ISSUE TITLE
we should remove the worker task from the Procfile

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#20]
_From @talumbau on June 9, 2015 16:57_

Now that the workload is done on AWS, there is no need for this entry.

_Copied from original issue: OpenSourcePolicyCenter/webapp#214_

**Comment by talumbau** [comment]
this was resolved in the old repo, so we don't have the history, but by inspection, one can see that this entry is no longer in `Procfile` at the top of the repo.
