### ISSUE TITLE
EITC parameters

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/webapp-public#202]
```
reform = {2016:{"_EITC_rt":[[0.08415, 0.374, 0.44, 0.495]],
                "_EITC_prt": [[0.08415, 0.17578, 0.23166, 0.23166]]}}

```

It seems this reform has inconsistent results between taxcalc and TaxBrain. Using taxcalc, the difference between baseline and reform is within 2 billions, but on TaxBrain the difference is roughly between 70 - 80 billions, running separately or combined together.

@talumbau @MattHJensen @martinholmer

**Comment by talumbau** [comment]
closed via #203
