### ISSUE TITLE
Why no CPI button on Personal Refundable Credit amounts?

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#206]
The Tax-Calculator current_law_policy.json file has the ```_II_credit``` amount (which is indexed by MARS) with this specification:  ```"cpi_inflated": true```.

Is there a reason TaxBrain does not have a CPI button on this parameter?

**Comment by martinholmer** [comment]
Same question for the ```_II_credit_ps``` amounts.  Why no CPI button in TaxBrain?

**Comment by talumbau** [comment]
Hmm.. these are good questions. The models have a boolean field to hold this info. See, respectively, here:

https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/models.py#L147

and here:

https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/models.py#L152

So, for some reason, the flag is not rendering. I will investigate.
