### ISSUE TITLE
OutputUrl serves no purpose

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#21]
_From @zrisher on June 8, 2015 7:57_

Right now, we save all of the input and output data for a taxcalc run in a `TaxSaveInputs` model instance. When this model receives its results from a TaxCalc run, we generate a `UniqueUrl` model instance that serves as a single point of reference for this `TaxSaveInput`. We could just as easily use the `TaxSaveInput` directly instead.

However, I believe the eventual purpose of this separation was to allow re-use of a `TaxSaveInputs` for many runs of the calculator by various users. If a user runs the same calc (i.e. params and TC version are the same) at different times, or multiple users run the same calc, we could store a new `UniqueUrl` for each run, but refer to a shared `TaxSaveInputs` for info on the params, version, and results. This would save us from having to rerun the calculator.

If this sounds like the right way to go, I'm happy to work on implementation.

_Copied from original issue: OpenSourcePolicyCenter/webapp#212_

**Comment by talumbau** [comment]
It is possible to re-use TaxSaveInputs results, but the cost of running the model is small enough and the Tax-Calculator code advances quickly enough that the idea of re-using TaxSaveInputs results has not been a high priority. Closing for now.
