### ISSUE TITLE
TaxBrain table tooltips need content

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#219]
Tooltips need to be filled in. 

![image](https://cloud.githubusercontent.com/assets/8301092/14331396/1c76fa76-fc13-11e5-8265-be653ce0165e.png)

**Comment by mistakevin** [comment]
To update the tooltips, you only need to change the text here https://github.com/OpenSourcePolicyCenter/webapp-public/blob/master/webapp/apps/taxbrain/constants.py

**Comment by mistakevin** [comment]
cc @talumbau

**Comment by MattHJensen** [comment]
Resolved. Closing.
