### ISSUE TITLE
Format tax law inputs with %

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#22]
_From @MattHJensen on May 19, 2015 16:49_

What do you think about formatting the relevant tax law parameters as percents on the input page for the webapp? For instance, the haircuts could be 0% to 100% rather than  0 to 1? Would this be easy to do on the webapp side? (I wouldn't want to hardcode it into params.json and functions.py.)

_Copied from original issue: OpenSourcePolicyCenter/webapp#201_

**Comment by ospc-auto** [comment]
_From @zrisher on May 20, 2015 13:22_

This wouldn't be too hard to implement, and really you'll want an interface ready to deal with % values eventually anyway. I can't speak for whether it would make more sense to a tax-modeler though. Seems like a nice addition for any ratio constrained from 0-1.

**Comment by ospc-auto** [comment]
_From @MattHJensen on May 20, 2015 13:24_

Ok. Changing this to an enhancement.

**Comment by MattHJensen** [comment]
Closing in favor of #269.
