### ISSUE TITLE
Policy reform * notation does not seem to work

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#224]
On Sunday, April 24th, I entered `*,*,*,400000` to raise the social security MTE to $400,000 beginning in 2019.  The start year was 2016 and the three `*` values were meant to indicate the MTE should be at current-law values for 2016, 2017, and 2018.  The [TaxBrain run results](http://www.ospc.org/taxbrain/3078/) show payroll tax revenue changes as follows:
```
   2016    2017    2018    2019
    0.0    -6.4   -10.6   117.2
```
I expected no change in 2016, but I also expected no change in 2017 and 2018.  Why are payroll tax revenues **declining** in 2017 and 2018?  The large increase in payroll tax revenue in 2019 was expected.

@talumbau @MattHJensen

**Comment by talumbau** [comment]
Hmm.. the difference came out because the web app code advanced the 2016 value (118,500) to values for 2017 and 2018 that do not match what a default Calculator instance produces. To do this advancement, I use the `indexing_rates_for_update` method on a `Policy` object, so it appears that I do not properly understand the code that advances parameters in to the future now. @martinholmer maybe you can point me to a test in Tax-Calculator or example that shows how to properly advance a policy parameter in to the future.

**Comment by martinholmer** [comment]
T.J. said:
> Hmm.. the difference came out because the web app code advanced the 2016 value (118,500) to values for 2017 and 2018 that do not match what a default Calculator instance produces. To do this advancement, I use the indexing_rates_for_update method on a Policy object, so it appears that I do not properly understand the code that advances parameters in to the future now. @martinholmer maybe you can point me to a test in Tax-Calculator or example that shows how to properly advance a policy parameter in to the future.

Here is the source code (from `parameters_base.py`) for that method:

```
def indexing_rates_for_update(self, param_name,
                                  calyear, num_years_to_expand):
        if param_name == '_SS_Earnings_c':
            rates = self.wage_growth_rates()
        else:
            rates = self.inflation_rates()
        if rates:
            expand_rates = [rates[(calyear - self.start_year) + i]
                            for i in range(0, num_years_to_expand)]
            return expand_rates
        else:
            return None
```

Is it possible that when TaxBrain calls that function it forgets to put a leading underscore in front of the passed `param_name`?  The TaxBrain results I got certainly look like the `_SS_Earnings_c` parameter is being indexed by price inflation, not wage inflation, in the years before the 2019 reform.  If this turns out to be true, you should check all the TaxBrain source code for the same mistake (like indexing after 2019 in the example reform being discussed here).

@MattHJensen

**Comment by talumbau** [comment]
yes, you are correct. This is the source of the error. I will create a fix and update this issue when the fix is up on the site. thanks!

**Comment by martinholmer** [comment]
T.J. (@talumbau)  said:
> Maybe you can point me to a test in Tax-Calculator or example that shows how to properly advance a policy parameter in to the future.

Codecov says that the `indexing_rates_for_update` method in `parameter_base.py` is completely tested.

On the other hand, it would seem that the following test in the public-webapp repository (in the `webapp/apps/taxbrain/tests/test_all.py` file) is incorrect:

```
def test_package_up_vars_wildcards_2016(self):
    values = {"SS_Earnings_c": ['*','*',230000.]}
    ans = package_up_vars(values, first_budget_year=2016)
    exp =  [118500., 120099, 230000.]
    assert ans['_SS_Earnings_c'] == exp
```

The value of 120099 is incorrectly equal to a price-indexed 118500 (rather than a wage-indexed 118500): the 2016 default value for price inflation is 1.35 percent while the default value for wage inflation is 4.79 percent.  So, if the test above had been correctly formulated (using this line `exp = [118500, 214176, 230000]`), then the lack-of-leading-underscore error highlighted in this issue #224 would have been flagged by the unit tests in the public-webapp repository.

@MattHJensen

**Comment by talumbau** [comment]
yes, this is the test that will be updated. as well as another one. Re-opening until the fix is pushed.

**Comment by martinholmer** [comment]
@talumbau said: 
> Re-opening until the fix is pushed.

Thanks.  I clicked the wrong button, but couldn't figure out how the re-open the mistakenly closed issue.
What's the trick?

**Comment by talumbau** [comment]
Oh I think the only option is the "Re-open and comment" button. So, I don't think you can click something just to re-open. I think you have to add a comment combined with the "re-open" action.

**Comment by martinholmer** [comment]
@talumbau said:
> Oh I think the only option is the "Re-open and comment" button. So, I don't think you can click something just to re-open. I think you have to add a comment combined with the "re-open" action.

Thanks for the tip!
