### ISSUE TITLE
TaxBrain missing EITC_MinEligAge and EITC_MaxEligAge parameters

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#228]
Given that Congressional staff have requested these parameters be included in TaxBrain and that the President has proposed a reform involving these parameters, it seems like we should add them as soon as possible.  There seemed to be a consensus that this was a good idea in issue #225.
What is the schedule for adding these parameters to TaxBrain?

@MattHJensen @talumbau

**Comment by MattHJensen** [comment]
@talumbau, could we include this in the upcoming TaxBrain release?

**Comment by talumbau** [comment]
pending PR: https://github.com/OpenSourcePolicyCenter/webapp-public/pull/230

**Comment by martinholmer** [comment]
Issue #228 resolved by pull request #230.
