### ISSUE TITLE
TaxBrain missing OLG parameter values in job-finished email

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#229]
When using the OLG model for dynamic analysis and accepting the default parameter values, one gets a job-finished email that contains the following information:
```
You used the following macroeconomic model parameters: {u'g_y_annual': u'', u'frisch': u''}
```
The absence of any information about the parameter values used is very confusing.
Why can't the email just say what parameter values were used?

@MattHJensen @talumbau

**Comment by talumbau** [comment]
seems reasonable. I'll take this.
