### ISSUE TITLE
TaxBrain handling of the * notation for delayed reform implementation

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#232]
Using TaxBrain version 0.6.3.8b7f3b, I try to double the 0.9% Additional Medicare tax rate beginning in 2018 (when the TaxBrain start year is 2016) by entering the following in that text box:
```
*,*,0.018
```
When I click on `Show me the results!`, I immediately get a new page that says:
```
500 Internal Server Error!
```
And there is no further explanation.  Did I do something wrong?  Or, is this a bug in TaxBrain?

@talumbau

**Comment by talumbau** [comment]
From checking the logs and local testing, this appears to be a Unicode processing issue, although I'm sure why it has not shown up until now. It is indeed a bug, because this input should be allowed.

**Comment by talumbau** [comment]
@martinholmer please try this again on TaxBrain. I can't explain how previously the text was not processing as Unicode but now is processing in Unicode, but either way I believe the issue is resolved.
