### ISSUE TITLE
Problem using * notation with vector parameter

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#235]
It appears that the `*` notation to delay implementation of a reform provision now works fine for scalar policy parameters.  However, it does not seem to work at all with vector policy parameters.   Below is an example:

[TaxBrain run 3627](http://www.ospc.org/taxbrain/edit/3627/?start_year=2016) has start year 2016 and specifies an increase for single filers in the Additional Medicare FICA Threshold beginning in 2016.  That reform is simulated just fine.

But if I try to delay the implementation of that reform by one year by entering `*,250000` in the text box (instead of `250000`), I get a `500 Internal Server Error!` message.

**Comment by talumbau** [comment]
closed via #236

**Comment by talumbau** [comment]
@martinholmer this fix is live on TaxBrain. please try at your convenience.

**Comment by martinholmer** [comment]
T.J. said:
> this fix is live on TaxBrain. please try at your convenience
Thanks again for the quick responses.
