### ISSUE TITLE
Revise EITC age parameter text to agree with Tax-Calculator

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#239]
When updating TaxBrain for other reasons, please change the two EITC age parameter titles to agree with the revised parameter definitions in [Tax-Calculator pull request 728](https://github.com/open-source-economics/Tax-Calculator/pull/728).

**Comment by martinholmer** [comment]
@talumbau,  I see there is a flurry of activity on TaxBrain.  Can the enhancement in issue #239 be included in the work?

**Comment by talumbau** [comment]
The text is read directly from the JSON file associated with a release of Tax-Calculator, so as to prevent specifying the text in two places. So, resolving this would mean cutting a new release of Tax-Calculator, which is not a big deal in terms of effort, but something that happens more cautiously now that the usage level is higher.

**Comment by martinholmer** [comment]
T.J. (@talumbau) said:
> The text is read directly from the JSON file associated with a release of Tax-Calculator, so as to prevent specifying the text in two places. So, resolving this would mean cutting a new release of Tax-Calculator, which is not a big deal in terms of effort, but something that happens more cautiously now that the usage level is higher.

I didn't know about the automatic reading of the parameter definitions.  Sounds very sensible.
I'll close this issue because now I understand that the new definitions will be automatically incorporated into TaxBrain with the next Tax-Calculator version.  Thanks for the explanation.
