### ISSUE TITLE
Results page Lorum Ipsum needs to be replaced

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#24]
_From @talumbau on May 12, 2015 18:33_

![results_page_text](https://cloud.githubusercontent.com/assets/1891418/7595233/61a76520-f8ab-11e4-9289-e5edc877bbc3.png)

I'm not sure what should actually go here. @MattHJensen, should this be changed to one or more flatbocks? Alternatively, if it is a sort of 'boilerplate' disclaimer message, do you have text you would like to be added?

_Copied from original issue: OpenSourcePolicyCenter/webapp#189_

**Comment by ospc-auto** [comment]
_From @MattHJensen on May 12, 2015 19:34_

Let's change this to one flatblock for now.

**Comment by talumbau** [comment]
closed via https://github.com/OpenSourcePolicyCenter/webapp-public/pull/39
