### ISSUE TITLE
Request: adding feature to highlight media coverage on home page

### ISSUE THREAD

**Issue by chilinhtran96** [OpenSourcePolicyCenter/webapp-public#246]
We want to highlight our media coverage by adding an end-of-site banner featuring our media mentions on online news sites. 

Where: OSPC home page www.ospc.org
Title: **As seen in**
Position:  right after “Updates from the field”
Format: a display of website logos that links to the contents in which OSPC is mentioned
Example: <see attachment>
![image](https://cloud.githubusercontent.com/assets/19432929/15365864/dc5c1a22-1cef-11e6-8ae4-d5f6cecdbacc.png)
Logos: <see attachment below>

Links to include:
Wall Street Journal	
http://www.wsj.com/articles/cracking-washingtons-black-box-1459723493

Real Clear Markets	http://www.realclearmarkets.com/articles/2016/04/13/as_tax_day_approaches_we_can_surely_do_better_102110.html

Washington Post	
https://www.washingtonpost.com/news/wonk/wp/2016/04/14/the-search-for-the-best-middle-class-tax-cut/

The Insider 	
http://www.insideronline.org/2016/04/understanding-middle-class-tax-cuts/

Mother Jones	
http://www.motherjones.com/kevin-drum/2016/04/we-need-quit-trying-cut-middle-class-income-taxes

Opportunity Lives	
http://opportunitylives.com/this-transparent-new-tool-could-fundamentally-change-how-politicians-make-policy/

Barron's	
http://online.barrons.com/articles/social-securitys-predictions-1431129373

![barrons](https://cloud.githubusercontent.com/assets/19432929/15365846/d12d3816-1cef-11e6-87d9-0edbfd19cf60.jpg)
![insiderweblogo](https://cloud.githubusercontent.com/assets/19432929/15365848/d131e028-1cef-11e6-80cf-6fdf7e1385bb.png)
![motherjones](https://cloud.githubusercontent.com/assets/19432929/15365850/d1321304-1cef-11e6-9351-08a3c962d940.png)
![opportunitylives](https://cloud.githubusercontent.com/assets/19432929/15365847/d131bcd8-1cef-11e6-944e-32d159f5fe29.png)
![rcm_logo_home](https://cloud.githubusercontent.com/assets/19432929/15365851/d13209e0-1cef-11e6-9036-673d8af2383d.jpg)
![wall-street-journal-logo](https://cloud.githubusercontent.com/assets/19432929/15365849/d131de52-1cef-11e6-96d5-1705391bf2e7.png)
![washington-post-logo](https://cloud.githubusercontent.com/assets/19432929/15365852/d132d5c8-1cef-11e6-8dd3-f3318717e0c5.jpg)

**Comment by chilinhtran96** [comment]
![image](https://cloud.githubusercontent.com/assets/19432929/15365976/50d5950e-1cf0-11e6-919c-4be364313142.png)

**Comment by MattHJensen** [comment]
Thanks @chilinhtran96. Let's drop "The Insider" piece since it is a pure reprint from Brill's paper.

**Comment by talumbau** [comment]
@chilinhtran96 @MattHJensen @mistakevin this is now deployed on ospc.org. Thanks all.

**Comment by MattHJensen** [comment]
Looks great! Thanks everyone.
