### ISSUE TITLE
js failures w/ latest version

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#249]
- The default values are showing by default now, rather than after a value has been edited. 
- We lost the information 'i's.

**Comment by talumbau** [comment]
Hmm.. perhaps I was using a cached version but I don't recall seeing this behavior last night. Would you like to roll back until we get a fix?

**Comment by MattHJensen** [comment]
I am ok with either. Whichever you think is easier/better.

**Comment by talumbau** [comment]
I think the i's are nice to have. Let me see if I can grab @mistakevin today and talk through the issue. If the fix is quick we can just do that. Otherwise I will rollback by end of day.

**Comment by talumbau** [comment]
Success! thanks @mistakevin
