### ISSUE TITLE
The user should select which year's parameters he sees in the 'parameters-used' section

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#25]
_From @MattHJensen on March 3, 2015 15:26_

There should be a "for 2xxx" dropdown under the 'parameters used' section. I.e., the user should be able to select which year's parameters he sees. 

This will allow us to not worry about, in the short run, how to display that someone used our cpi toggle feature or our comma-separated-param-for-different-years feature.

The simplest behavior would be to automatically default to displaying 2015 parameters (the first year in the 10-year budget window).
 
A more complicated behavior would be to default to displaying the same year of parameters as the year  that is selected for the tables, above. (and default to 2015 parameters, if the 10-year table is selected)

I am thinking dropdown would go between these two lines (inspired by the dropdown we use for selecting table year) 

![image](https://cloud.githubusercontent.com/assets/8301092/6465446/3231b398-c18f-11e4-851a-f96728f9f21c.png)

(as a project for phase 2, I hope we can allow our webapp users to download the plan x and plan y params.json files, and potentially even upload these jsons as well, at least for plan y)

_Copied from original issue: OpenSourcePolicyCenter/webapp#118_

**Comment by ospc-auto** [comment]
_From @zrisher on May 18, 2015 17:51_

Until this works, let's hide it.

**Comment by talumbau** [comment]
this will be superseded by a display of the JSON representing the parameter.
