### ISSUE TITLE
Deployment Enhancements

### ISSUE THREAD

**Issue by kevincolten** [OpenSourcePolicyCenter/webapp-public#251]
- [ ] Bundle JS and CSS with source maps for development
- [ ] Minify JS and CSS for deployment without source maps
- [ ] Add cache-buster/asset versioning for deployment
- [ ] Use Cloudfront for CDN w/ gzipping

**Comment by MattHJensen** [comment]
Closing this issue as there has been no progress since 2016. @kevincolten and @brittainhard, please let me know if you think it should be reopened.
