### ISSUE TITLE
TaxBrain "500 Internal Server Error!" bug for tax bracket reforms

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#257]
TaxBrain crashes when a user tries to specify a change in income tax brackets that are delayed one or more years after the TaxBrain start year.

For example, the 500 error is generated when start year is 2016 and the following is entered into the `Single` box under the title `Personal income tax bracket (upper threshold) 1`:
```
*,*,15000
```
This notation is specifying an increase in the top of the first income tax bracket beginning in 2018.

Trying to raise other brackets for single or other filing-unit types also produces the 500 error.

@talumbau @MattHJensen

**Comment by talumbau** [comment]
Ah, in this case we have the `*` syntax used with a field that has field validations. So, for example, for `II_brk1`, the validation we have to check is:

```
"validations": {"min": 0, "max": "_II_brk2"}
```

Therefore, in this case, the proper processing will involve filling out the wildcard entries, and then ensuring that the user-specified 2018 value is not greater than the 2018 value for `_II_brk2`. 

I'll take this on.

**Comment by talumbau** [comment]
The reason for the failure is that the field validation code is not currently able to handle wildcard entries. The validation happens prior to wildcard replacement so we'll have to do that differently.

**Comment by martinholmer** [comment]
@talumbau analyzed the needed changes and said:
> I'll take this on.

Thanks.  Please let me know when the public-version of Tax-Brain reflects your changes.

**Comment by talumbau** [comment]
The fix for this issue, PR #258, is this is now live on ospc.org (cc @martinholmer )

**Comment by martinholmer** [comment]
@talumbau said:
> The fix for this issue, PR #258, is this is now live on ospc.org (cc @martinholmer)
T.J.,  Thanks for the quick work on this issue.
