### ISSUE TITLE
TaxBrain "500 Internal Server Error!" bug for delayed _ID_Charity_frt reforms

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#259]
Using the `*` notation to specify the delayed (beyond TaxBrain start year) implementation of a change in value of the `_ID_Charity_frt` policy parameter causes a "500 Internal Server Error!" message.  This is the only remaining delayed reform bug that has been detected using the [sep-16-delay.json](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/taxbrain/sep-16-delay.json) file, which contains 79 separate delayed reforms.

@talumbau @MattHJensen

**Comment by talumbau** [comment]
@martinholmer this should be resolved on TaxBrain now, but I am not 100% certain of the reform you tried. If the issue is not resolved, please re-open and describe the entries that go in the text box as I am not 100% sure how the JSON file is used.

**Comment by martinholmer** [comment]
@talumbau Thanks.  Now my Tax-Calculator-vs-TaxBrain test that uses delayed reforms does not crash.
