### ISSUE TITLE
PDF Breaks With Login Requirement

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#26]
_From @theofanislekkas on February 18, 2015 15:56_

The pdf functionality is not producing the desired result while the login decorators are in place.  The pdf is returning an image of a page with the login fields instead of the table & the params used.

### NOTE: The pdf functionality is still not live

_Copied from original issue: OpenSourcePolicyCenter/webapp#91_

**Comment by talumbau** [comment]
This has been lingering for some time. Looking for help here. @zrisher @mistakevin

**Comment by johneo** [comment]
@talumbau PR #110

**Comment by talumbau** [comment]
no longer relevant.
