### ISSUE TITLE
Questionable TaxBrain dynamic partial-equilibrium results

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#260]
**Background**
I was looking, for the first time, at the Tax-Calculator `Behavior` class and `behavior` function (in order to get ideas about how to approach a new feature: endogenous consumption when calculating marginal tax rates).  I reviewed the source code in the `behavior.py` file and the unit tests in the `test_behavior.py` file.  Then I wrote a script to do some partial-equilibrium dynamic analysis (as the `behavior` function logic is called on TaxBrain) on my local computer.  That script was checked-in as [Tax-Calculator pull request #759](https://github.com/open-source-economics/Tax-Calculator/pull/759). The conversation associated with that pull request contains a few results obtained from that new script.  The following questions assume you have looked over those results.

**Questions**
When I try to reproduce those results with TaxBrain using the same reform and the same behavioral-response elasticities, I get [questionable results](http://www.ospc.org/dynamic/behavior_results/149/).

First, even though the TaxBrain static results show no changes in tax revenue for 2019 (the year before the reform), the TaxBrain dynamic results show large changes in both income tax and payroll tax revenues.  That is not what my script produces; it produces zero change in 2019 revenues in both the static analysis and the dynamic analysis.  Why does TaxBrain have dynamic, partial-equilibrium effects in years before the reform is implemented?

Second, for 2020, the first year of the pop-the-cap reform, the TaxBrain dynamic results are very different from the dynamic results generated by my new script.  TaxBrain has post-reform income tax revenue being $66.0 billion **higher** in the dynamic analysis (relative to the static analysis).  Remember this reform raises marginal tax rates on the top 1% or 2% of earners, and therefore, would be expected to cause a reduction in earnings among high earnings (because the assumed substitution elasticity is 0.25 and the assumed income elasticity is zero).  In my script, Tax-Calculator estimates (using the same reform and elasticities) that income tax revenue is $33.6 billion **lower** in the dynamic analysis (relative to the static analysis).  This is the qualitative result that one would expect given the assumed behavioral-response elasticities.  Why does TaxBrain produces counter-intuitive results (that differ substantially from those produced by Tax-Calculator on my computer) for income tax revenues after the reform is implemented?

And third, TaxBrain produces for 2020+ a massive reduction in FICA revenue in the dynamic analysis (relative to the static analysis).  That doesn't seem right; the Tax-Calculator produces a very small reduction.  Why does TaxBrain produce counter-intuitive results for payroll tax revenues after the reform is implemented?

I'm a novice at conducting this sort of partial-equilibrium dynamic analysis, but I have taken the time to read the first two papers on this topic that are cited on the TaxBrain partial-equilibrium page, and to create a script that produces seemly reasonable income tax revenue results for this reform.  I don't understand why the TaxBrain results are so different.  Did I do something wrong?

@MattHJensen @talumbau @feenberg @Amy-Xu

**Comment by feenberg** [comment]
On Mon, 30 May 2016, Martin Holmer wrote:

Note that my comments below may be wrong-headed if I am not understanding 
the question (which is likely). But they might be relevant, so I am 
volunteering them now.

> 
> Background
> I was looking, for the first time, at the Tax-Calculator Behavior class and behavior
> function (in order to get ideas about how to approach a new feature: endogenous
> consumption when calculating marginal tax rates). I reviewed the source code in the
> behavior.py file and the unit tests in the test_behavior.py file. Then I wrote a
> script to do some partial-equilibrium dynamic analysis (as the behavior function logic
> is called on TaxBrain) on my local computer. That script was checked-in as
> Tax-Calculator pull request #759. The conversation associated with that pull request
> contains a few results obtained from that new script. The following questions assume
> you have looked over those results.
> 
> Questions
> When I try to reproduce those results with TaxBrain using the same reform and the same
> behavioral-response elasticities, I get questionable results.
> 
> First, even though the TaxBrain static results show no changes in tax revenue for 2019
> (the year before the reform), the TaxBrain dynamic results show large changes in both
> income tax and payroll tax revenues. That is not what my script produces; it produces
> zero change in 2019 revenues in both the static analysis and the dynamic analysis. Why
> does TaxBrain have dynamic, partial-equilibrium effects in years before the reform is
> implemented?

A rational forward-looking utility-maximizing taxpayer who sees the 
upcoming increase in tax rates will substitute work now at the lower tax 
rate for work later at the higher tax rate (substitution effect). There 
will also be an income effect that causes the taxpayer to work harder to 
compensate for the higher taxes. By doing the additional work before the 
tax increase, less additional is required.


> 
> Second, for 2020, the first year of the pop-the-cap reform, the TaxBrain dynamic
> results are very different from the dynamic results generated by my new script.
> TaxBrain has post-reform income tax revenue being $66.0 billion higher in the dynamic
> analysis (relative to the static analysis). Remember this reform raises marginal tax

That seems wrong.

> rates on the top 1% or 2% of earners, and therefore, would be expected to cause a
> reduction in earnings among high earnings (because the assumed substitution elasticity
> is 0.25 and the assumed income elasticity is zero). In my script, Tax-Calculator
> estimates (using the same reform and elasticities) that income tax revenue is $33.6
> billion lower in the dynamic analysis (relative to the static analysis). This is the
> qualitative result that one would expect given the assumed behavioral-response
> elasticities. Why does TaxBrain produces counter-intuitive results (that differ
> substantially from those produced by T ax-Calcu lator on my computer) for income tax
> revenues after the reform is implemented?
> 
> And third, TaxBrain produces for 2020+ a massive reduction in FICA revenue in the
> dynamic analysis (relative to the static analysis). That doesn't seem right; the
> Tax-Calculator produces a very small reduction. Why does TaxBrain produce
> counter-intuitive results for payroll tax revenues after the reform is implemented?
>

That also seems wrong.


> I'm a novice at conducting this sort of partial-equilibrium dynamic analysis, but I
> have taken the time to read the first two papers on this topic that are cited on the
> TaxBrain partial-equilibrium page, and to create a script that produces seemly

Are you referring to Creedy, Saez, etc? Do they cover transitions? It has 
been a while since I read them, but I don't recall that they did. You are 
simulating a transition, and seeing transition effects.

dan

**Comment by martinholmer** [comment]
Dan @feenberg said:
> Are you referring to Creedy, Saez, etc? Do they cover transitions? It has been a while since I read them, but I don't recall that they did. You are simulating a transition, and seeing transition effects.

Yes, those are the papers I read, but I don't remember any discussion of transitions.  I think your final sentence exposes a vagueness in Tax-Calculator and TaxBrain.  When I say the reform is implemented in 2020 with an analysis start year of 2016, why do you assume the reform has become law at the beginning of 2016 (rather than at some later time)?  It seems entirely plausible to interpret a reform starting in 2020 to have been legislated in 2018 or even at the very end of 2019.  Should we add a Tax-Calculator parameter to specify the reform legislation year?  It seems as if we are missing that parameter in Tax-Calculator and you are assuming it is equal to the analysis start year (2016 in this case) and I'm assuming it is 2020 for immediate implementation.  Seems like either one of those two interpretations is plausible given the lack of a legislation-year parameter in Tax-Calculator.

But a far more important point is that this line of thinking seems unlikely to be the answer to my first question for the reasons I described above in my prior comment in this conversation: there is no forward-looking utility maximization going on in the Tax-Calculator `behavior` logic.

@MattHJensen @feenberg @Amy-Xu @talumbau

**Comment by feenberg** [comment]
On Mon, 30 May 2016, Martin Holmer wrote:

> 
> Dan @feenberg said:
>
>             First, even though the TaxBrain static results show no changes
>             in tax revenue for 2019 (the year before the reform), the
>             TaxBrain dynamic results show large changes in both income tax
>             and payroll tax revenues. That is not what my script produces;
>             it produces zero change in 2019 revenues in both the static
>             analysis and the dynamic analysis. Why does TaxBrain have
>             dynamic, partial-equilibrium effects in years before the
>             reform is implemented?
>
>       A rational forward-looking utility-maximizing taxpayer who sees the
>       upcoming increase in tax rates will substitute work now at the lower tax
>       rate for work later at the higher tax rate (substitution effect). There
>       will also be an income effect that causes the taxpayer to work harder to
>       compensate for the higher taxes. By doing the additional work before the
>       tax increase, less additional is required.
> 
> Perhaps so, but the Tax-Calculator behavior logic has no forward-looking
> utility-maximizing taxpayers; it has just a few assumed elasticities that are
> mechanically applied to the static tax reform effects. So, while what you say may be
> true in the real world, what you are describing does not seem to be happening in the
> simulated world of Tax-Calculator.

OK, there is a vocabulary issue here:

   partial equiblibrium
   static
   dynamic

I think static means no change in the data, and partial equilibrium means 
that an elasticity is applied to the data, but then what does dynamic 
mean if not forward-looking?

dan

**Comment by feenberg** [comment]
On Mon, 30 May 2016, Martin Holmer wrote:

> 
> Dan @feenberg said:
>
>       Are you referring to Creedy, Saez, etc? Do they cover transitions? It has
>       been a while since I read them, but I don't recall that they did. You are
>       simulating a transition, and seeing transition effects.
> 
> Yes, those are the papers I read, but I don't remember any discussion of transitions.
> I think your final sentence exposes a vagueness in Tax-Calculator and TaxBrain. When I
> say the reform is implemented in 2020 with an analysis start year of 2016, why do you
> assume the reform has become law at the beginning of 2016 (rather than at some later
> time)? It seems entirely plausible to interpret a reform starting in 2020 to have been
> legislated in 2018 or even at the very end of 2019. Should we add a Tax-Calculator
> parameter to specify the reform legislation year? It seems as if we are missing that

I am not sure there would be much demand for that, but it isn't a silly 
idea. In a forward looking model, it does make a difference when people 
learn of a tax change.

However, since the model isn't actually forward-looking, the point is 
moot.

dan

**Comment by martinholmer** [comment]
Dan @feenberg said:
> OK, there is a vocabulary issue here:
>
>   partial equilibrium
>   static
>   dynamic
>
> I think static means no change in the data, and partial equilibrium means that an elasticity is applied to the data, but then what does dynamic mean if not forward-looking?

I have no problem with your vocabulary, but it is inconsistent with TaxBrain vocabulary.

One of the three TaxBrain dynamic analysis options is the partial-equilibrium analysis using behavioral-response elasticities.  The logic of this partial-equilibrium analysis is not forward-looking, hence my question about why there is a behavioral response in years before the implementation of the reform.

Because there is no forward-looking logic in the Tax-Calculator `behavior` function logic, my guess, and it is nothing more than a wild guess, is that there is a bug in TaxBrain when it does the partial-equilibrium analysis.

@MattHJensen @feenberg @Amy-Xu @talumbau

**Comment by MattHJensen** [comment]
@martinholmer said:

> Because there is no forward-looking logic in the Tax-Calculator behavior function logic, my guess, and it is nothing more than a wild guess, is that there is a bug in TaxBrain when it does the partial-equilibrium analysis.

Yes, I believe this is correct. I am adding a "bug" label. 


---

As an aside: 

@feenberg  said:
> I think static means no change in the data, and partial equilibrium means that an elasticity is applied to the data, but then what does dynamic mean if not forward-looking?

@martinholmer said: 
> I have no problem with your vocabulary, but it is inconsistent with TaxBrain vocabulary.

@martinholmer is correct here. In the TaxBrain world (and to my knowledge, in the revenue estimation world) "dynamic" means that GNP is allowed to change in response to the tax change. Given that the "Partial Equilibrium model" can accommodate labor supply effects, I think it is appropriate to group it with other dynamic estimates. The Partial Equilibrium model can also accommodate elasticities that do not contain labor supply, in which case it is better thought of as a "conventional estimate".

**Comment by talumbau** [comment]
@martinholmer @MattHJensen there was a problem with wildcard entries propagating to partial equilibrium simulations. Please run your sim again and let me know. thanks!

**Comment by martinholmer** [comment]
@talumbau said:
> @martinholmer @MattHJensen there was a problem with wildcard entries propagating to partial equilibrium simulations. Please run your sim again and let me know. thanks!

I have rerun the TaxBrain partial-equilibrium analysis and the qualitative results are much better than before pull request #264.  However, I cannot determine whether the quantitative results from TaxBrain are the same as from Tax-Calculator because the version of Tax-Calculator being used by TaxBrain is so old (late April).

**Comment by martinholmer** [comment]
TaxBrain's use of the soon-to-be-released Tax-Calculator version 0.6.4 will enable a quantitative test of whether or not Tax-Calculator and TaxBrain produce the same dynamic partial-equilibrium estimates.
