### ISSUE TITLE
Set standard deduction to zero gives 500 Internal Server Error

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#261]
When I set the standard deduction amounts to zero I get the appropriate warning about the params being outside of the validation range. But when I re-run to accept the warning, I get an error. 

As an aside, the error page url isn't unique to my run (I guess that is only generated on a successful run), so it is difficult to share exactly what happened. 

![image](https://cloud.githubusercontent.com/assets/8301092/15750790/c178bebe-28b5-11e6-875e-28a3a078700f.png)

cc @talumbau

**Comment by MattHJensen** [comment]
Upon further investigation it appears setting EITC credit rate, max EITC amount, and bracket values to zero also result in 500 Internal Server Errors. According to an investigation by @GoFroggyRun these reforms do not create problems locally.

**Comment by talumbau** [comment]
resolved via #262
