### ISSUE TITLE
widget view enhancements

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#263]
For viewing a raw "taxplot" widget, we want to add additional functionality to the viz. This should include:
- [ ] email address entry (sign up)
- [ ] custom text entry
- [ ] watermarked logo placement
- [ ] attribution section (might be redundant with custom text entry)

**Comment by talumbau** [comment]
additional enhancements (not for initial version)

- [ ] custom google analytics events

**Comment by brendancol** [comment]
closing as stale
