### ISSUE TITLE
Progress 'Bar' for taxcalc runs

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#27]
_From @theofanislekkas on February 4, 2015 19:47_

Can a default time limit be set on the progress 'bar' button after the inputs are submitted for calculation. @thisaac @bmeisinger 

_Copied from original issue: OpenSourcePolicyCenter/webapp#74_

**Comment by ospc-auto** [comment]
_From @bmeisinger on February 5, 2015 22:51_

Right now we're using a CSS transition for the button that can be set to any time.

**Comment by ospc-auto** [comment]
_From @theofanislekkas on February 5, 2015 23:53_

@bmeisinger Ahh, great.  I think @talumbau was thinking 20 seconds for the default time.  I don't know how long the calculation currently takes (it's less than 20 though.)  Does it make sense from a UX point of view to have a longer default time for the progress effect to take place than the actual time of the calculation?  The concern is that we don't want the progress effect to end before the calculation does.

**Comment by ospc-auto** [comment]
_From @bmeisinger on February 6, 2015 16:53_

We think a more significant loader might be better in this instance as we don't want users to navigate away from the app. Possible a modal or a screen take over. Once you have a better idea of processing time maybe we can have a quick chat to determine what is best?

**Comment by ospc-auto** [comment]
_From @theofanislekkas on February 6, 2015 17:4_

@bmeisinger That makes sense.  I'll talk with @talumbau later today and will touch base with you.

**Comment by ospc-auto** [comment]
_From @zrisher on April 16, 2015 3:36_

Just thinking about how you could set this up to update progress in real time. It seems Celery jobs provide a `state` attribute, so this sounds plausible to me:

* `dropq.run_models` would report its status back to the calling job either via `yield` or a local callback, [example](http://codereview.stackexchange.com/questions/31789/is-using-yield-a-sensible-way-to-report-progress-of-data-processing)
* the calling job would update `job.state`, [example](http://www.dangtrinh.com/2013/07/django-celery-display-progress-bar-of.html)
* the view would query `job.state` and update the template to display the status. Alternatively, if the user has JS, you could direct them to a static waiting page where the JS does the polling instead of the HTTP. [example](http://stackoverflow.com/questions/7380373/django-celery-progress-bar)

**Comment by ospc-auto** [comment]
_From @zrisher on April 16, 2015 3:41_

With real time updates, you could say things like "Loading tax data", "Running year 1", "Preparing results", etc

**Comment by ospc-auto** [comment]
_From @talumbau on July 17, 2015 1:56_

The only thing we have here is a pretty cheezy re-load page. @MattHJensen, this would be a great place for a new contributor to dig in, if they have front-end experience.

**Comment by talumbau** [comment]
this is done
