### ISSUE TITLE
The results page for OGUSA simulations has the wrong title

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#271]
The page title is "Distribution and Revenue Tables for Federal Individual Income Taxes". That's not the proper title for the results displayed. It is the title we use for microsim results. What is the correct title for the results page for OGUSA runs? @MattHJensen @jdebacker @rickecon

**Comment by talumbau** [comment]
For example, this results page:

http://www.ospc.org/dynamic/results/155/

clearly has a bad title and it includes a drop-down for a year selection, but selecting a year does not change the table, since it already gives a 10 year view. Would a better title be:

"Differences in Macroeconomic Variables for Years 2016-2015"

Thoughts @MattHJensen @jdebacker @rickecon?

**Comment by jdebacker** [comment]
Yes, "Differences in Macroeconomic Variables for Years 2016-2025" makes sense (although the year range should correspond to the year input in the tax calc parameters).
