### ISSUE TITLE
latest feature requests on gallery

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#283]
from @MattHJensen 
- [x] Drop “Our sponsor” box from the gallery page.
- [x] Call it Vizualization Gallery instead of Vizualization Widget Gallery
- [x] Add a centered flatblock under "Vizualization Widget Gallery" where I can add a paragraph describing how these are made and pointing people ot the plots repo. (see comment below)
- [x] Check the social sharing links at the bottom - delete if broken and hard to fix.
- [x] change plot url from http://domain.com/widgets/tax_reform_viz_1/ to  http://domain.com/gallery/tax_reform_viz_1
- [x] alignment on mobile?
- [x] Add description text and acknowledgements to embed page.

**Comment by talumbau** [comment]
cc @brendancol

**Comment by talumbau** [comment]
from @MattHJensen:

Also, I thought this was true but based on the scaling behavior w/ mobile I should probably check: when someone embeds the plot, will the description text and acknowledgements come along for the ride? — they ought to.

**Comment by brendancol** [comment]
@MattHJensen @talumbau  Regarding:

> 
Add a centered flatblock under "Vizualization Widget Gallery" where I can add a paragraph describing how these are made and pointing people ot the plots repo.

There is already a flatblock centered underneath the title called `gallery_page_description`.  Was this enough or should I add another?

**Comment by MattHJensen** [comment]
@brendancol said:

> There is already a flatblock centered underneath the title called gallery_page_description. Was this enough or should I add another?


That should be fine. Is there a way for me to add some filler text here to see how it works on the test app? 

Alternatively, I am fine experimenting with this once the gallery is live at ospc.org -- it isn't imperative that the text be there immediately.

**Comment by brendancol** [comment]
@MattHJensen You should be able to test on the ospc staging site

**Comment by MattHJensen** [comment]
I am not seeing a flatblock labelled `gallery_page_description` on the test site. Here is what I see:

![image](https://cloud.githubusercontent.com/assets/8301092/17195752/ce767cb2-549a-11e6-8d6b-24af47a6d8db.png)

**Comment by MattHJensen** [comment]
> I am not seeing a flatblock labelled gallery_page_description on the test site. Here is what I see:

That said, I'm happy to test this on the live site.

**Comment by MattHJensen** [comment]
I'm still not seeing the gallery_page_description flatblock from the ospc.org admin. Unchecking the box for that todo.

**Comment by talumbau** [comment]
added `gallery_page_description` flatblock and verified that it's running on ospc.org. Checked the box to "done" for that item. The last remaining item is in regards to alignment on mobile.

**Comment by talumbau** [comment]
Viewing the gallery on an iPhone is a pretty reasonable experience. The text is centered and each visualization is vertically aligned:

![img_0729](https://cloud.githubusercontent.com/assets/1891418/20008744/bd302eda-a26f-11e6-8019-3a6b9d8196d3.PNG)

![img_0728](https://cloud.githubusercontent.com/assets/1891418/20008750/c25b3328-a26f-11e6-9e10-54f4e6e60871.PNG)

Leaving open for a while but this seems done to me.

**Comment by MattHJensen** [comment]
> Viewing the gallery on an iPhone is a pretty reasonable experience. The text is centered and each visualization is vertically aligned:

Agreed.
