### ISSUE TITLE
B-Tax tabular output

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#289]
This issue is to discuss the display of tabular output from the B-Tax calculator.

I've mocked up some [tables](https://github.com/OpenSourcePolicyCenter/webapp-public/files/391142/WebApp_OutputTable_Mockup.xlsx) that show a general format for the output (as well as the B-Tax object names that are used).

I've titled the tables "changes in...", intending for them to display the change in the values between the baseline and a reform.  I'd imagine users being interested in both the baseline and reform values themselves.  However, presenting levels and differences would expand this table from 6 to 18 columns of output values.  Too many for a default display, I think.

My initial thought is to do the following:
- Display two tables by default, changes in METRs by Asset and changes in METRs by Industry.  We can have one above the other on the screen, or (my preference not knowing how how this is to do) have tabs to move between the two.
- Similar to the "build table" choices on the Tax Calculator output, allow users to select on the first level, Baseline or Reform or Change.
- Allow a second level of the build table functionality where the user can select the type of variable to output: METR, METTR, Cost of Capital, Depreciation.
- Allow users to export tables as csv files.

@bfgard and I will begin work on having B-Tax output data frames akin to the tables proposed here.

cc @PeterDSteinberg, @MattHJensen

**Comment by MattHJensen** [comment]
@jdebacker, can this issue be closed?

**Comment by jdebacker** [comment]
@MattHJensen   - yes. This was closed via PR #392.  Download of files still not available, but that is now separate in Issue #327
