### ISSUE TITLE
B-Tax visual output

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#290]
This issue is to discuss visual output from the B-Tax calculator.  It relates to Issue #289, which discusses tabular output.

As an alternative (or addition) to the tabular output, we might present users with a graphical representation of the B-Tax calculations.

An example of this would be a cross-filter plot such as this (note: output plotted here is not current and does not display correct calculations):
![crossfilter](https://cloud.githubusercontent.com/assets/10715924/17260231/342fd50a-559d-11e6-9071-29c3485d1015.png)

The data that underlies this figure is the same that that proposed in the tabular output in Issue #289.  Therefore, the outputs from the calculator that are used in the UI remain largely the similar and the tabular and visual output are close substitutes for users.

My inclination is to first get a B-Tax web app working with tabular output and resolve any issues with that.  Once that's up, we can transition to output that presents the visualization by default with options to view the tabular data and output csv files.

cc @bfgard, @PeterDSteinberg, @MattHJensen

**Comment by talumbau** [comment]
this is now handled via the "plots" repo, with the user-contributed code here:

https://github.com/open-source-economics/plots/tree/master/contrib/corp_metr
