### ISSUE TITLE
Refine sign in flow

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#3]
_From @MattHJensen on August 6, 2015 23:53_

There are a couple of confusing aspects of our sign in process. 
1. The sign up field does not indicate that it is the source of access to TaxBrain
2. Neither the TaxBrain slide on the home page nor on the "apps" page tells you how to sign up. 

Anyone notice other confusing aspects? 

Notes:
- It seems wise that we merged news signup with TaxBrain signup. 
- Later we may want a contributor mailing list/newsletter, but that will be different and won't need to be on the OSPC homepage. 

_Copied from original issue: OpenSourcePolicyCenter/webapp#253_

**Comment by zrisher** [comment]
It seems to me we could fix most of the problems with a few changes to the login page:

There should be a notification at the top if you've been redirected from a resource that requires authentication, i.e. "you must log in to [use taxbrain | view news]"
the login and password fields should be centered and have bottom margin equal to the top
There should be a link to the new account page
There should be some text that explains new accounts are free and we won't track you or send you annoying emails. Probably best accomplished with a flatblock.

**Comment by MattHJensen** [comment]
@amfarrell and @talumbau, do you have any ideas on this one? If there were a quick fix here, I think it would improve the UI quite a bit while we wait for the 2009 puf. (a couple of people have come to me confused about this).

**Comment by mistakevin** [comment]
> There should be a link to the new account page

There is no single link to the account creation page. You have to go through the newsletter subscription first.

The current flow goes:
1. Enter email on homepage (for seemingly **only** the newsletter)
2. Receive confirmation email with new account activation link (mention of authorized use of taxbrain)
3. Click **unique link** in email, directs to account creation page.
4. Create an account. Save. Redirect to a page that suggests returning to home page or taxbrain
  * Also get email with username/password, with mention of taxbrain

We could:
1. Separate the newsletter/account creation
2. Remove the unique "account creation link" email step
3. Replace it with a "Create an Account" link on the homepage
4. After registering, send a "Confirm email address" email with a unique link.
5. Direct user to a "Thank you for confirming" page that mentions taxbrain

**Comment by zrisher** [comment]
Yep, I like all of @mistakevin's suggestions. Newsletters and accounts have different purposes and intended audiences, even if they are linked by User.

**Comment by MattHJensen** [comment]
This makes sense to me as well. We will also want the "create an account" link on the TaxBrain signin page.

**Comment by talumbau** [comment]
OK great. @mistakevin it sounds like we have consensus. Blast away and post a PR when you are ready.

**Comment by talumbau** [comment]
OK, to clarify these "user stories" are what is desired:

1. Go to ospc.org, put email address in box, click "Sign Up!", Get email confirmation that you have signed up. Done.

2. Go to ospc.org, click "Register" button in upper right. Go to Register page. Put in email address, username, name, password, Click Register. Get email confirming registration, with unique link URL that must be clicked to confirm.

If user does only action 1., they don't end up with a login account for the site. Also, someone could put an email address that is not their own in to the page and sign someone up for the newsletter. This does not seem good.

If user does action 2, they don't end up with a real registered account until they click the unique link in their email address. That seems good.

Looking for input here @MattHJensen

**Comment by talumbau** [comment]
User sign-up needs a re-design.
