### ISSUE TITLE
Deviation from CBO baseline bug

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#300]
http://www.ospc.org/taxbrain/edit/4900/?start_year=2016

A user added 50% to the baseline CBO growth rate generated very odd results. 

@GoFroggyRun, could you try to reproduce with Tax-Calculator? 

It could be that the feature works for more modest deviations, so try something like 0.05 as well.

**Comment by MattHJensen** [comment]
> It could be that the feature works for more modest deviations, so try something like 0.05 as well.

No, that doesn't work either: http://www.ospc.org/taxbrain/4903/

**Comment by MattHJensen** [comment]
@talumbau, let's hide the entire growth section for now. Besides it being broken, the UI probably needs more thought so it doesn't confuse people with dynamic scoring. 

I'm checking now to see if we will need an accompanying patch to the TaxBrain-TC validation suite in TC. 

@GoFroggyRun, this means that the testing is not urgent and needn't distract you from the CEX work -- could you just open an issue in TC, I'll assign it to you if you can't assign it to yourself, and then you can circle back when you have a chance.

**Comment by MattHJensen** [comment]
As far as I can tell the growth capabilities on TaxBrain are not being tested in taxcalc/taxbrain.

**Comment by GoFroggyRun** [comment]
@MattHJensen said:
>
this means that the testing is not urgent and needn't distract you from the CEX work -- could you just open an issue in TC, I'll assign it to you if you can't assign it to yourself, and then you can circle back when you have a chance.

Got you. I have just opened this issue in TC.

**Comment by talumbau** [comment]
FWIW, the reform dictionary passed in [4903](http://www.ospc.org/taxbrain/4903/) is essentially:

```
{2016: {'_factor_adjustment': [0.05]}}
```

If that is correct, then the issue is on the Tax-Calculator side. If that is not the correct reform for what the user did, then the problem is on the web app side.

**Comment by MattHJensen** [comment]
Thanks @talumbau. I'll leave a note on https://github.com/open-source-economics/Tax-Calculator/issues/860 to open an issue over here at webapp-public once things get figured out over there.
