### ISSUE TITLE
Add CCC to the OSPC home page "from the lab" section

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#311]
We could just mirror the TaxBrain format, even keeping the gears in the background if need be.

![image](https://cloud.githubusercontent.com/assets/8301092/17814146/6633682c-65fc-11e6-9bdb-c74e8cb7bb52.png)

**Comment by talumbau** [comment]
@MattHJensen should this be a box that is below the FROM THE LAB text but above the TaxBrain box in your screen cap? Or should the CCC box be below the TaxBrain box?

**Comment by MattHJensen** [comment]
@talumbau Let's put new stuff on top.

**Comment by talumbau** [comment]
this is resolved in #407 but we can move it to its own PR if there is too much work left in #407. I don't think that's the case (just need a new JS function and the HTML button for refreshing parameters to call this JS function).

**Comment by talumbau** [comment]
closed via #407
