### ISSUE TITLE
Add TaxBrain ability to specify run using JSON reform file

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#312]
The discussion beginning around August 1, 2016, concerning [Tax-Calculator issue #429](https://github.com/open-source-economics/Tax-Calculator/issues/429#issuecomment-240692920) has concluded that we want to enhance TaxBrain to be able to handle an alternative way of specifying policy reforms.  In addition to the text-box and check-box approach currently used by TaxBrain, we want to give users the option to bypass that approach and specify a reform using a JSON file as can be done when using the inctax.py interface to Tax-Calculator.

This TaxBrain enhancement would use existing Tax-Calculator capabilities, so this enhancement requires no changes to Tax-Calculator.  There is an example of a JSON reform file in the test_incometaxio.py file [REFORM_CONTENTS string](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/tests/test_incometaxio.py#L173-L208).  And there is a [Policy class static method](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/policy.py#L174-L209) that reads a JSON reform file and returns a dictionary that can be passed to the Policy class implement_reform method.

Here are some of the features this new TaxBrain capability should probably have:

(1) the ability to specify a local JSON reform file for uploading to TaxBrain;

(2) syntax checking that indicates illegal JSON;

(3) a way of saving the reform file associated with TaxBrain run results;

(4) a way of editing a saved reform file to generate a new TaxBrain run;

(5) a way of downloading a saved JSON reform file.

I don't use TaxBrain often, so I don't have much experience with the work flow.  I'm hoping that others with more TaxBrain experience will revise and/or add to this list of features.

@MattHJensen @talumbau @feenberg @Amy-Xu @GoFroggyRun @zrisher

**Comment by feenberg** [comment]
(2) Syntax checking is presumably a security issue - perhaps the best thing to do here is to use a pre-existing conversion tool to convert from JSON to some other format and read that, assuming the conversion tool would balk at problematic input. Writing our own checker seems like a fair amount of work and risk.

(3,4) Once we have taxbrain results, won't there be a run number, and can't that work as a way of saving run results? 

(5) Obtaining JSON from taxbrain  would be a link from the results page - probably should be available for any run, not just runs originating with user generated JSON. Should this include all parameters or just non-default parameters?

I am still hoping for the results page to have a summary of the tax reform. That is, a listing of the non-default tax parameters that would print with the results. This would be an opportune time to add that.

**Comment by martinholmer** [comment]
Dan Feenberg said:
> (2) Syntax checking is presumably a security issue - perhaps the best thing to do here is to use a pre-existing conversion tool to convert from JSON to some other format and read that, assuming the conversion tool would balk at problematic input. Writing our own checker seems like a fair amount of work and risk.

Checking for correct JSON syntax is not just a "security issue".  Incorrect JSON will not translate into a reform dictionary.  The existing Policy.read_json_reform_file() static method does raise a ValueError when invalid JSON is encountered, but it doesn't point out the offending line.  It just suggests the user use a [free JSON syntax checking website](jsonlint.com) to find the error(s).  It would be nice for our users to have this feature built into TaxBrain.  I'm imagining that there are existing Python packages that can be used to do the JSON syntax checking.

> (3,4) Once we have taxbrain results, won't there be a run number, and can't that work as a way of saving run results?

Yes, but (3) discusses saving the uploaded reform file, not the run results, which are already being saved by TaxBrain.

> (5) Obtaining JSON from taxbrain would be a link from the results page - probably should be available for any run, not just runs originating with user generated JSON. Should this include all parameters or just non-default parameters?

I'm not sure what you are suggesting here.

> I am still hoping for the results page to have a summary of the tax reform. That is, a listing of the non-default tax parameters that would print with the results. This would be an opportune time to add that.

Perhaps each run can have a JSON reform file associated with it.  The JSON reform file would already be available for runs specified using a JSON reform file.  For runs specified using the current TaxBrain method (using text-boxes and check-boxes), perhaps somebody could write a new Policy class method that translates a reform dictionary into a JSON reform file.  If we did that, there would be a way to describe every policy reform submitted to TaxBrain.

@MattHJensen @talumbau @feenberg @Amy-Xu @GoFroggyRun @zrisher

**Comment by feenberg** [comment]
On Sat, 20 Aug 2016, Martin Holmer wrote:

> 
> Dan Feenberg said:
>
>       (2) Syntax checking is presumably a security issue - perhaps the best
>       thing to do here is to use a pre-existing conversion tool to convert from
>       JSON to some other format and read that, assuming the conversion tool
>       would balk at problematic input. Writing our own checker seems like a fair
>       amount of work and risk.
> 
> Checking for correct JSON syntax is not just a "security issue". Incorrect JSON will

I thought it was especially important because it was a security issue. 
That rather means we have to get it right before beta.

> not translate into a reform dictionary. The existing Policy.read_json_reform_file()
> static method does raise a ValueError when invalid JSON is encountered, but it doesn't
> point out the offending line. It just suggests the user use a free JSON syntax
> checking website to find the error(s). It would be nice for our users to have this
> feature built into TaxBrain. I'm imagining that there are existing Python packages
> that can be used to do the JSON syntax checking.
>

I hope this doesn't become another dependency. Does nothing in standard 
libraries return a line number of errors? I see this:

    https://codedump.io/share/rBrAeFYEKGhV/1/python-jsonloads-fails-with-valueerror-invalid-control-character-at-line-1-column-33-char-33

which suggests there might be.

>       (3,4) Once we have taxbrain results, won't there be a run number, and
>       can't that work as a way of saving run results?
> 
> Yes, but (3) discusses saving the uploaded reform file, not the run results, which are
> already being saved by TaxBrain.

Doesn't TaxBrain save both? How else can it rerun a run? Does it not save 
parameters as JSON?

>
>       (5) Obtaining JSON from taxbrain would be a link from the results page -
>       probably should be available for any run, not just runs originating with
>       user generated JSON. Should this include all parameters or just
>       non-default parameters?
> 
> I'm not sure what you are suggesting here.

I understood that there were defaults for all tax parameters, and that a 
JSON file of tax parameters need not include all parameters, only those 
that are not left at the default value. Similarly, if we are outputting a 
JSON file of tax parameters, do we want to include all of them, or only 
those that are not at the default value? The advantage of the latter is 
that it makes it clear to the reader what has been tinkered with.

>
>       I am still hoping for the results page to have a summary of the tax
>       reform. That is, a listing of the non-default tax parameters that would
>       print with the results. This would be an opportune time to add that.
> 
> Perhaps each run can have a JSON reform file associated with it. The JSON reform file
> would already be available for runs specified using a JSON reform file. For runs
> specified using the current TaxBrain method (using text-boxes and check-boxes),
> perhaps somebody could write a new Policy class method that translates a reform
> dictionary into a JSON reform file. If we did that, there would be a way to describe
> every policy reform submitted to TaxBrain.

This is really important. I am used to seeing distribution tables with 
only vague descriptions of the reform being scored - and in Matt and Amy's 
attempts to reproduce TPC and other scores I notice that they are also 
frustrated by incomeplete specifications. If we can provide a complete and 
accurate specification of the reform in a compact printout, that would be 
a good thing.

dan

**Comment by martinholmer** [comment]
Dan Feenberg said:
> I hope this doesn't become another dependency. Does nothing in standard libraries return a line number of errors? I see this:
>
>    https://codedump.io/share/rBrAeFYEKGhV/1/python-jsonloads-fails-with-valueerror-invalid-control-character-at-line-1-column-33-char-33
>
> which suggests there might be.

I have no idea about the best way to provide TaxBrain users with some idea about how to correct their invalid JSON.  All I know is that it would be more user-friendly to give them some idea of where the error is in their JSON reform file than to simply say the provided JSON is invalid.  I'm assuming that the TaxBrain developers will have good ideas about how best to provide this feature.

> Doesn't TaxBrain save both?  How else can it rerun a run?  Does it not save parameters as JSON?

I have no idea about how tax reform parameters are stored in TaxBrain.  I doubt they are stored as JSON reform files, but perhaps T.J. can enlighten us.

> I understood that there were defaults for all tax parameters, and that a JSON file of tax parameters need not include all parameters, only those that are not left at the default value. 

Your understanding is correct.

> Similarly, if we are outputting a JSON file of tax parameters, do we want to include all of them, or only those that are not at the default value?

Only "those that are not at the default value".  Please look at the example JSON reform file pointed to in my original comment in this issue #312.

> The advantage of the latter is that it makes it clear to the reader what has been tinkered with.

Precisely.  That is what is being discussed here.

@MattHJensen @talumbau @feenberg @Amy-Xu @GoFroggyRun @zrisher

**Comment by zrisher** [comment]
> (2) I have no idea about the best way to provide TaxBrain users with some idea about how to correct their invalid JSON. All I know is that it would be more user-friendly to give them some idea of where the error is in their JSON reform file than to simply say the provided JSON is invalid. I'm assuming that the TaxBrain developers will have good ideas about how best to provide this feature.

Sure, one of the cool things about Javascript Object Notation is that javascript understands it. :smile: It looks like we're using five different javascript frameworks, so I'm sure we can rely on one of those for client-side checking. You'd want to check it server-side after it's been posted, but you can rely on more general errors there.

> I have no idea about how tax reform parameters are stored in TaxBrain. I doubt they are stored as JSON reform files, but perhaps T.J. can enlighten us.

They are stored as attributes on a model representing the user input. This might be a good time to consider refactoring that model to just store a JSON reform string. I know it would be a lot of changes, but it might significantly simplify much of the logic in this app.

**Comment by martinholmer** [comment]
@zrisher said:
> Sure, one of the cool things about Javascript Object Notation is that javascript understands it. 😄 It looks like we're using five different javascript frameworks, so I'm sure we can rely on one of those for client-side checking. You'd want to check it server-side after it's been posted, but you can rely on more general errors there.

Good to know that this will not request use of any new software libraries --- Dan @feenberg was concerned about that.

@zrisher also said:
> They [TaxBrain policy parameters] are stored as attributes [in a database] representing the user input. This might be a good time to consider refactoring that model to just store a JSON reform string. I know it would be a lot of changes, but it might significantly simplify much of the logic in this app.

I would be much more efficient to do this, but I guess there is a transition cost.  After paying the transition costs, are there any disadvantages to this approach relative to the current approach?

@talumbau @MattHJensen

**Comment by talumbau** [comment]
I think there's a lot going on in this issue. I'll focus on what I think can reasonably be provided for the user interface w/o too much effort:

1. An interface to allow someone to specify JSON for their reform (*).
This would basically be a text box accepting JSON input. @zrisher if you are interested in taking on the task of verifying the JSON on the front end, please let me know. We could provide some amount of error feedback using just the `json.loads` function in Python. For example, I intentionally messed up `current_law_policy.json` and got the following message when loading the file:

```
JSONDecodeError: Expecting ':' delimiter: line 1584 column 19 (char 65177)
```

which seems pretty good. It would not be too hard to push such an error message back up to the user.

2. For TaxBrain jobs that are created with the interface described above, the `Edit Parameters` button on the results pages for such jobs would take one back to the JSON entry page with the user's JSON entry already filled in. One would not go back to the typical TaxBrain input page with the JSON entry translated in to a page with data already filled in. The main reason this is not feasible is because the set of reforms representable by a JSON dictionary is a superset of the reforms one can make with the TaxBrain input page.

3. For any TaxBrain job, we can add a section to the results page that allows one to download a JSON representation of the reform (**). Seems like this would make debugging very clean and would make things very transparent.

Caveats:

* - A single JSON blob would currently be insufficient to describe all possible TaxBrain jobs (even with just the microsim). The reason is that a couple of parameters (e.g. growth parameters like `_factor_adjustment`) are specified as a separate piece of data to Growth objects. So, to really provide the full capability to specify JSON instead of using the TaxBrain interface, we would need three text boxes: a policy reform box, growth parameters box, and a behavior parameters box.

** - because of the discussion in (*) when a user downloads a JSON representation of the reform, they would likely get back a text file that would have up to three separate JSON objects in it, due to the different policy, growth, and behavior sections one can specify.

**Comment by zrisher** [comment]
>@zrisher if you are interested in taking on the task of verifying the JSON on the front end, please let me know. 

@talumbau I will need to check in with Matt on my priorities for next month, but happy to take this on if it's in the list. 

> We could provide some amount of error feedback using just the json.loads function in Python... It would not be too hard to push such an error message back up to the user.

Agreed sounds like a good strategy for the server response.

> So, to really provide the full capability to specify JSON instead of using the TaxBrain interface, we would need three text boxes: a policy reform box, growth parameters box, and a behavior parameters box.

Sounds pretty awesome to me. : )

**Comment by martinholmer** [comment]
Over a month ago, @MattHJensen asked me to raise an issue describing the outlines of TaxBrain enhancement that would allow TaxBrain users to upload JSON policy reform files like those accepted by the `inctax.py` and `simtax.py` command-line interfaces to the taxcalc package.  That issue #312 generated considerable discussion during its first few days, but there has been no discussion for over three weeks.  And there has been no visible progress at implementing this enhancement.  So, my questions, @talumbau, is where do things stand on this enhancement?

**Comment by talumbau** [comment]
yes this issue has been lingering. A couple of questions that would help me understand if we can proceed: 

1. Are the initial interface restrictions (and associated caveats) that I describe in my previous message on this issue acceptable? So, roughly that is: JSON upload page is three boxes, "Edit Parameters" pages for JSON-based TaxBrain jobs are JSON input pages

2. Which is a higher priority: providing a JSON download of any TaxBrain job? or the JSON input capability?

**Comment by martinholmer** [comment]
@talumbau said:
> Yes this issue has been lingering. A couple of questions that would help me understand if we can proceed:
>
> (1) Are the initial interface restrictions (and associated caveats) that I describe in my previous message on this issue acceptable?  [Which were:]
>
>>  So, to really provide the full capability to specify JSON instead of using the TaxBrain interface, we would need **three** text boxes: a policy reform box, growth parameters box, and a behavior parameters box.  So, when a user downloads a JSON representation of the reform, they would likely get back a text file that would have up to three separate JSON objects in it, due to the different policy, growth, and behavior sections one can specify.

This is fine.  But the most important, by far, is the policy reform box that can be used to upload JSON policy reform files.  So, you should consider doing this development work in steps: add the policy reform file upload capability first, then use what you've learned to add the other two upload boxes.

> (2) Which is a higher priority: providing a JSON download of any TaxBrain job or the JSON input capability?

No question about it: the top priority is the input or upload capability.  Download would be nice but the main bottleneck is that the current TaxBrain interface cannot (and should not be expected to) handle the full range of reforms that the taxcalc package can simulate.  We need to remedy that problem as soon as possible.

@MattHJensen @feenberg @amfarrell @GoFroggyRun @zrisher

**Comment by talumbau** [comment]
this feature is now live at ospc.org/taxbrain/file
