### ISSUE TITLE
CCC UI: B-Tax start year change gives error

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#321]
Currently, one gets a 404 error if the start year is changed from the default value of 2016.  I've opened [another issue](https://github.com/open-source-economics/B-Tax/issues/78) for the B-Tax calculations to reflect changes in start year, but the UI should handle them as well.

**Comment by talumbau** [comment]
@jdebacker there is no longer a 404 when selecting a different default start year (this was fixed via  1ea704cae810dc61aa4fc5075296f4ff91e3e00b). However, I don't believe the start year is actually propagating to the `btax` package and modifying the start year of the simulation. Can you or @PeterDSteinberg point me to some `btax` code that shows how the start year should be fed into the calculation? If I can have that, this should be a quick fix.

cc @MattHJensen

**Comment by jdebacker** [comment]
@talumbau - thanks for looking at this.  You're right that the year is not being fed into B-Tax.  I can add the script to pass this through, but am not sure on how this will work.  

I think what we want to do is to have the btax_defaults.json adjust the defaults as different years are selected.  Then the business tax parameter defaults will be passed to B-Tax in the current way.  In addition, I will need to take the year variable and pass that to B-Tax as well to adjust the start year for the Tax-Calculator run.  

Two questions:
1) Does this change to the default values json sound right?
2) What will be the name of the year object coming from the UI that I'll feed into B-Tax?

cc @PeterDSteinberg

**Comment by talumbau** [comment]
If you tell me that calling the `run_btax_to_json_tables` function with `start_year` set to the desired year will produce the output you want - I'm referring to this function:

https://github.com/open-source-economics/B-Tax/blob/master/btax/run_btax.py#L124

then I can make everything work with a small change. Is this the right place to plug in the year from the UI?

**Comment by jdebacker** [comment]
@talumbau calling that with the `start_year` set to the desired year will help update the start year for the Tax-Calculator run that produces the tax rates we use.  

BUT one also needs to change the business tax parameters (namely bonus depreciation), which changes based on the year.  I can do this in B-Tax, but I think it'd be better if the year change in the UI changes the default values pulled from `btax_defaults.json`.  I say this because this will then update the default values entered on the screen in the web app.

Sound ok?

**Comment by talumbau** [comment]
Isn't it true that calling the `parameters.get_params` with the appropriate `start_year` with get the appropriate business tax parameters? I am referring to the function here:

https://github.com/open-source-economics/B-Tax/blob/master/btax/run_btax.py#L77

If what I am saying is true (that `parameters.get_params` called with the appropriate start year wil get the values you describe) then everything is OK because the `start_year` argument in `run_btax_to_json_tables` is passed to this function via the `run_btax` function.

If what I am saying is incorrect, then I still think we should modify the function `run_btax_to_json_tables` to work such that the start year applies to both the `taxcalc` run and the business tax parameters.

Let me know if I am correct or incorrect so I will know what to do next for this issue.

**Comment by jdebacker** [comment]
TJ, you are incorrect.  I still need to update `parameters.get_params` to update the business tax parameters based on the start year.  I can do this now - I just wasn't sure if we needed to do that if the json file containing the parameters defaults were updated (which I still think it would need to be so that the web app presents the defaults that correspond to the chosen start year).

**Comment by talumbau** [comment]
Ah, I get it now. Yes, we have something for `taxcalc` that does this. The general idea is that we need a function that can take a start year and give back default parameters for that start year. So with `taxcalc`, we have [`default_data`](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/parameters.py#L21) in ParametersBase which we can call with different start years to get the defaults that should be displayed to the user. Right now, in the web app, we essentially just grab the `DEFAULTS` dictionary from the `btax` package and get the values out of there. I noticed that there are not years in [btax_defaults.json](https://github.com/open-source-economics/B-Tax/blob/master/btax/param_defaults/btax_defaults.json) in master. Does this functionality exist right now in `btax` (i.e. call a function with a certain start year and get back default parameters)? If yes, we can use it on the web app. If not, is that something that I should write, you should write, or maybe @PeterDSteinberg?

**Comment by jdebacker** [comment]
@talumbau It does not exist.  I'm looking at Tax-Calc now and am trying to copy that over.  Give me 30 min on this and I'll open a PR.  I'll notify you all of that and any questions I have.  Also, I'll just be working in B-Tax and not the web app.  If you or @PeterDSteinberg could help with that, it'd be great.

**Comment by talumbau** [comment]
yes no problem there. The `taxcalc` version is quite general - probably no need to be as fancy with `btax`. If you can add the function and a test that shows how to use it, should be no problem on my part to add it in to the web app.

**Comment by MattHJensen** [comment]
@talumbau and @jdebacker, I think it is important to have this ability, but for the sake of our next release, how about resolving this issue #321 by hiding the "change start year" from CCC? 

Then we can add a new issue w/o the bug label and w/o the next release label for adding back the change start year feature and have enough time for testing. We can add that to a release whenever we think it is ready.

**Comment by talumbau** [comment]
ok sounds good. I'm working on a PR for some of these CCC issues so I will add that in.

**Comment by jdebacker** [comment]
FYI, [this PR](https://github.com/open-source-economics/B-Tax/pull/107) allows B-Tax to accept and use a flexible start year to update both business and individual tax parameters.
