### ISSUE TITLE
CCC UI: Default value for non-corp entity tax rate

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#322]
We have the default rate on non-corporate entities shown to be 0.35.  Is there a way to make this change conditional on other inputs?  In particular, to have the default rate be 0.0, but if the non-corporate entity level tax indicator is checked, then this default is changed to 0.35 (or whatever is entered in the corporate tax rate box above)?  

As it stands, I can see people asking questions like "why do you have the default rate on NC entities at 0.35 when it is 0.0?"  But I like the idea that if one wanted to institute a comprehensive business income tax, the default is to take all entities at the same rate.

**Comment by talumbau** [comment]
hmm.. this can be done by custom JS code. @zrisher @brendancol, I'm trying to think of a good way to specify this logic so that we don't have just a jumble of custom javascript that handles these cases. Ideas?

**Comment by MattHJensen** [comment]
> In particular, to have the default rate be 0.0, but if the non-corporate entity level tax indicator is checked, then this default is changed to 0.35 (or whatever is entered in the corporate tax rate box above)?

@jdebacker, would an easier option to begin with to just make the non-corporate entity level rate be 0.0 under current law and then get rid of the indicator? It seems to me that the indicator is logically redundant, although i can see how it might improve UI if it worked as you are requesting here.

**Comment by jdebacker** [comment]
@MattHJensen 's suggestion is good. We can eliminate check box and do that since it sounds like a lot of trouble to do otherwise.
