### ISSUE TITLE
CCC UI: Info buttons on the depreciation rules

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#323]
Can we have info buttons on the depreciation rules table headers?  e.g. on ADS, GDS, etc.  These need some explanation.

If we can get these, I think we can omit the "Rate of bonus on n-year class property" and thus simplify and condense the table.

**Comment by MattHJensen** [comment]
@jdebacker, do you want this text to reside in webapp-public as flatblocks or in B-Tax? (@talumbau/@brendancol, is one of these much easier?)

**Comment by jdebacker** [comment]
I like having them in the json files in B-Tax and accessed on the web app via mousing over the (i) button.  I feel like that allows one to have a lot of information without cluttering the UI.  But happy to defer to these others who are more experienced.

**Comment by talumbau** [comment]
I don't think we could do a flatblock for hover overs (not 100% sure but I think it would be tricky). Getting the text from a JSON file and displaying the text as a hover over for a button is what we currently do for TaxBrain so I would suggest we go that route here.

**Comment by talumbau** [comment]
@jdebacker does the desired text already exist? If yes, can you point me to it?

**Comment by jdebacker** [comment]
I think we could just pull from the "notes" filed in the `btax_defaults.json` file. @talumbau

**Comment by talumbau** [comment]
Ok, I thought I understood then but it turns out I don't understand. In the `btax_defaults.json`, each item does have a notes section, but it's not clear to me which text should pop up when one hovers over the "ADS" text in the ADS column on the input page. Similar question for "GDS" and "Economic."

**Comment by jdebacker** [comment]
Ah, I see, the notes read something like:

> "This parameter is an indicator for the use of the Alternative depreciation System (ADS) on 27.5-year class property."

So they are specific to each class of property.  I think for the hover-over at the top of the column, we just want to be a bit more general.  E.g.,

> "This parameter is an indicator for the use of the Alternative depreciation System (ADS)."

Can we create another variable for such text?

**Comment by talumbau** [comment]
Yes that would be great.

**Comment by jdebacker** [comment]
@talumbau  See [here](https://github.com/open-source-economics/B-Tax/pull/108)

**Comment by talumbau** [comment]
@jdebacker the current version of `btax` used for CCC is at commit https://github.com/open-source-economics/B-Tax/commit/06fb537a1d9833185255b21a74bbca6d2d20ebcc from October 6. If I put in the changes from your merged [PR](https://github.com/open-source-economics/B-Tax/pull/108) on B-Tax, we will have all of the changes to B-Tax made since then running on CCC. Let me know if this is correct and we should be able to wrap up this issue pretty quickly.

**Comment by jdebacker** [comment]
@talumbau Sounds right.  I do have [this open PR](https://github.com/open-source-economics/B-Tax/pull/107), but given your recent change remove the start year from the webb app, maybe we just leave that PR open for now and don't merge into CCC (although it would not cause any issue to do so - the default is set to 2016 there as well).

**Comment by talumbau** [comment]
@jdebacker here is what the hover overs look like. Let me know if that is good enough to move forward with:

<img width="804" alt="screen shot 2016-10-17 at 9 06 30 pm" src="https://cloud.githubusercontent.com/assets/1891418/19461853/bbc9fa96-94ad-11e6-89cc-6e08ecffc778.png">

**Comment by jdebacker** [comment]
Like it!

**Comment by talumbau** [comment]
@jdebacker this is released and live on www.ospc.org/ccc

**Comment by jdebacker** [comment]
@talumbau Hover over works very nice.  However, the labels are popping up in correctly.

I see: 
- Bonus tooltip showing up over "ADS"
- ADS tooltip showing up over "Economic"
- Economic tooltip showing up over "Bonus"

**Comment by jdebacker** [comment]
@talumbau I think [this PR](https://github.com/OpenSourcePolicyCenter/webapp-public/pull/373) fixes this.

**Comment by talumbau** [comment]
resolved via #373
