### ISSUE TITLE
CCC  UI: Typo in the interest deductibility haircut description

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#324]
I misspelled "fraction".

**Comment by MattHJensen** [comment]
@jdebacker, should it actually be "fraction of interest not deductible", since it is a haircut? 
![image](https://cloud.githubusercontent.com/assets/8301092/18318295/308ad6a4-74ef-11e6-8244-62ae57f67087.png)

**Comment by jdebacker** [comment]
@MattHJensen you are right.  Fixing in [PR #81 in B-Tax repo](https://github.com/open-source-economics/B-Tax/pull/81).

**Comment by talumbau** [comment]
closed via https://github.com/open-source-economics/B-Tax/pull/81
