### ISSUE TITLE
CCC table output selector broken

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#328]
When I set all depreciation schedules to ADS, I get output that looks like this:

![image](https://cloud.githubusercontent.com/assets/8301092/18317762/064611f8-74ed-11e6-935d-7874a884b886.png)

Then I select "Baseline", and nothing happens:

![image](https://cloud.githubusercontent.com/assets/8301092/18317771/1310eb9c-74ed-11e6-8f52-b11b4412376d.png)

Then I go back to "Change from reform" (the original default", and everything is zeroed out, not matching the first picture. 

![image](https://cloud.githubusercontent.com/assets/8301092/18317795/2af84764-74ed-11e6-83fe-9cbc338d5d72.png)

It seems like neither the originally displayed nor final "change from reform" numbers are correct. 

https://ospc-taxes7.herokuapp.com/ccc/9/

**Comment by PeterDSteinberg** [comment]
Fixed in B-Tax (see PR 79 listed above).  Closing this issue.

**Comment by MattHJensen** [comment]
@PeterDSteinberg, I dont think this one is fixed. For instance:

![image](https://cloud.githubusercontent.com/assets/8301092/18393119/3e0f6b16-7682-11e6-9a02-75052fa2319a.png)


Then

![image](https://cloud.githubusercontent.com/assets/8301092/18393190/78605aaa-7682-11e6-96e7-cc400e798756.png)

Then

![image](https://cloud.githubusercontent.com/assets/8301092/18393201/823e4668-7682-11e6-8287-58bb6de251f3.png)

Then

![image](https://cloud.githubusercontent.com/assets/8301092/18393206/8a36e028-7682-11e6-9374-42cf2f83fd19.png)

**Comment by PeterDSteinberg** [comment]
@MattHJensen It 's not clear to me what is wrong in your screenshots.  The previous error had the entire "change from reform" table as all zeros.  Your recent screenshot shows nonzeros there except some columns are all zero.

**Comment by MattHJensen** [comment]
@PeterDSteinberg, look at the Corporate column. When the page first loads, it is actually showing the reform values instead of the change values. Only once I select something else and then reselect change do I see the proper deltas.

**Comment by PeterDSteinberg** [comment]
@brendancol do you have any input on @MattHJensen 's finding.  Note that the first screenshots of this may encapsulate 2 separate bugs 1) Matt's just mentioned one, 2) the [fixed bug in B-Tax PR #79](https://github.com/open-source-economics/B-Tax/pull/79) related to the gds/ads switches.

**Comment by PeterDSteinberg** [comment]
@brendancol I have confirmed that the UI is getting the correct tables.  This appears to be a js redraw/refresh issue.

**Comment by talumbau** [comment]
resolved via #319
