### ISSUE TITLE
CCC waiting and output pages should use CCC logos instead of TB logos.

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#329]
The logos displayed in the top bar for the CCC's "calculating" page and output page should be for CCC, not TaxBrain.

**Comment by PeterDSteinberg** [comment]
Fixed in #319

**Comment by PeterDSteinberg** [comment]
Confirmed this is fixed in https://ospc-taxes7.herokuapp.com/ccc/28/ . Closing
