### ISSUE TITLE
CCC fill out flatblocks' contents

### ISSUE THREAD

**Issue by PeterDSteinberg** [OpenSourcePolicyCenter/webapp-public#331]
Here are the flatblocks which need to be filled out for the /ccc and /apps pages that are new:

```
ccc_depreciation_blurb
ccc_macro_econ_blurb
ccc_other_blurb
ccc_payroll_blurb
ccc_footer
ccc_subheader
ccc_what_is_taxbrain_dropdown
ccc_above_get_started_blurb
ccc_get_started_blurb
ccc_results_header
taxbrain_ccc_dynamic_subheader
taxbrain_what_is_taxbrain_dropdown
ccc_what_is_ccc_dropdown
ccc_vs_taxbrain_blurb
taxbrain_entry_blurb
cost_of_capital_entry_blurb
```

**Comment by MattHJensen** [comment]
@jdebacker, I just added the flatblocks to the admin with dummy text that shows the name for the flatblock.  

I added the subheader and footer, but I think most of these you may want to fill out as they are describing the model and tool. Let me know if you'd like to assign any to me.

**Comment by jdebacker** [comment]
Now updated in test app.  I was not sure what to put for:
1) taxbrain_ccc_dynamic_subheader
2) ccc_vs_taxbrain_blurb
3) taxbrain_entry_blurb
4) cost_of_capital_entry_blurb

Also, should "What is TaxBrain?" by the "Start Exploring" be replaced by "What is Cost of Capital Calculator?"

cc @MattHJensen  @PeterDSteinberg @talumbau

**Comment by talumbau** [comment]
all Flatblocks content added. Thanks @MattHJensen @jdebacker and @PeterDSteinberg
