### ISSUE TITLE
CCC "What is the Cost of Capital Calculator"

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#332]
Currently the CCC header contains a "What is TaxBrain?" dropdown. It should contain a "What is the Cost of Capital Calculator" dropdown.

**Comment by PeterDSteinberg** [comment]
Fixed in #319

**Comment by PeterDSteinberg** [comment]
Confirmed fixed on https://ospc-taxes7.herokuapp.com/ccc/28/ . Closing.
