### ISSUE TITLE
CCC: N/As for METTR of debt-financed investments

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#337]
![image](https://cloud.githubusercontent.com/assets/8301092/18451608/aa554a04-7905-11e6-999e-aa36e3fef57b.png)

@jdebacker, are the N/As intended?

**Comment by jdebacker** [comment]
@MattHJensen - they are not.  It appears to be a UI issue.  See [here](https://github.com/open-source-economics/B-Tax/issues/77).

**Comment by MattHJensen** [comment]
Thanks @jdebacker. Removing question label and adding mustfix label.

**Comment by jdebacker** [comment]
fixed via #345

**Comment by talumbau** [comment]
closed via #345
