### ISSUE TITLE
Parameters Modify Rules

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/webapp-public#340]
Per discussion in issue [#927](https://github.com/open-source-economics/Tax-Calculator/issues/927), we want to apply certain rules when users are modifying a couple pairs of parameters, namely individual income (II) and passthrough (PT) rates and brackets parameters, and Capital Gain (CG) and Capital Gain alternative minimum (CG AMT) rates and brackets parameters. 

The rules I have in mind is that, when any of II's bracket or rate being modified, we would apply the same change to corresponding PT's bracket or rate. Moreover, any modifications to CG's bracket or rate would result in the same change to corresponding AMT CG's bracket or rate. 

In this way, we are avoiding potential confusions and mistakes by users who are not familiar with topics like passthrough tax and alternative minimum tax without nerfing our TB functionality. 

cc @MattHJensen @talumbau

**Comment by MattHJensen** [comment]
A first and easy step would be to keep the existing user interface but just make it so that when the user  changes the personal income tax rates and brackets, both the _II and _PT parameters are affected. The user interface would not change at all.

**Comment by MattHJensen** [comment]
@talumbau, here's a detailed description based on our call today. 

**First**, the "AMT Long-term capital gains and qualified dividends" subsection should be removed. 

**Second**, the "Long-term Capital Gains and Qualified Dividends" subsection fields should modify both the TC params they currently modify _and_ the params from the corresponding fields in the old ""AMT Long-term capital gains and qualified dividends" section. The meta data should point to their current fields. 

**Third**, the "personal income tax" subsection fields should modify both the TC params they currently modify _and_ the corresponding `_PT` fields. The meta data should point to their current fields. 

Note that the meta data solution is a little tricky. For example, the _II_rt and _II_brk fields metadata in TC should probably note that personal income tax has been split into two separate buckets and requires modification of both _PT params and _II params. This will make sense to TC users, but it will be confusing to TB users who only see one set of parameters. If possible, the best option is probably to have custom, webapp-only, meta data for these TB fields that point at more than one TC parameter.

cc @martinholmer @GoFroggyRun

**Comment by talumbau** [comment]
closed via #342

**Comment by hdoupe** [comment]
I think that #340 works against our new approach of moving as much parameter processing as possible to the underlying model. This issue was created in response to users getting strange results due to interactions between the capital gains and AMT parameters. This seems like an issue that should be resolved by Tax-Calculator. Does PolicyBrain still need to manipulate the parameters in this way?

cc @martinholmer @GoFroggyRun @MattHJensen
