### ISSUE TITLE
Drastically different static and PE estimates for rate reductions

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#341]
top rate from 39.6 to 35.

Static
![image](https://cloud.githubusercontent.com/assets/8301092/18686100/b2f2065e-7f48-11e6-9e2b-3eda4d2a844a.png)
http://www.ospc.org/taxbrain/5785/

PE, substitution elasticity 0.55: 
![image](https://cloud.githubusercontent.com/assets/8301092/18686079/a27afb28-7f48-11e6-93c9-235f9603044d.png)
http://www.ospc.org/dynamic/behavior_results/277/

Attempting to replicate on TC now.

**Comment by talumbau** [comment]
@MattHJensen has this been confirmed as a bug in the web app? I can verify that the reform dictionary for #5785 is 

```
{2016: {'_II_rt7': [0.35]} }
```

**Comment by MattHJensen** [comment]
Thanks T.J. This is not a bug on web app.
