### ISSUE TITLE
good choice for a file upload widget?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#350]
We need a file upload widget to completely fulfill #312. Right now, the WIP PR has a text area where one can paste in the desired reform. so the downstream processing is basically done, we just need a reasonable widget in the UI. What is a good javascript library choice here? @zrisher @kevincolten @brendancol Any pointers would be helpful. Thanks!

cc @MattHJensen

**Comment by kevincolten** [comment]
http://www.dropzonejs.com/ is a really popular library

**Comment by talumbau** [comment]
Thanks for this info! We are going to go with just a simple `input=file` element for right now. Closing
