### ISSUE TITLE
CCC Output Tables Info

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#351]
It's be nice to have some more info about what the output from the CCC means.  e.g. having in the info buttons as on the user input page to describe terms like METR, METTR, and depreciations (the NPV of the tax depreciation deductions).

**Comment by MattHJensen** [comment]
I think this is a combination of a B-Tax issue and a javascript issue so assigning @jdebacker and @brendancol. I mention B-Tax under the assumption that we want that documentation to be in B-Tax. Alternatively, it could just involve webapp flatblocks.

**Comment by brendancol** [comment]
@Jason, can you provide content for doing info tooltips?

**Comment by jdebacker** [comment]
@brendancol You can find tooltips updated in the new `btax_results_*.json` files.  However, these are specific to the form of financing and entity type.  Let me give some general text here (hope that's ok, but not sure if this should go in those json files or not):

METTR: "Marginal effective total tax rate on new investments.  The METTR includes the impact of all levels of taxation (both on business entities and savers) on the incentives to invest."

METR: "Marginal effective tax rate on new investments.  The METR includes the impact of the first level of taxation on the incentives to invest."

Cost of Capital: "The cost of capital is calculated as the net-of-depreciation, before-tax rate of return."

Depreciation: "Net present value of depreciation deductions."

**Comment by brendancol** [comment]
@jdebacker these tooltips should live in `btax/constants.py` which I've add in PR coming soon

**Comment by talumbau** [comment]
resolved via #377
