### ISSUE TITLE
CCC Output Page - Edit Parameters Button

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#352]
It could be helpful for the CCC output page to have an "Edit Parameters" button as the TaxBrain output page does.  Such a link is often very helpful to be able to go back and see what the exact parameter settings were for that particular run.

**Comment by jdebacker** [comment]
I'm adding "next release" label because I can't see any way to view the parameters of a given run when I'm only given a link to the output page.

cc @talumbau @MattHJensen

**Comment by MattHJensen** [comment]
+1 Necessary feature for debugging and sharing results.

**Comment by talumbau** [comment]
Update here: I was about ready to push this but I discovered that user choices for the radio buttons in each row of the Depreciation section are not preserved. In other words, when you go to the edit page, any numbers filled in to fields are there, but any of the GDS, ADS, or Economic buttons the user clicked are not filled in. After I get that working, I can push this feature.
