### ISSUE TITLE
remove JSON text field input page

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#355]
the `/json` page has been removed in favor of `/file`. See #312, #353 for details.

**Comment by brittainhard** [comment]
@talumbau @MattHJensen do we want to remove the endpoints at both `/json` and `/file`?

**Comment by martinholmer** [comment]
@brittainhard asked:
> do we want to remove the endpoints at both /json and /file?

No.  Remove only the /json endpoint.

@talumbau @MattHJensen
