### ISSUE TITLE
Link for main TaxBrain page to the reform-file-upload page?

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#356]
Is there a link from the main TaxBrain page to the reform-file-upload page?  I didn't see one, but could have been in too much of a hurry to notice it.  If there is no link, is there a plan to add one?  If not, how would people know anything about this capability?

**Comment by talumbau** [comment]
There is not such a link, but we can add one. Sometimes that is a good way to release a new feature, so that beta-testers can try out new features that others won't stumble upon until we are ready for a more general audience. But, now is as good a time as any to create such a link. @MattHJensen do you have thoughts on how you would like to link to the new file-upload page?

**Comment by martinholmer** [comment]
@talumbau said:
> There is not such a link, but we can add one. Sometimes that is a good way to release a new feature, so that beta-testers can try out new features that others won't stumble upon until we are ready for a more general audience. But, now is as good a time as any to create such a link. @MattHJensen do you have thoughts on how you would like to link to the new file-upload page?

I think it is fine to wait for a while to add the link.  I hope to add some tests of the reform-file-upload capability, so that can be part of our beta testing.

**Comment by martinholmer** [comment]
So what is the current thinking on TaxBrain issue #356?  There has been ten days of testing.  Do we need more time for testing, or are we waiting for more reform file examples at [this webpage](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/REFORMS.md)?

**Comment by MattHJensen** [comment]
> Do we need more time for testing, or are we waiting for more reform file examples at this webpage?

@martinholmer, I think more reform files will certainly be helpful, but we can add the link from the TaxBrain page now anyways. Do you have a recommendation for where it would fit?

**Comment by martinholmer** [comment]
@MattHJensen said:
> I think more reform files will certainly be helpful, but we can add the link from the TaxBrain page now anyways. Do you have a recommendation for where it would fit?

I don't really know the best place for the link on the main TaxBrain page.  So far, I haven't used TaxBrain that much, so I'm a novice user.  Maybe you could add to Step 1 of *What is TaxBrain?* a second sentence that mentions the reform-file way of specifying parameters and provides a link to that page.  Maybe there's a better approach.

@MattHJensen @feenberg @talumbau @Amy-Xu @GoFroggyRun

**Comment by martinholmer** [comment]
Ten days ago @MattHJensen said:
> I think more reform files will certainly be helpful [several have been added and more will be added soon], but we can add the link from the TaxBrain page now anyways. Do you have a recommendation for where it would fit?

And @martinholmer replied:
> I don't really know the best place for the link on the main TaxBrain page. So far, I haven't used TaxBrain that much, so I'm a novice user. Maybe you could add to Step 1 of What is TaxBrain? a second sentence that mentions the reform-file way of specifying parameters and provides a link to that page. Maybe there's a better approach.

What's the current thinking on the link location and the timing of this enhancement?

@talumbau @brendancol

**Comment by feenberg** [comment]
On Tue, 1 Nov 2016, Martin Holmer wrote:

> 
> Ten days ago @MattHJensen said:
>
>       I think more reform files will certainly be helpful [several have been
>       added and more will be added soon], but we can add the link from the
>       TaxBrain page now anyways. Do you have a recommendation for where it would
>       fit?
>

The https://www.ospc.org/taxbrain/ doesn't have any menu bar. I would have 
thought there was plenty of material for such a bar, including 
documentation, links to the mailing list, the new graphical pages, etc. 
Some of the text on that page could be moved to "about" and other pages. 
That would move the first paramaters up above the fold, which I think 
would communicate clearly to potential users what we offered.

Once we have a menu bar, "proposals" would be a natural item, leading to a 
selection box.

dan

**Comment by MattHJensen** [comment]
@martinholmer, thanks for the reminder about this issue. 

> Maybe you could add to Step 1 of What is TaxBrain? a second sentence that mentions the reform-file way of specifying parameters and provides a link to that page. Maybe there's a better approach

I just followed this approach. 

@feenberg said: 

> The https://www.ospc.org/taxbrain/ doesn't have any menu bar. I would have
> thought there was plenty of material for such a bar, including
> documentation, links to the mailing list, the new graphical pages, etc.
> Some of the text on that page could be moved to "about" and other pages.
> That would move the first parameters up above the fold, which I think
> would communicate clearly to potential users what we offered.

I think adding a menu bar is a very good idea. There are several other TaxBrain UI changes we might want to consider as well. I just opened https://github.com/OpenSourcePolicyCenter/webapp-public/issues/398 to serve as a location for anyone to propose those ideas.

**Comment by MattHJensen** [comment]
@martinholmer, could you take a look at the TaxBrain input page and close this issue if you think it is resolved.

**Comment by martinholmer** [comment]
@MattHJensen asked:
> [Can] you take a look at the TaxBrain input page and close this issue [#356] if you think it is resolved.

I have several suggestions about how to improve things:

(1) On the main TaxBrain page it says "You can do so with the graphical user interface below or by uploading a policy reform file, here." where `here` is the HTML link.  How about this:
"uploading a policy reform file from this page." where `this page` is the HTML link.

(2) When I go to `this page` I find on the left-hand side below the Start Year box a "Getting Started" item and an "Input Form" item.  The "Input Form" link does nothing.  Why not remove it?

(3) Then when I specify an input file and click on Show Me the Results, nothing happens.  Unless my memory is shot, it did seem to work last week.

Can't really close this issue #356 when so many things need improvement.

**Comment by martinholmer** [comment]
@martinholmer said:
> (3) Then when I specify an input file and click on Show Me the Results, nothing happens. Unless my memory is shot, it did seem to work last week.

OK, I tried doing this again and it did work as expected.  
But I still think my two other suggestions wrt #356 are needed improvements.

@MattHJensen @talumbau

**Comment by martinholmer** [comment]
@martinholmer said six days ago:
> I have several suggestions about how to improve things:
>
> (1) On the main TaxBrain page it says "You can do so with the graphical user interface below or by uploading a policy reform file, here." where here is the HTML link. How about this:
"uploading a policy reform file from this page." where this page is the HTML link.
>
> (2) When I go to this page I find on the left-hand side below the Start Year box a "Getting Started" item and an "Input Form" item. The "Input Form" link does nothing. Why not remove it?

@talumbau,  Where do we stand on these improvements?  If these changes have been implemented, I can close this issue #356.

**Comment by MattHJensen** [comment]
@martinholmer, thanks for suggesting these improvements! I just resolved (1), opened a new issue (#409) for (2), and added the new issue to [milestone b2](https://github.com/OpenSourcePolicyCenter/webapp-public/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20milestone%3Ab2), a batch of issues that will be completed after [milestone b1](https://github.com/OpenSourcePolicyCenter/webapp-public/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20milestone%3Ab1). Closing this issue.
