### ISSUE TITLE
Suggestions for the taxbrain/file/ page

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#358]
@talumbau, I have compared aggregate 2020 revenues under current-law and a complex reform whose JSON-reform-file I uploaded to TaxBrain.  The aggregate revenue results are exactly the same on my local computer and on TaxBrain.  So, things seem to be working fine.  Thanks for adding this useful feature to TaxBrain.

But I do have a few suggestions to make the user experience better.

(1) on the file-upload page it says:
```
Get Started
You are looking at default parameters for 2016.

JSON Input Parameters

Tax Calculator Parameters

Select a file:
```
There are a number of improvement we can make here.  First, we aren't looking at any parameters.  And second, "JSON Input Parameters" might be better as something like "Reform file" with a link to the right labeled "Examples" or "More information" that goes to the taxcalc/reforms/REFORMS.md file I'm in the process of developing.  And third, I don't see what the "Tax Calculator Parameters" label adds once something like the above suggestions are implemented.  What are your thoughts on this?

(2) Then after TaxBrain does the calculations, the label above the uploaded file is this:
```
THE FOLLOWING PARAMETERS WERE UPLOADED FOR THIS SIMULATION:
```
Don't you think something like this would be better?
```
THE FOLLOWING REFORM FILE WAS UPLOADED FOR THIS SIMULATION:
```
Thoughts?

(3) When there is a syntax error in the uploaded file, it is difficult to locate the error, which is usually given in terms of line number and column number.  The line number is easy to see, but the column number is difficult because the error message is not being displayed in a fixed-width font.  Can this be changed?  I hope so, because otherwise the error message is not very helpful.

Again, the basic functionality we've been looking for seems to be there.  Thanks again for all your work on making this happen.  Just a few minor enhancements would make it much easier to use.

**Comment by talumbau** [comment]
fixed by #365
