### ISSUE TITLE
File-based TaxBrain reforms should properly link to dynamic simulations

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#359]
We have three dynamic simulation options:

 - partial equilibrium
 - OGUSA
 - macro elasticities

In order to properly link a File-based TaxBrain simulation to OGUSA, work must be done on the OGUSA package (to properly feed the reform file into the Tax-Calculator in the portion of OGUSA that estimates the tax functions needed for the rest of the simulation). For partial equilibrium and macro elasticities, we can add code on the backend that properly takes the file-based reform and feeds it to the `Policy.read_json_reform_file` function.

Therefore, when a user clicks the "link to dynamic simulation" button on the results page for a file-based TaxBrain reform run, the user should only see the partial equilibrium and macro elasticities options, until OGUSA supports running such reforms as well.

**Comment by talumbau** [comment]
resolved via #362 and #363

**Comment by MattHJensen** [comment]
Thanks @talumbau.
