### ISSUE TITLE
update CCC logo on dark background?

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#366]
![costofcapitalcalfinal 1](https://cloud.githubusercontent.com/assets/8301092/19439458/255bbd76-944c-11e6-870e-a2b0ed737dd1.png)

Would the third logo look better on dark backgrounds than the second?

**Comment by talumbau** [comment]
@MattHJensen here is the /ccc/ page at the top with the third logo:

<img width="350" alt="screen shot 2016-10-17 at 12 56 10 pm" src="https://cloud.githubusercontent.com/assets/1891418/19448876/298daa22-9469-11e6-9508-6eea820a39ad.png">

here it is with the first:

<img width="383" alt="screen shot 2016-10-17 at 12 54 20 pm" src="https://cloud.githubusercontent.com/assets/1891418/19448884/3374725a-9469-11e6-9916-da18ce4a3638.png">

I agree that using the third logo is the best. If this looks good to you I will include the change in my upcoming PR.

**Comment by MattHJensen** [comment]
> I agree that using the third logo is the best. If this looks good to you I will include the change in my upcoming PR.

Looks great!
