### ISSUE TITLE
Default TB output to difference table w payroll and individual income taxes

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#375]
This is the default TB output:

![image](https://cloud.githubusercontent.com/assets/8301092/19567026/53457662-96ba-11e6-9c1f-8e64befe7e2c.png)

Let's make it:

![image](https://cloud.githubusercontent.com/assets/8301092/19567037/5e780748-96ba-11e6-8815-8a4f20fe9af2.png)

**Comment by talumbau** [comment]
I took a look at `js/taxbrain-tablebuilder.js`, but could not grok the code enough to make a meaningful change here. Assigning to @brendancol

**Comment by brendancol** [comment]
I've changed defaults of table builder: the screenshot below is zoomed out so you can see the table title etc.

<img width="1180" alt="screen shot 2016-11-01 at 9 45 14 am" src="https://cloud.githubusercontent.com/assets/433221/19893699/0eb0ed9e-a018-11e6-942f-98377dac0061.png">

**Comment by MattHJensen** [comment]
Thanks @brendancol! The column selector looks like it may not be displaying unselected columns. 

![image](https://cloud.githubusercontent.com/assets/8301092/19895113/dffdae02-a025-11e6-9f1a-b8c58fcb75ed.png)
