### ISSUE TITLE
TB output diagnostic table defaults

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#376]
The current diagnostic table defaults are:

![image](https://cloud.githubusercontent.com/assets/8301092/19567194/df40db98-96ba-11e6-92b5-5d0db4c629dc.png)

Let's make them:

![image](https://cloud.githubusercontent.com/assets/8301092/19567168/d51c2fdc-96ba-11e6-8a81-147be945687e.png)

**Comment by talumbau** [comment]
I can't seem to find the place in the JS where the default check status of each column is set. Assigning to @brendancol

**Comment by MattHJensen** [comment]
John Sabelhaus' students also suggested this one via him. Matt should notify him when it is live.
