### ISSUE TITLE
Explore submitting multiple dropq years to one node

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#38]
Currently we submit one budget year per node in our pool of AWS worker nodes, and only give a node multiple budget years if a node is down or unresponsive for some reason. We should look at the performance of using half as many nodes with two budget years per node. This task would involve starting two celery workers on each AWS node and setting the "greedy fetch" settings of celery to 'off' or essentially 'just get one job at a time'. If the performance is good, we could turn off some nodes and reduce AWS costs.

**Comment by talumbau** [comment]
cc @PeterDSteinberg

**Comment by MattHJensen** [comment]
One note is that incorporating some behavioral effects (see behavior.py in taxcalc) will require several more calculator runs per budget year. It may make sense to get this incorporated before making performance-relevant decisions.

On Sep 10, 2015, at 7:43 PM, T.J. Alumbaugh <notifications@github.com<mailto:notifications@github.com>> wrote:


cc @PeterDSteinberg<https://github.com/PeterDSteinberg>

**Comment by talumbau** [comment]
this is resolved. We just round-robin all the work (no matter how many budget years) to how ever many nodes are available.
