### ISSUE TITLE
Enable 10-year liabilities table to display Current Law, Reform, and Change.

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#380]
Currently TB's 10-year liabilities table only displays the delta between baseline and reform. A user requested the capability to see the baseline and reform numbers as well, without having to pick them out of the diagnostic table for each year. 

Here is the current table: 
![image](https://cloud.githubusercontent.com/assets/8301092/19649150/b58ca3b6-99d2-11e6-8e85-862fc9dcc069.png)

Here's how we can meet the request:

- [x] Add a selector above the title: `Current Law`, `Reform`, `Change`.  

- [ ] Change the table name to "Total liabilities by calendar year, `descriptor`", where the `descriptor` is the name of the selection. 

- [x] The default should be `Change`. 
- [x] Add tooltip hooks for new buttons

Matt should notify John Sabelhaus when this is complete.

**Comment by talumbau** [comment]
@brendancol we would probably need to make the total liabilities table a new element that is similar to the "tablebuilder" assets. If I provide you the JSON to populate the additional versions of the table (we have the delta data, would just need baseline and reform), can you add the selector and make the table data switch based on the selected value? I'm thinking a drop down for the selector? Sound right? Adding @brendancol to assignees but keeping myself as I need to supply the data.

**Comment by MattHJensen** [comment]
> I'm thinking a drop down for the selector? Sound right? 

Another option would be three buttons next to each other. Like these, but w one more: 
![image](https://cloud.githubusercontent.com/assets/8301092/20008585/8b76fa6a-a277-11e6-8a92-e286fd47bea3.png) I defer to @brendancol, though.

**Comment by talumbau** [comment]
closed via #413
