### ISSUE TITLE
"Looks Ok" Buttons

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#381]
- [x] Replace `Looks OK` after Macroeconomic Variables section with "Show me results button"
     - I decided to remove this button instead which is consistent with the TaxBrain input page
- [x] Fix `Looks OK` button at the bottom of Other Section
- [x] Fix Taxbrain `Payroll Taxes` `Looks OK` button (currently jumps to adjustments

**Comment by talumbau** [comment]
closed via #403
