### ISSUE TITLE
Replace "What is TaxBrain?" with "What is Cost of Capital Calculator?"

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#384]
Replace "What is TaxBrain?" with "What is Cost of Capital Calculator?" at the top of the CCC landing page.  

This may be in the flat blocks, but I can't locate it.

**Comment by jdebacker** [comment]
@MattHJensen - do you agree this should be changed?

@talumbau - I'm happy to make this small fix, but need some direction as to where to make it.

**Comment by MattHJensen** [comment]
> @MattHJensen - do you agree this should be changed?

Yes

**Comment by talumbau** [comment]
I see the issue here for the input page and the results page. I'm handling this now.
