### ISSUE TITLE
Extraneous rows at the bottom of the CCC output tables

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#386]
The last row at the bottom of the "by industry" table:
![ind_table_ss](https://cloud.githubusercontent.com/assets/10715924/19741752/f65a5316-9b8f-11e6-98a9-c1a91f131b2b.png)

And the last row at the bottom of the "by asset" table:
![asset_table_ss](https://cloud.githubusercontent.com/assets/10715924/19741772/0bda7bc6-9b90-11e6-8f64-207b869c78bc.png)

appear unnecessary (the repeat the header at the top of the table) and should be removed.

**Comment by PeterDSteinberg** [comment]
Fixed by #392
