### ISSUE TITLE
Print values of all output variables for major groupings

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#388]
Currently, major groupings display values for corporate and non-corporate METRs only (and in a different format than in other rows of the table):

![grouping](https://cloud.githubusercontent.com/assets/10715924/19742028/3bd42d58-9b91-11e6-9620-65d36e7be444.png)

The output table ought to display values for all output variables for these groupings - and do so in the same format as the other rows in the table.

**Comment by MattHJensen** [comment]
+1 The whole row would be bold, right? 

Is there a reason not to have an average line at the bottom? (the way I envision the averaging, the number would be the same for both the assets table and the industry table.)

**Comment by jdebacker** [comment]
Yes, whole row is bold.

I envisioned the overall average to be the first line since this is what many are most interested in.  And yes, this overall number would be the same value for the "by industry" and "by asset" tables.

**Comment by PeterDSteinberg** [comment]
Fixed by #392

**Comment by jdebacker** [comment]
@PeterDSteinberg Did we have the overall average in the table?  I thought so, but not seeing it on CCC now.

**Comment by jdebacker** [comment]
Closed w PR #423
