### ISSUE TITLE
Numbers if CCC output rounded to nearest whole number

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#389]
When loading a CCC results page, the first time the results page loads, the numbers are rounded to the nearest integer (with the negative sign persisting if necessary):

<img width="1133" alt="screen shot 2016-10-26 at 8 49 05 pm" src="https://cloud.githubusercontent.com/assets/1891418/19751323/f3628240-9bbd-11e6-8d3e-e3089e4205bc.png">

Then if you hit refresh on the page, the numbers display as expected:

<img width="1153" alt="screen shot 2016-10-26 at 8 52 12 pm" src="https://cloud.githubusercontent.com/assets/1891418/19751345/1ac65564-9bbe-11e6-9144-93e82a736c75.png">

@brendancol any ideas?

**Comment by talumbau** [comment]
this might be a JS caching issue. Looking for someone to reproduce or I'll close.

**Comment by jdebacker** [comment]
@talumbau I just did a couple runs and never had the rounding issue.  Even when values were zero.

**Comment by brendancol** [comment]
@talumbau @jdebacker I also didn't experience any trouble here, but I'll keep my eye out in case its something more subtle.  for now I'm going to close.
