### ISSUE TITLE
Add Build Table Tooltips

### ISSUE THREAD

**Issue by brendancol** [OpenSourcePolicyCenter/webapp-public#394]
<img width="320" alt="screen shot 2016-10-31 at 1 36 30 pm" src="https://cloud.githubusercontent.com/assets/433221/19866739/4e600f46-9f6f-11e6-89fd-d824dea29386.png">

**Comment by brendancol** [comment]
@MattHJensen I noticed a bunch of tooltips missing on the Build Table page

**Comment by brittainhard** [comment]
@MattHJensen @brendancol any ideas on what these tooltips should say?

**Comment by MattHJensen** [comment]
@brittainhard, I'll take care of this one.

**Comment by MattHJensen** [comment]
Diagnostic Table tooltip: Key variables in the computation of tax liabilities. 

Difference Table tooltip: Key variables that highlight the differences between two tax plans.

Current Law tooltip: Current law as defined by default parameters. 

Reform tooltip: The reform proposal as defined by user-provided parameters. 

Payroll tooltip: Include employee and employer payroll taxes in output. 

Income tooltip: Include individual income taxes in output.

Expanded income tooltip: The tab variable includes adjusted gross income, non-taxable interest income, taxable investment income excluded from AGI, non-taxable social security benefits, the employer’s share of FICA, and above the line adjustments to AGI on form 1040. 

Income bins tooltip: Tax units are binned according to the income group to which they belong. 

Income Deciles: Tax units are binned according to the income decile to which they belong.
