### ISSUE TITLE
Need to eliminate incomplete and obsolete Lee-Rubio parameter

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#400]
The current version of TaxBrain includes this:

![image](https://cloud.githubusercontent.com/assets/12170745/19974494/1458d88a-a1bf-11e6-9dcc-d480a91db726.png)

The Lee-Rubio proposal would appear to be obsolete, and more importantly, the other policy parameters required to specify this old Lee-Rubio reform are not available on TaxBrain.  It does not make any sense to have this Lee-Rubio parameter on TaxBrain.  Can it be removed?

@MattHJensen @talumbau @feenberg @brendancol

**Comment by MattHJensen** [comment]
Closed by #405
