### ISSUE TITLE
Add a feedback form to TaxBrain

### ISSUE THREAD

**Issue by andersonfrailey** [OpenSourcePolicyCenter/webapp-public#406]
Currently there are two ways provide feedback on TaxBrain: a user must either open a GitHub issue or find the link to the mailing list in the "What is TaxBrain" section of the TaxBrain app. I would like to propose adding a more traditional form to solicit feedback on the site. I put together [this](https://docs.google.com/forms/d/e/1FAIpQLSfvKEsQZNe9_16FhKNZcEyv3C8qXZhBfrqLxSd4VR97w92moQ/viewform) Google form as an example of what it could look like.

I envision a link to the form being on the OSPC home page in the "Become a Contributor" section, or at the bottom of the page where contact and feedback links are often found. 

The main goal for this is to make providing feedback easier for users. I worry that under the current set up those who like using TaxBrain but don't want to create a GitHub account and make their thoughts public or sign up for an email list will be less likely to give feedback. I believe a simple form would give them a more familiar way to join the discussion.

After feedback is submitted through the form, the it could be emailed to everyone on the mailing list, as I believe is currently the case, or it could be filtered through an intern or research assistant on the OSPC team who opens an issue on GitHub for the responses.

**Comment by martinholmer** [comment]
The idea in issue #406 sounds like a good idea to me.  Thanks, @andersonfrailey

**Comment by MattHJensen** [comment]
@andersonfrailey, thanks a lot for the contribution. I just added a link to the TaxBrain input page. 

Could you:
I just added a live link to https://docs.google.com/forms/d/e/1FAIpQLSfvKEsQZNe9_16FhKNZcEyv3C8qXZhBfrqLxSd4VR97w92moQ/viewform from TaxBrain. 

Could you:

- Check to make sure that the form is receiving data properly. 
- Move the "What would you like to see improved in TaxBrain?" to the top of the form and rename it to “What is your TaxBrain feedback?”

**Comment by andersonfrailey** [comment]
@MattHJensen, I've updated the form and it is receiving data properly.

**Comment by MattHJensen** [comment]
This is resolved. Thanks @andersonfrailey
