### ISSUE TITLE
Fiscal totals summary page only displays 8 budget years

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#419]
The recently deployed updated fiscal totals page displays the delta between the policy and baseline and has tabs for summaries for baseline and reform separately:

<img width="1261" alt="screen shot 2016-11-21 at 8 40 36 pm" src="https://cloud.githubusercontent.com/assets/1891418/20509005/1b4ab058-b02b-11e6-9059-fcd9bf17165c.png">

However, when running with 10 budget years, the summary data is only shown for 8 years. For the other two years, the user has to scroll down and look at the full table of information.

I can confirm that we are passing all 10 years of summary data to the javascript code. @brendancol can you look at this ASAP? I suspect that it's a formatting issue that we didn't see before.

Rolling back to a previous version of the site would not restore previous functionality because the worker nodes are producing new data (the baseline and reform totals), so the worker nodes would have to be rolled back as well. The least amount of effort would seem to be to fix the javascript side of things and just deploy that fix.

**Comment by MattHJensen** [comment]
@brendancol, do you have time to take a look at this tomorrow (Wednesday)? I'm giving a major presentation on Friday and a 10-year budget window is expected functionality.

**Comment by brendancol** [comment]
@MattHJensen Hey, yes I will look at this tomorrow and figure out whats going on

**Comment by talumbau** [comment]
closed via #424
