### ISSUE TITLE
Reset Parameter button should entirely reset input page.

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#420]
On Chrome, after the "Reset Parameters" button is activated, the parameters that were used and then reset are left highlighted and displaying the default value subscript.

![image](https://cloud.githubusercontent.com/assets/8301092/20527969/5a3bff02-b098-11e6-8431-63c6d684e93d.png)

I think the button should return the page to its original form. One way to do that would have be to simply have it link to www.ospc.org/taxbrain. 

(using the browser's refresh capability won't work, as our original motivation for adding the reset parameter button is that in firefox, the refresh button does not clear out existing parameters (see #379). Reloading www.ospc.org/taxbrain works fine.)

**Comment by talumbau** [comment]
So, the difference is that the boxes are still highlighted in blue, correct? An unmodified box still shows the default value, but it does not have the blue highlighting. Just making sure I understand.

**Comment by MattHJensen** [comment]
An unmodified box still shows the default value, does not have the blue highlighting, _and_ does not display the default value under the box. So the difference is that the boxes are still highlighted in blue and the default value is displayed _under_ the box.
