### ISSUE TITLE
macro elasticity run not completing

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#426]
http://www.ospc.org/dynamic/macro_results/381/

![image](https://cloud.githubusercontent.com/assets/8301092/20801242/3890cf5c-b7b6-11e6-9084-f5766a8e3fe9.png)

@brendancol @PeterDSteinberg

**Comment by brendancol** [comment]
just polls forever http://www.ospc.org/dynamic/macro_results/381/

**Comment by talumbau** [comment]
There are two bugs here:

 - the worker node was incorrectly calling code in dropq
 - the webapp was not properly reading the FAIL status of the jobs, which results in endless polling

I have fixed both. PRs coming up.
