### ISSUE TITLE
new features in json file

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#431]
@martinholmer recently augmented the JSON reform file to include Growth, Behavior, and Consumption parameters in https://github.com/open-source-economics/Tax-Calculator/pull/1083

These changes break backwards compatibility for TB and TC, and some updates to TB are required before we can deploy any version of TC greater than 0.7.2 to TB. 

I described the core issue in https://github.com/open-source-economics/Tax-Calculator/pull/1083: 

> it won't be trivial to adopt on TaxBrain because of how TaxBrain guides users to static modeling first and then to dynamic modeling. Right now, partial eq and other dynamic runs come after the static results; with the new file upload feature, users will be able to jump directly to a partial equilibrium run without first generating static results. I don't think it will be hard to deal with the user interface and backend changes that will need to result from that, but it won't be trivial either.

To be more specific, the problem is that the new JSON format allows users to upload a file that will produce a partial equilibrium result rather than to a static result. The resulting page shouldn't have the same functionality as a static results page, and it also probably can't have the same functionality as the partial equilibrium result page.  

The reason that the page shouldn't have the same functionality as the static results page is that it won't make sense for the user to continue on to dynamic modeling after having specified behavioral parameters. 

The reason that the page probably can't have the same functionality as the partial equilibrium result page is that our existing PE page allows the user to return to the static results, but no static results were generated with the json file. 

I see two options for when the user includes nonzero behavioral parameters: 

1) Have the page take the user to what looks like the static results page, but when the user clicks "Link to Dynamic Simulations" a pop up will say "Your simulation is already a partial equilibrium dynamic simulation. Please resubmit without behavioral parameters if you would like to link to other dynamic modeling options." 

2) Have the page look like the partial equilibrium results page and either:
a) remove the "The microsimulation upon which this dynamic simulation was based can be found here"  or,
b) (fancier version) leave the "The microsimulation upon which this dynamic simulation was based can be found here" and when the user clicks "here", run that static calculation and generate the static results on the fly. 

@talumbau, it would be helpful to know which of these is easier to implement, and if there will be any other difficulties on the back end with incorporating the new json features from https://github.com/open-source-economics/Tax-Calculator/pull/1083

**Comment by martinholmer** [comment]
@MattHJensen said:
> I see two options for when the user [uploads a JSON reform file that] includes nonzero behavioral parameters:
>
> (1) Have the page take the user to what looks like the static results page, but when the user clicks "Link to Dynamic Simulations" a pop up will say "Your simulation is already a partial equilibrium dynamic simulation. Please resubmit without behavioral parameters if you would like to link to other dynamic modeling options."

I don't know anything about the easy or difficulty of different kinds of changes to TaxBrain, but it seems to me that this first option is a very sensible approach.  There is no need for different output options, just a need to block the current path to the "dynamic" analysis options.

That's my two cents on this.

@MattHJensen @talumbau @feenberg @brendancol @Amy-Xu @GoFroggyRun @andersonfrailey

**Comment by MattHJensen** [comment]
Thanks @martinholmer! That makes sense to me too.

**Comment by MattHJensen** [comment]
Added this to milestone b1 as it is blocking any new TC releases.

**Comment by talumbau** [comment]
I actually think 1 is probably the easiest, due to the fact that it maintains the "file based reform generates static results page" workflow, which is desirable. I can take this on.

**Comment by MattHJensen** [comment]
Sounds good. Thanks @talumbau
