### ISSUE TITLE
How should Consumption parameters be handled in TaxBrain runs?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#433]
When #431 is implemented, a user will be able to upload a file-based reform that includes: policy parameters, growth parameters, behavior parameters, and consumption parameters. When the only parameters are policy parameters, the comparison carried out by TaxBrain is trivial (delta of policy with no reform and policy with reform). With the other parameters, the TaxBrain comparison is defined as follows:

With growth parameters:

(policy with no reform and with growth parameters) - (policy with reform and with growth parameters)

With behavior parameters and growth parameters:

(policy with no reform and with growth parameters) - (policy with reform and with growth parameters and with behavior parameters)

So with consumption parameters is the proper handling:

(policy with no reform and with growth parameters) - (policy with reform and with growth parameters and with behavior parameters and with consumption parameters)

OR

(policy with no reform and with growth parameters and with consumption parameters) - (policy with reform and with growth parameters and with behavior parameters and with consumption parameters)

cc @MattHJensen

**Comment by MattHJensen** [comment]
Should be: 

(policy with no reform and with growth parameters and with consumption parameters) - (policy with reform and with growth parameters and with behavior parameters and with consumption parameters)

**Comment by talumbau** [comment]
got it, thanks!
