### ISSUE TITLE
CCC inconsistent sort feature

### ISSUE THREAD

**Issue by salimfurth** [OpenSourcePolicyCenter/webapp-public#434]
I noticed a minor inconsistency in the CCC output page. When "Asset" view is selected, each of the column headers acts as a clickable sort function. But under "Industries" the feature doesn't exist.

Personally, I'm ambivalent about whether it should exist. Sorting breaks up the two-level hierarchy that the existing reporting relies on. Thus the categories "Communications" (under Equipment) and "Communication" (under Structures), for example, could be easily confused. 

I'm using Chrome Version 54.0.2840.99 m.

**Comment by jdebacker** [comment]
@salimfurth , thanks for pointing this out.  Given that the tables now produce averages over groups and of assets/industries and highlight these, it's easier to find one's way around the tables.  The sort feature therefore feels unnecessary.  I propose we remove it.

**Comment by MattHJensen** [comment]
@jdebacker, I just moved this to b2 so we can clear out b1 which contains a TB bug.

**Comment by brittainhard** [comment]
@jdebacker @MattHJensen i'm going to go ahead and put up a PR for this if you are set on removing it.

**Comment by jdebacker** [comment]
@brittainhard - yes, let's remove this feature. Thanks.

**Comment by brittainhard** [comment]
Fixed in #467
