### ISSUE TITLE
validation testing against Tax-Calculator in TB release

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#447]
https://github.com/open-source-economics/Tax-Calculator/issues/1119 indicates that the TaxBrain release process could benefit from (more) validation testing against Tax-Calculator. 

The baseline results from TaxBrain should be extremely close to those in the [pufcsv_agg_expect.txt](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/tests/pufcsv_agg_expect.txt) that the Tax-Calculator team generates from the `requires_pufcsv` tests.  

One option would be to compare against those results with a tolerance. Another would be to add new `requires_pufcsv` tests that generate a dropq baseline. 

@talumbau, what do you think?

**Comment by MattHJensen** [comment]
@hdoupe, do you think this issue should remain open?

**Comment by hdoupe** [comment]
@MattHJensen, I am working on similar tests in PR #627.  This issue could be closed in favor of #615 and #602.

**Comment by MattHJensen** [comment]
Thanks @hdoupe. Closing.
