### ISSUE TITLE
The "print button" on the results page should either work or be removed.

### ISSUE THREAD

**Issue by zrisher** [OpenSourcePolicyCenter/webapp-public#45]

**Comment by talumbau** [comment]
This is probably what should happen for "Print" as well as "Save to PDF":

http://stackoverflow.com/questions/1377446/render-html-to-pdf-in-django-site

The LOE on this is likely not small.

**Comment by johneo** [comment]
@talumbau what about bringing up the browser's native print dialog when the user clicks "Print"?

**Comment by johneo** [comment]
It appears to be simply `window.print();`

**Comment by talumbau** [comment]
resolved by the revamp of the results page some time ago.
