### ISSUE TITLE
Are we missing a model parameter?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#451]
For some other work I'm doing, I noticed that the TaxSaveInputs model does not have the `_ID_BenefitSurtax_em` parameter, which was added to `current_law_policy.json` in the refactor that @MattHJensen did last month. Do we need to add this? 

cc @brittainhard

**Comment by MattHJensen** [comment]
We do. Good catch!

**Comment by talumbau** [comment]
@brittainhard can you handle this?

**Comment by brittainhard** [comment]
@talumbau looks straightforward. I'll push a fix a little later in the day.

**Comment by talumbau** [comment]
Resolved via #453

**Comment by rrenfrow86** [comment]
@MattHJensen - recommend closing.
