### ISSUE TITLE
Where is the TaxBrain release number displayed?

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#454]
I used to be able to find out if TaxBrain was using, say, release 0.7.1, but now I can't find that info.
Has the release number been dropped or moved?

@MattHJensen @PeterDSteinberg @brittainhard @talumbau

**Comment by MattHJensen** [comment]
@martinholmer, it is in the "what is TaxBrain" dropdown at the top of the page.

![image](https://cloud.githubusercontent.com/assets/8301092/22410180/ade6c39e-e662-11e6-9ac3-85924e8c0b9b.png)

**Comment by martinholmer** [comment]
@MattHJensen said:
> it is in the "what is TaxBrain" dropdown at the top of the page.

Thanks.
