### ISSUE TITLE
Misleading "(percentage point)" labels on two "Baseline Growth Assumptions" input boxes

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#455]
The documentation info (via the i pop-up box) is inconsistent with the "(percentage point)" labels.
Best strategy would seem to be dropping the "(percentage points)" text in both labels and let the pop-up documentation explain to the TaxBrain user what units to enter.

@MattHJensen @PeterDSteinberg @brittainhard @talumbau

**Comment by MattHJensen** [comment]
@martinholmer, could you describe the inconsistency? 

The first parameter allows the user to supply a percentage point deviation from the existing CBO growth rate. i.e., the user adjusts a percent growth rate by a percentage point factor. 

The second parameter allows the user to supply a growth rate that replaces the CBO growth rate. i.e., the user replaces a percent growth rate with a percent growth rate. 

As far as I can tell, we are using the "percentage point" and "percent" terms properly.

**Comment by martinholmer** [comment]
@MattHJensen said:
> The first parameter allows the user to supply a percentage point deviation from the existing CBO growth rate. i.e., the user adjusts a percent growth rate by a percentage point factor.

No, that is not what is happening in the source code.  The real GDP growth rates in Tax-Calculator are expressed in decimal, not percentage, terms.  So, while CBO says real GDP grows at 2.1 percent in a given year, Tax-Calculator says real GDP grows at 0.021 in that year.  Any user putting in 1.1 as the deviation --- thinking it would increase 2.1 to 3.2 percent --- would be shocked to see massive increases in the blown-up variables (because each blowup factor would have 1.1 added to its value, which is typically just a little bit larger than one).

[Tax-Calculator pull request 1160](https://github.com/open-source-economics/Tax-Calculator/pull/1160) attempts to clarify things by revising the long_name and description of both of the Growth parameters.

**Comment by martinholmer** [comment]
[Tax-Calculator pull request 1160](https://github.com/open-source-economics/Tax-Calculator/pull/1160), which attempts to clarify things by revising the long_name and description of both of the Growth parameters, has been merged into the Tax-Calculator master branch.

**Comment by MattHJensen** [comment]
Thanks @martinholmer -- I understand the inconsistency now.

**Comment by martinholmer** [comment]
@MattHJensen,  What's the status of issue #455?

**Comment by martinholmer** [comment]
Beginning with release 0.7.7, the TaxBrain GUI does not contain growth-related parameters, so issue #455 has been resolved and is now being closed.
