### ISSUE TITLE
Edit parameters page only shows font color change

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#459]
Here is what an input field looks like to begin with. 

![image](https://cloud.githubusercontent.com/assets/8301092/22397610/623a61e6-e543-11e6-8ae3-d795feeccec8.png)

When I edit a parameter on the TaxBrain input page, the color of the font darkens, the input field turns green, and the Default value appears under the input field. This is great. 

![image](https://cloud.githubusercontent.com/assets/8301092/22397605/4f06ee82-e543-11e6-9b30-ba4e16160d6a.png)

However, when I run TaxBrain and then click edit parameters, only the font is darker:

![image](https://cloud.githubusercontent.com/assets/8301092/22397603/1c34c8d0-e543-11e6-816e-f21ddb48de68.png)

It would be better if the edit parameters page also included the input field color changes and the default values appearing under the input page (i.e, it should look exactly like the second image from this post rather than the third). 

This issue applies to both TaxBrain and CCC.

**Comment by MattHJensen** [comment]
This problem has returned. 

![image](https://cloud.githubusercontent.com/assets/8301092/23768251/68b60f2e-04d9-11e7-8489-33d0a9ee8e40.png)

@brittainhard

**Comment by brittainhard** [comment]
Looks like the `taxbrain.js` file was reverted somehow. Quick fix.

**Comment by brittainhard** [comment]
@MattHJensen possible fix is up on the test app.

**Comment by MattHJensen** [comment]
@brittainhard, looks good on the test app.
