### ISSUE TITLE
Experiments with webapp

### ISSUE THREAD

**Issue by Amy-Xu** [OpenSourcePolicyCenter/webapp-public#46]
To identify potential bizarre behaviors in webapp, I'm planning to do some experiments for each parameter in TaxBrain following these categories of value range:

- theoretical reasonable range
- extremely large values
- negative values
- other corner cases

I'll list the results in this issue and keep updating as I go. I'm thinking to do it this way.

If the webapp's able to generate a result table, I would compare it with my local taxcalc and see whether they are the same and whether the results make economic sense. If neither of them makes sense, I would try to see if anything went wrong with taxcalc. If my local tables make sense, I would put down what I got from both webapp and my local taxcalc for later webapp debugging. 

For some other errors that look similar, I would just put them into one big category if I can. It seems so far many errors I got are coming from extremely large values. I would just put all of them in a big category without adding a revenue table for each parameter. Specifically, at the moment there would be a key error category. In the category, I'll list all the parameter names with experiment values in the parenthesis. 

Key error from extremely large parameter inputs
----------------------------------------------------------------
* Max Taxable Earnings for Social Security (10^10)
* Maximum foreign earned income exclusion (9000000)
* Adjustment for self employed health insurance haircut (0.5)
* Personal Exemption (4100)

Any suggestions/thoughts on this? @talumbau @MattHJensen Please also help me tag any one relevant to this task as well. Thank you!

**Comment by MattHJensen** [comment]
@amy-xu, overall this seems great and very well thought out. One note: do you think it would make sense to start with the 'reasonable' range, so we can know whether errors are arising from corner-case issues or are something more basic? For example, when I raise Max Taxable Earnings for Social Security by just $2000 above the default value, I get a key error, so it doesn't seem this is stemming from the 'extremely large' input problem, it something more basic. 

@Amy-Xu, is it fair to say that anything listed under an error message should be viewed as an independent bug for @talumbau and the webapp team to look into?

**Comment by Amy-Xu** [comment]
@MattHJensen I'll definitely start with the reasonable range. At this moment, at least this key error should be a bug in the webapp. @talumbau In addition to the parameters I added to the list, I also found for the haircut parameters, if I put decimals between 0 and 1, which should be the right range, it always gives me the key error. But if I give it an integer, like 2, even though this doesn't make much sense in terms of tax logic, I can always get the result tables.

**Comment by MattHJensen** [comment]
@Amy-Xu, it seems like this key error is a pretty pervasive bug -- if you keep hunting for bugs, I'm afraid you will keep finding this one over and over. Why don't you turn to something else for a while during which others can track this one down.

**Comment by talumbau** [comment]
Couple of things here for @Amy-Xu and @MattHJensen :

There are definitely values of inputs that cause the calculations in `dropq` to fail. One example that we currently protect against in "no changes", which is the same thing as an empty "user_mods" dictionary. This inevitably leads to some columns of all zeros in the `dropq` calculation, which likely causes some pandas operation to fail, which raises an exception of some kind. This eventually results in the 'Key Error' that you are seeing, although I haven't looked in to the exact sequence of events.

To me, I see two activities that are worthwhile:

1.  We create a general error screen, such that, if we don't get back good values from the dropq workers (for whatever reason) we display this error screen, although with the option of downloading the parameters that you chose. We could then link to the issues page on this repo or the Tax-Calculator repo. That covers us for bugs "in the wild"

2. For your activity Amy, I would suggest that we set you up with a script that allows you to call dropq the way the webapp does, you could then script out all of the experiments you are running. The script that does this is `example.py` located at the top of the `dropq` repo. For example, it shows how to modify a tax bracket by creating a typical "user_mods" dictionary:

```
myvars['_II_rt4'] = [0.39, 0.40, 0.41]
```

As long as you know the names of the parameters you wan to modify, you can get the exact behavior of the webapp from this script. If something is broken, you likely won't get a KeyError, you'll probably get the underlying Exception that causes the KeyError. This should make your work faster.

**Comment by Amy-Xu** [comment]
Thank you T.J. @talumbau for the suggestions. Will give it a try shortly!

**Comment by Amy-Xu** [comment]
@talumbau I tried using latest drop Q and taxcalc for testing. A quick update is almost all the key errors I have gotten so far are due to [this line](https://github.com/OpenSourcePolicyCenter/dropQ/blob/master/dropq/utils.py#L90) here. Intuitionally, because those experiments barely generated any difference in tax revenue, so the `wsum` variable was rounded to zero. As we use this variable as a denominator to calculate 'share of overall change' in the difference tables, drop q throws a 'float divided by zero' error. For now as a temp solution, I add 0.00001 to `wsum` and all those errors are gone. We probably want that column shown as 'NA' if `wsum==0` in the end.

**Comment by talumbau** [comment]
@Amy-Xu @MattHJensen now that https://github.com/OpenSourcePolicyCenter/dropQ/pull/22 is merged, do you want to close this issue and open for additional errors that come up? The reason for doing that would be that with Amy's change, we have killed a huge portion of the potential error cases, and I think additional ones would be special edge cases, whereas the original problem was that any inputs that caused a negligible change in revenue would cause an exception. What do you think?

**Comment by Amy-Xu** [comment]
That sounds good to me! And each issue would just be for one specific error/case.

**Comment by MattHJensen** [comment]
Makes sense to me too. Closing.
