### ISSUE TITLE
minor text changes

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#468]
- [ ] Add "Static" to the title of the [static results page](http://www.ospc.org/taxbrain/9909/) and drop "for Federal Individual Income Taxes": Should be "Static Revenue and Distribution Tables" 

- [ ] Add "Partial Equilibrium" to the title of the [partial equilibrium dynamic results page](http://www.ospc.org/dynamic/behavior_results/392/) and drop "for Federal Individual Income Taxes": Should be "Partial Equilibrium Revenue and Distribution Tables

In both, note we are also switching the order of "revenue" and "distribution"

- [x] "A platform for accessing OSPC's open-source tax models." should be "A platform for accessing open-source tax models."

**Comment by MattHJensen** [comment]
@brittainhard, it looks like the only thing preventing me from checking off the first two tasks is that both the Partial Equilibrium and the Static pages rely on the same `taxbrain_results_header` flatblock. We need a different flatblock on each page, perhaps `taxbrain_static_results_header` and `taxbrain_pe_results_header`

**Comment by brittainhard** [comment]
@MattHJensen i'll push a fix for that.

**Comment by rrenfrow86** [comment]
This has been completed per @brittainhard - @MattHJensen please confirm if this can be closed.

**Comment by MattHJensen** [comment]
Closing.
