### ISSUE TITLE
Embed iframe for border adjustment calculator at ospc.org/bac

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#470]
https://ospc.shinyapps.io/border-adjustment-calculator/

**Comment by brittainhard** [comment]
@MattHJensen what page do you want this on?

**Comment by MattHJensen** [comment]
My impression was that the easiest would be to just embed an iframe at a new page: ospc.org/bac. Alternatively, we could include it in the gallery -- but that seems harder to me.

**Comment by brittainhard** [comment]
I think it fits in the gallery better, but I just have a minor styling concern. It has its own link to taxbrain, and that just looks a little off. Minor concern if it can be fixed quickly.

**Comment by MattHJensen** [comment]
I'm not seeing the link to TaxBrain -- could you screenshot it for me?

**Comment by brittainhard** [comment]
At the top-left.

<img width="1009" alt="screen shot 2017-02-21 at 10 02 47 am" src="https://cloud.githubusercontent.com/assets/5440553/23172898/039361e6-f81d-11e6-883f-2a2e537196ec.png">

**Comment by MattHJensen** [comment]
Let's ignore that for now. It is useful for other places that it is embedded. 

If adding it to the gallery is easy even though it is served from shinyapps.io instead of us, then that makes sense to me too.

**Comment by brittainhard** [comment]
Ok. My plan is to embed it in the template used for gallery items (http://localhost:8000/gallery/box_plot/) and hard-code the info on the page.

**Comment by MattHJensen** [comment]
Got it. Sounds good.
