### ISSUE TITLE
macro elasticities model key=2017 error

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#473]
![image](https://cloud.githubusercontent.com/assets/8301092/22987027/799bccda-f37b-11e6-8278-b3d69501f808.png)

http://www.ospc.org/dynamic/macro_results/417/

**Comment by PeterDSteinberg** [comment]
@martinholmer @MattHJensen Please try your failing jobs now on test test app.

**Comment by MattHJensen** [comment]
@PeterDSteinberg, I'm getting the same error:

![image](https://cloud.githubusercontent.com/assets/8301092/22988379/db3d9618-f37f-11e6-8b6e-edf3133d6ce1.png)

http://ospc-taxes7.herokuapp.com/dynamic/macro_results/8/

**Comment by PeterDSteinberg** [comment]
Fixed - new deploy  2-15-2107

**Comment by MattHJensen** [comment]
Thanks @PeterDSteinberg
