### ISSUE TITLE
"Macroeconomic Elasticities" dynamic analysis is broken

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#474]
The "Macroeconomic Elasticities" dynamic analysis does not work.

When I specify a pop-the-cap reform beginning in 2018, the [static results](http://www.ospc.org/taxbrain/9967/) look sensible.

But then when I specify a 0.36 elasticity in the box titled **Elasticity of GDP wrt 1 - AMTR**, I get the following error message:
```
Sorry! Your calculation failed. Please re-enter parameters and try again :(.

Error: key=2017 in reform is not an integer calendar year
```

@MattHJensen @PeterDSteinberg @brittainhard

**Comment by martinholmer** [comment]
Issue #474 is identical to issue #473, which was being posted while I was preparing this issue #474.

**Comment by PeterDSteinberg** [comment]
Resolution expected in next hour.

**Comment by MattHJensen** [comment]
Resolved.
