### ISSUE TITLE
Selecting ADS on CCC does not produce results 

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#478]
https://www.ospc.org/ccc/384/

**Comment by MattHJensen** [comment]
cc @PeterDSteinberg @jdebacker

**Comment by MattHJensen** [comment]
This is a problem on both the test app and on ospc.org.

**Comment by rrenfrow86** [comment]
@MattHJensen and @jdebacker - Brittain suggests this can be closed, please confirm.

**Comment by MattHJensen** [comment]
Closing.
