### ISSUE TITLE
Changing bonus depreciation on B-Tax does not change results

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#479]
http://www.ospc.org/ccc/389/

Note that this experiment left the depreciation selectors on GDS. 

@jdebacker, could you confirm that this is a bug? 

@codykallen thinks that this is not actually a bug, and that bonus depreciation should only matter when ADS is selected (see #478):

> The bonus depreciation is implemented through the accelerated depreciation schedule. Bonus depreciation rates are entirely irrelevant on the baseline general depreciation schedule or on the economic depreciation schedule. As an example, the results for 100% bonus depreciation on GDS (https://www.ospc.org/ccc/387/) are the same as those for 0% bonus depreciation on GDS (https://www.ospc.org/ccc/388/) or any other bonus depreciation rate applied.

If Cody is right, the user interface seems very confusing even after #478 is fixed. The user would need to know to switch from GDS to ADS before changing bonus depreciation parameters.

**Comment by jdebacker** [comment]
Confirming - this is a bug. And not one I recall seeing before.  The model should be able to handle bonus with GDS, ADS, or economic (those define the base schedule upon which bonus is applied).  

I did fix a B-Tax bug the other day (not yet in CCC) that was related to the model not changing the depreciation schedule (GDS, ADS, economic) when moving between the different systems, but bonus was working.

CC @MattHJensen @codykallen

**Comment by MattHJensen** [comment]
This a problem on both ospc.org and the test app.

**Comment by MattHJensen** [comment]
Fixed on the test app. closing.
