### ISSUE TITLE
What should happen when the user clicks the "Share" link on the results page?

### ISSUE THREAD

**Issue by talumbau** [OpenSourcePolicyCenter/webapp-public#48]
Currently, nothing happens. We should either remove it or implement some useful feature.

**Comment by johneo** [comment]
@talumbau, I am attempting to integrate https://github.com/carrot/share-button for the share button. Which sites do you want to integrate with? FB? Pinterest? Twitter? Email? G+ seems to require that the URL be whitelisted with Google API first. I'll have to check on that.

**Comment by johneo** [comment]
Actually, Google just don't like people sharing localhost URL with the world. Including FB, Twitter, G+, and email options. I will need the text for the subject line and the message body.

**Comment by talumbau** [comment]
@johneo , I pushed #104, which had the changes for the Share button. It worked locally and it worked on the Heroku test app. Then I pushed it to the main Heroku app and it doesn't work. Here is the output of the console upon page load:

<img width="494" alt="screen shot 2015-12-31 at 1 44 05 pm" src="https://cloud.githubusercontent.com/assets/1891418/12067743/ca6015fa-afc4-11e5-8fda-4b4a47a01a41.png">

I don't understand why it would work on the test app and work locally, and then fail to work on www.ospc.org. I have made you collaborator on both the test app and the main app on Heroku. 

To answer obvious questions:

- The error occurs when trying through www.ospc.org as well as through ospc-taxes4.herokuapp.com (the second of which is the error screen I'm showing).

- I ran `python manage.py collectstatic` on Heroku and got the same errors
- the file `static/js/vendor/share-button/share-button.min.js` exists on Heroku

It can't be some kind of missing file because everything works on the test app on Heroku. 

cc @mistakevin @zrisher in case you have any insights into why this would be broken.

**Comment by talumbau** [comment]
@johneo you can view this error page by going to http://www.ospc.org/taxbrain/763/

**Comment by talumbau** [comment]
nm, figured it out. This now works on ospc.org. Somehow to assets copied into `staticfiles` did not get added to the repo and so were not pushed to Heroku. Not sure why it worked on ospc-taxes5. 

<img width="598" alt="screen shot 2015-12-31 at 2 14 48 pm" src="https://cloud.githubusercontent.com/assets/1891418/12067945/e5a605aa-afc8-11e5-9fe9-f22b1f966c13.png">



Closing this and associated issues.
