### ISSUE TITLE
Marketing push

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#493]
Hi all, we're planning another marketing push for OSPC webapps to Congressional and executive branch staff and professors. See sample flyer below. 

This issue contains small projects from several repos that need to be accomplished before we can proceed. Please let me know if you can think of others. This should be a priority before other b3 milestone items. 

- [x] Mirror ospc.org/gallery/border-adjustment at ospc.org/bac  (@brittainhard)
- [x]  Fix https://github.com/open-source-economics/B-Tax/issues/134 (@jdebacker)
    - [x]  Deploy latest B-Tax to CCC (@brittainhard)
- [x]  Review and merge https://github.com/open-source-economics/Tax-Calculator/pull/1206 
(@gofroggyrun for review @matthjensen for merge)
    - [x]  New version of Tax-Calculator (@matthjensen)
        - [x]  Deploy latest version of Tax-Calculator to TaxBrain (@brittainhard)
            - [x] Link to docs and hello from TaxBrain input (@matthjensen) 
- [x] Disable link to Overlapping Generations Model from the dynamic landing page and change the color of the button to make it obvious that it is disabled (@brittainhard)
- [x] Update Overlapping Generations flatblock on dynamic landing page to say that it is in maintenance mode (@matthjensen)
- [x] Begin saving logs. (@brittainhard)
- [x] Extensive manual testing for CCC, TB static, TB PE, and TB macro elasticities and make sure everything works. (Everyone) 
    - [x] resolve issues that are identified during manual testing and added to the b2 milestone (@brittainhard) 

![image](https://cloud.githubusercontent.com/assets/8301092/23467159/4b781e3a-fe6b-11e6-94c9-6d28372fb2db.png)

**Comment by martinholmer** [comment]
@MattHJensen said to-do list includes:
> New version of Tax-Calculator (@matthjensen)
> Deploy latest version of Tax-Calculator to TaxBrain (@brittainhard)

What do you mean by "latest version"?
Are changes for release 0.7.8 listed in [TC #1202](https://github.com/open-source-economics/Tax-Calculator/issues/1202) going to be included?

**Comment by MattHJensen** [comment]
@martinholmer asked:

> What do you mean by "latest version"?

0.7.8 

> Are changes for release 0.7.8 listed in TC #1202 going to be included?

That would be best, but I was thinking it wouldn't require any changes to webapp-public. Am I mistaken?

**Comment by martinholmer** [comment]
@MattHJensen responded:
>> What do you mean by "latest version"?
>
> 0.7.8
>
>> Are changes for release 0.7.8 listed in TC #1202 going to be included?
>
> That would be best, but I was thinking it wouldn't require any changes to webapp-public.
> Am I mistaken?

Depends on how far along TaxBrain is in using the new growth features added in [TC #1199](https://github.com/open-source-economics/Tax-Calculator/pull/1199).

@PeterDSteinberg @brittainhard

**Comment by MattHJensen** [comment]
> Depends on how far along TaxBrain is in using the new growth features added in TC #1199.

TaxBrain hasn't done anything to accomodate the new growth features, but the TaxBrain GUI doesn't have any growth parameters anymore so I am operating under the assumption that there is nothing to do. Assuming nothing has been done yet, what do you think should be done?

**Comment by martinholmer** [comment]
@MattHJensen said:
> TaxBrain hasn't done anything to accommodate the new growth features, but the TaxBrain GUI doesn't have any growth parameters anymore so I am operating under the assumption that there is nothing to do. Assuming nothing has been done yet, what do you think should be done?

You're correct in that there is nothing to do if TaxBrain doesn't have growth parameters anymore.

In the short term, probably do nothing wrt growth in TaxBrain GUI and let people who want to use the new growth capability do JSON file uploads.  This assumes that the next TaxBrain is using the 0.7.8 version of dropq.py --- is that the plan?

@PeterDSteinberg

**Comment by MattHJensen** [comment]
I just released Tax-Calculator 0.7.8 and @jdebacker updated B-Tax by resolving open-source-economics/B-Tax#134 this morning. 

@brittainhard / @PeterDSteinberg, if you deploy the latest of both to ospc.org, then everyone can start manually testing while the todos from this issue are resolved.

**Comment by MattHJensen** [comment]
> You're correct in that there is nothing to do if TaxBrain GUI doesn't have growth parameters anymore.

Great. Thanks @martinholmer.

> This assumes that the next TaxBrain is using the 0.7.8 version of dropq.py --- is that the plan?

That's the plan. @PeterDSteinberg did find a need for some [changes](https://github.com/OpenSourcePolicyCenter/deploy/pull/32/files) relating to the implementation of the macro elasticity in dropq (see https://github.com/open-source-economics/Tax-Calculator/issues/1210).

**Comment by brittainhard** [comment]
@MattHJensen Papertrail, the heroku app we use for logging, is now outputting to an s3 bucket. All the logs are being archived.

**Comment by MattHJensen** [comment]
> Papertrail, the heroku app we use for logging, is now outputting to an s3 bucket. 

Thanks @brittainhard! Checking the box.

**Comment by rrenfrow86** [comment]
@MattHJensen - checked off remaining Brittain tasks that have been completed for this.

**Comment by MattHJensen** [comment]
Just added a new item to the checklist:

- resolve issues that are identified during manual testing and added to the b2 milestone (@brittainhard)`

**Comment by brittainhard** [comment]
@MattHJensen, I thought I should give you an update on the issues:

https://github.com/OpenSourcePolicyCenter/webapp-public/issues/507: Has a fix implemented in Tax-Calculator., but i'm leaving it open in case we have problems when we deploy the latest taxcalc (the fix is currently on master, but we have to cut a new version for it).

https://github.com/OpenSourcePolicyCenter/webapp-public/issues/508: the problem was with the logic in the `celery_tasks.py` file. My PR at https://github.com/OpenSourcePolicyCenter/deploy/pull/36 has a fix for this.

https://github.com/OpenSourcePolicyCenter/webapp-public/issues/504: there is a fix for this at https://github.com/OpenSourcePolicyCenter/webapp-public/pull/511, just have to fix the failing build.

https://github.com/OpenSourcePolicyCenter/webapp-public/issues/505: PR is available at https://github.com/OpenSourcePolicyCenter/webapp-public/pull/516. Same with #504 , there are some build issues that need to be solved.

https://github.com/OpenSourcePolicyCenter/webapp-public/issues/512: currently looking through the code for this one. Hopefully it should be a quick fix.

Let me know if you have any questions.

**Comment by MattHJensen** [comment]
@brittainhard, thanks, this is great. I plan to release a new taxcalc towards the end of today. I can do it sooner if it is blocking you.

**Comment by brittainhard** [comment]
@MattHJensen There is still some work to be done to sync webapp and taxcalc. A lot of new fields were added. We're going to have to do another release cycle before we can test everything again.

I'm not currently blocked. I'm still working through #512. I'll need a new release when I start merging the PRs.

**Comment by MattHJensen** [comment]
> There is still some work to be done to sync webapp and taxcalc. A lot of new fields were added. We're going to have to do another release cycle before we can test everything again.

@brittainhard, would it make things significantly easier if I were to add a commit that removes all of the section labels from the new parameters, release 0.8.0, and then add another commit that adds them back that will be part of 0.8.1?

**Comment by brittainhard** [comment]
@MattHJensen I think it would save time to work off taxcalc master as-is to sync up the apps. All that is required on my side is to add new fields to the Django models, and iron out any differences.

I experimented with taxcalc master locally when I was working on a couple of bugfixes, and the differences in the models aren't too large. There a couple of API changes that will have to be fixed, though.

I think it's better to work off of latest master for the new version.

**Comment by MattHJensen** [comment]
> I think it's better to work off of latest master for the new version.

Ok. Thanks.

**Comment by MattHJensen** [comment]
This is resolved. Thanks everyone!
