### ISSUE TITLE
CCC Differences tables of output mixed up

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#496]
CCC needs to include B-Tax through the merge of PR #135.  Currently the test-app is at B-Tax PR #131 and ospc.org is at a prior version.

**Comment by MattHJensen** [comment]
@jdebacker, is this issue resolved now?

**Comment by jdebacker** [comment]
Yes.  This was fixed with [B-Tax PR #140](https://github.com/open-source-economics/B-Tax/pull/140)
