### ISSUE TITLE
Make it easier to display content from the news blog on the webapp

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#5]
_From @zrisher on July 24, 2015 14:49_

We'd like to display links to blog posts from within this webapp, but the blog posts are hosted on a separate Pelican app. We could:

* manually code these links into the html - easy, but requires dev instead of site maintenance to update
* provide a flatblock for this content - allows site maintainers to update the content, but they must get the html right and will need to pull titles / descriptions / links from Pelican manually. If the content changes on Pelican (esp links), they will need to update it here
* pull the content from the Pelican site dynamically - a lot of ways to do this, but using the atom feed Pelican provides by default might be easiest

_Copied from original issue: OpenSourcePolicyCenter/webapp#247_

**Comment by ospc-auto** [comment]
_From @talumbau on July 24, 2015 18:37_

cc @amfarrell

**Comment by talumbau** [comment]
Using the second or third option in the bullet list seems appropriate, if this feature is still desired. Closing for now.
