### ISSUE TITLE
_ALD_InvInc_ec_base_RyanBrady should be checkbox instead of 1/0

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#504]
As a rule, we can use checkboxes when parameters are boolean in current_law_policy.json. 

![image](https://cloud.githubusercontent.com/assets/8301092/23759634/4fccddd0-04bb-11e7-9090-e32955df0954.png)

@brittainhard

**Comment by brittainhard** [comment]
I'll look into this.
