### ISSUE TITLE
Pass-Through parameters are not being properly deployed

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/webapp-public#505]
When editing pass-through parameters, sometimes these modifications will be overrode, without any notifications, when there are also regular, non-pass-through, parameter changes. 

The problem can be replicated using the following toy example:

1. Set `Personal income (regular/non-AMT/non-pass-through) tax rate 2` (under Personal Income, Regular: Non-Amt, Non-Pass-Through section) to `0.25`.

2. Set `Pass-through income tax rate 2` (under Personal Income, Pass-Through section) to `0.15`.

3. Click "Show me the results".

4. After calculation is done, click "Edit parameters", and check the parameters we just edited.

5. You will find the actually `Pass-through income tax rate 2` being implemented is `0.25`, instead of `0.15`!

The cause of this problem might be that, for some reasons, pass-through parameters are associated with non-pass-though parameters. 

@MattHJensen

**Comment by MattHJensen** [comment]
I can replicated. 

cc @brittainhard

**Comment by brittainhard** [comment]
Looking into this now.

**Comment by brittainhard** [comment]
@GoFroggyRun @MattHJensen I looked at the code, and it looks like this is an intended feature. If there is a param like `II_rt1` set, then `PT_rt1` will always be set to the former param value.

The original issue and discussion is here: https://github.com/OpenSourcePolicyCenter/webapp-public/issues/340

The fix was added in https://github.com/OpenSourcePolicyCenter/webapp-public/pull/342

If we do want keep this logic, there is the possibility of hiding all of the `PT_*` fields, or I can revert the behavior if we want to change it back to the previous behavior.

Let me know what you think.

**Comment by GoFroggyRun** [comment]
@brittainhard Thanks for looking into this issue. 

@brittainhard said:
>I looked at the code, and it looks like this is an intended feature. If there is a param like II_rt1 set, then PT_rt1 will always be set to the former param value.

Yes, this was the case when we have not introduced any `PT_rt` parameters in tax-calculator to tax-brain (TB) I believe. Before users are able to edit `PT_rt` parameter themselves on TB, this assumption was a compromise (sort of) we made in past releases.

But right now, in TB, we are splitting `PT_rt` and `II_rt` parameters because we want them to be manipulated independently. In other word, the logic that sets corresponding `PT_rt` to be `II_rt`is no longer wanted. 

@MattHJensen let me know if I have missed something.

**Comment by MattHJensen** [comment]
@GoFroggyRun, that is correct. Thanks.

**Comment by brittainhard** [comment]
Good to know. I'll make a PR that removes this logic from webapp.

**Comment by GoFroggyRun** [comment]
I'm confirming that this issue has been fixed in the latest release of TB (test version). So closing. 

Thanks @brittainhard for fixing this!

**Comment by MattHJensen** [comment]
Thanks @brittainhard. Thanks @GoFroggyRun.
