### ISSUE TITLE
_CTC_new_ps not being properly deployed

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/webapp-public#507]
The `_CTC_new_ps` parameter, which corresponds to "New refundable child tax credit phaseout starting AGI" in TaxBrain under "Refundable Credit" section, is not being properly deployed.

In particular, TB will report the following error: 

![screen shot 2017-03-09 at 5 53 12 pm](https://cloud.githubusercontent.com/assets/13324931/23774604/656e4ac0-04f2-11e7-8cc2-1148ec8fab5d.png)

From the source code in [TC](https://github.com/GoFroggyRun/Tax-Calculator/blob/master/taxcalc/current_law_policy.json#L2585-L2598), it's clear why the array is reporting dimensional error when being modified. 

To replicate the error:

1. Edit the `New refundable child tax credit phaseout starting AGI` under "Refundable Credit" section to any number, say `1000`.

2. Click "Show me the results".

@MattHJensen @brittainhard

**Comment by MattHJensen** [comment]
Replicated. Thanks @GoFroggyRun!

**Comment by brittainhard** [comment]
Fixed in Tax-Calculator PR.

**Comment by brittainhard** [comment]
Re-opened. Behavior will not be fixed until the taxcalc version on the nodes is updated. This will also require changes to webapp.

**Comment by GoFroggyRun** [comment]
I'm confirming that this issue has been fixed in the latest release of TB (test version). So closing.

Thanks @brittainhard for fixing this!

cc @MattHJensen
