### ISSUE TITLE
Bug with TaxBrain file-upload logic

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#508]
In TaxBrain version 0.7.9 the file-upload page is completely broken.

When I chose a reform file to upload and click on the "Show me the results!" button, I get this:
```
Sorry! Your calculation failed. Please re-enter parameters and try again :(.

Error: invalid literal for int() with base 10: 'assumptions'
```
In the prior version of TaxBrain it was possible to specify no assumption file.

I don't understand how we can go backward from one release to another.  Sounds like there is insufficient testing of TaxBrain.

@PeterDSteinberg @brittainhard @MattHJensen

**Comment by martinholmer** [comment]
@MattHJensen,  I would appreciate it if resolving issue #508 was given a high priority.

**Comment by martinholmer** [comment]
When you try with TaxBrain 0.7.9 to upload both a reform file and an assumptions file, the same error message as described in #508 is generated.  So the bug is even more fundamental then I initially thought.  Essentially, the TaxBrain file-upload capability does not work at all.

**Comment by MattHJensen** [comment]
Moving this to milestone b2.

**Comment by MattHJensen** [comment]
@brittainhard, is this resolved?

**Comment by brittainhard** [comment]
@MattHJensen closing this. The fix in the deploy PR has been merged.

**Comment by MattHJensen** [comment]
@brittainhard, I'm reopening because I'm still getting errors for reform files that should work:

This is with the Trump2016.json file from the taxcalc/reforms

![image](https://cloud.githubusercontent.com/assets/8301092/24817229/b843a542-1ba9-11e7-9749-c14dc72793b9.png)

**Comment by brittainhard** [comment]
Ahh, i'll take another look, then.

**Comment by MattHJensen** [comment]
Here's the file I used: https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/reforms/Trump2016.json

**Comment by martinholmer** [comment]
TaxBrain file-upload capability is now working in the 0.8.1 version.
Thanks for the fix.  Closing issue #508.
