### ISSUE TITLE
Medicare payroll tax rate and additional medicare tax rate not being properly deployed

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/webapp-public#510]
Two parameters, medicare payroll tax rate and additional medicare tax rate, both under the Payroll Taxes section, are not being properly deployed in TB.

Based on a simple reform (adds 0.01 to each parameter) that modified both parameters, the result in [TB](http://www.ospc.org/taxbrain/10418/) is so different from result yields from TC: 

![screen shot 2017-03-13 at 7 00 37 pm](https://cloud.githubusercontent.com/assets/13324931/23878705/5ff979f4-081f-11e7-9497-7e470f9f1f69.png)

This seems a bug to me.

cc @MattHJensen

**Comment by MattHJensen** [comment]
Thanks @GoFroggyRun

**Comment by MattHJensen** [comment]
These two parameters in tax-calculator are:
- `_FICA_mc_trt`
- `_AMEDT_rt`

**Comment by MattHJensen** [comment]
@brittainhard, it's probably worth noting that @GoFroggyRun has tested all other parameters and found no other significant differences between TaxBrain and Tax-Calculator except for this issue and other previously opened issues over the last few days, so we are fairly certain there is no systematic error.

**Comment by GoFroggyRun** [comment]
Per @MattHJensen's request, I have created a table for a reform that modifies potential problematic parameters mentioned above. (Reform details available [here](http://www.ospc.org/taxbrain/edit/10418/?start_year=2017))

In year 2026, Combined liability, in Billions of $:

|   | Baseline        | Reform           | Difference  |
| --- | ------------- |:-------------:| -----:|
| TC  | 4,009.5     | 4,142.7 | 133.2 |
| DropQ (local)  | 4009.5     | 4,142.7       |   133.2|
| TB  | 4,009.2 | 4,142.4     |    133.2  |

Note that TC and DropQ local results are not identical, the difference is less than 0.1B though.

**Comment by MattHJensen** [comment]
Thanks @GoFroggyRun. My assessment is that these differences are caused solely by dropq noise. Closing.
