### ISSUE TITLE
Reported TaxBrain Web App Error

### ISSUE THREAD

**Issue by andersonfrailey** [OpenSourcePolicyCenter/webapp-public#519]
A TaxBrain user submitted the following response to our feedback form:
>Every time i change the standard deduction and the tax brackets i am getting a 500 internal server error

I was not personally able to recreate this error. Are there anymore details I should ask him for?

@martinholmer @MattHJensen @PeterDSteinberg @brittainhard

**Comment by MattHJensen** [comment]
It would be helpful know their run number if one was generated after submitting the reform (ospc.org/taxbrain/[number]). If no run number was generated, it would be helpful to know the specific parameter changes they made.

**Comment by talumbau** [comment]
If the user can reproduce the problem (i.e. reliably create this 500 error message), I would have him/her demonstrate the problem a couple of times in a row while noting the time (time zone included) and date.  This information could be provided to @brittainhard or @PeterDSteinberg who can look at the corresponding Papertrail logs to see if the Heroku app provides a better error message. It should at least be possible to capture the exact input that is causing the 500.

**Comment by MattHJensen** [comment]
Closing this given no followup from the user and our inability to recreate the problem.
