### ISSUE TITLE
NIIT parameter is Boolean

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/webapp-public#520]
The `_NIIT_PT_taxed` parameter is Boolean in Tax-Calculator, while that is not the case in TaxBrain, as indicated in the screen shot. This seems a bug to me.

cc @MattHJensen @brittainhard 

![screen shot 2017-04-04 at 1 37 57 pm](https://cloud.githubusercontent.com/assets/13324931/24670627/c8be81ea-193c-11e7-8958-2e24b6cfcbef.png)

**Comment by brittainhard** [comment]
This is related to the problem in #504 . I have a feeling that there are more inputs like this. I'll work on a general fix to this problem.

**Comment by GoFroggyRun** [comment]
@brittainhard yes you are right. There seems to be more than a couple of them:

![screen shot 2017-04-04 at 2 36 17 pm](https://cloud.githubusercontent.com/assets/13324931/24672828/265b4886-1944-11e7-8d1a-c983ee98ce3d.png)

cc @MattHJensen
