### ISSUE TITLE
Payroll tax logic bug in TB (test version)

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/webapp-public#521]
[This](http://ospc-taxes7.herokuapp.com/taxbrain/1219/) TB reform modifies payroll parameters, and I replicated the same reform in tax-calculator. It seems that, telling from the attached TC results, dropQ is not able to account for the huge difference between payroll liability differences in TB and TC. Thus, there's some bug within the Payroll Taxes section.

<img width="776" alt="screen shot 2017-04-04 at 3 08 18 pm" src="https://cloud.githubusercontent.com/assets/13324931/24674175/92525f6c-1948-11e7-814b-50ddbac402ba.png">

I will try to further identify problematic parameters.

cc @brittainhard @MattHJensen 

Detailed reform attached:
```
        "_FICA_ss_trt":
            {"2017": [0.134]},
        "_SS_Earnings_c":
            {"2017": [128200]},
        "_FICA_mc_trt":
            {"2017": [0.039]},
        "_AMEDT_ec":
            {"2017": [[201000, 251000, 126000, 201000, 201000, 126000]]},
        "_FICA_mc_trt":
            {"2017": [0.019]}
```

**Comment by MattHJensen** [comment]
Thanks @GoFroggyRun, looking forward to the isolated problem parameter when you have it.

**Comment by GoFroggyRun** [comment]
Based on the TB results [here](http://ospc-taxes7.herokuapp.com/taxbrain/1227/), I can confirm that the root cause of the problem is due to, and only due to, the parameter `_FICA_mc_trt`. 

See TB's result:

<img width="785" alt="screen shot 2017-04-04 at 7 42 25 pm" src="https://cloud.githubusercontent.com/assets/13324931/24683720/e659afd6-196e-11e7-908e-466490caa259.png">

Again, dropQ shouldn't be able to account for such huge difference.

cc @MattHJensen @brittainhard 

Reform file attached here:
```
{
  "policy": {
        "_FICA_mc_trt":
            {"2017": [0.019]}   
  }
}
```

**Comment by MattHJensen** [comment]
@gofroggyrun, thanks for identifying the problematic param. Just to clarify, the results in the table are from Tax-Calculator, not TB, right? 

<img width="785" alt="screen shot 2017-04-04 at 7 42 25 pm" src="https://cloud.githubusercontent.com/assets/13324931/24683720/e659afd6-196e-11e7-908e-466490caa259.png">

**Comment by MattHJensen** [comment]
@GoFroggyRun, the param that is edited on TaxBrain is not _FICA_mc_trt, it is the additional medicare tax rate. 
![image](https://cloud.githubusercontent.com/assets/8301092/24684431/00d2f9da-1974-11e7-85aa-11c78e01fd3e.png)

**Comment by MattHJensen** [comment]
Actually, the original reform has _FICA_mc_trt listed twice. 


        "_FICA_ss_trt":
            {"2017": [0.134]},
        "_SS_Earnings_c":
            {"2017": [128200]},
        **"_FICA_mc_trt":**
            {"2017": [0.039]},
        "_AMEDT_ec":
            {"2017": [[201000, 251000, 126000, 201000, 201000, 126000]]},
        **"_FICA_mc_trt":**
            {"2017": [0.019]}

**Comment by GoFroggyRun** [comment]
@MattHJensen Thanks for pointing out. 

I corrected the duplicated parameter name by changing the second `_FICA_mc_trt` to `_AMEDT_rt`, and the results from TB and TC do coincide. 

I'm also confirming that there's no discrepancy so far for static reforms based on a reform that modifies all TB parameters.

Sorry about the false alarm. Closing this one.

**Comment by MattHJensen** [comment]
Thanks @GoFroggyRun.
