### ISSUE TITLE
Reset parameters button broken. 

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#522]
Reset parameters button is broken. When I clicked it the page transforms from 

![image](https://cloud.githubusercontent.com/assets/8301092/24676504/37c5189c-1951-11e7-8ae2-5edbf75e8220.png)

To

![image](https://cloud.githubusercontent.com/assets/8301092/24676470/16c0fac6-1951-11e7-85d3-984fc540024c.png)

Without resetting the parameter values, only the formatting. 

I'm on Chrome.

**Comment by brittainhard** [comment]
@MattHJensen are you working off of the test app? Or the main app? I'm having trouble re-creating this. Can you show what steps you took?

**Comment by MattHJensen** [comment]
@brittainhard, I must have been on an edit parameters page. Now that I think about this more, the behavior was unexpected, but probably correct. 

I'm going to move this issue out of 2.5 and think about if there's any way we can make this a little smoother for the users.

**Comment by MattHJensen** [comment]
@brittainhard, I just had another user report this same issue, so I'm moving it back to 2.5. 

Since the other user had the same reaction I did, I think the right behavior is: 

if the user is on an edit parameter page, the reset parameters button will take them to a blank ospc.org/taxbrain page.

**Comment by brittainhard** [comment]
Fixed in #533
