### ISSUE TITLE
TaxBrain "Build Table" enhancements

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#534]
The "Build Table" feature at the bottom of the TaxBrain static results page is very nice.  I've used it off and on over the past year mostly by building a table and viewing it and maybe making a note of a few numbers that I'm viewing.

I've just started exploring the other options of what to do with a built table: Print, Copy and CSV.
I don't have Excel on my computer so I didn't try the fourth option.

Here are a few things I noticed that could be improved to make the user experience better.

(1) When using Print, the table looks good on the page, but a second blank page gets printed out even though there is plenty of whitespace at the bottom of the first page.  It's sort of a hassle to have to remember to switch the print option from All to Page 1, and even if you know to do that, the one printed page says it is 1/2, which is confusing.  Someone might think they were missing some output.

(2) When using Copy, everything works fine except the title of the built table is absent.  This is a major shortcoming.  The built table's title is included in the Print output, so I don't know why it wouldn't be included in the Copy output.

(3) When using CSV, the downloaded file loads up into my spreadsheet (OpenOffice) just fine except again the critically important title of the built table is missing.

I'm a novice user of these TaxBrain capabilities, so I could have made a mistake.  But if not, fixing these things would leave users would a much better impression of TaxBrain.

@MattHJensen @PeterDSteinberg @brittainhard

**Comment by martinholmer** [comment]
Another enhancement needs to be added to the list in TaxBrain issue #534.

It has already been pointed out that the title of the built table is not included in the downloaded CSV file or Copy.  But there is another problem: the name of the downloaded file is sort of laughable and completely useless.  Here is what I got in my `~/Download` directory after building four different distributional tables and clicking on the CSV button:
```
  989 Apr 14 17:09   Welcome to TaxBrain  TaxBrain (1).csv
  976 Apr 14 17:10   Welcome to TaxBrain  TaxBrain (2).csv
  961 Apr 14 17:12   Welcome to TaxBrain  TaxBrain (3).csv
  640 Apr 14 17:07   Welcome to TaxBrain  TaxBrain.csv
```
First of all, the embedded spaces cause failures with standard CLI tools.
Here is what I get on my Mac:
```
iMac2:tax-calculator mrh$ ll ~/Downloads/Welc*
ls: (1).csv: No such file or directory
ls: (2).csv: No such file or directory
ls: (3).csv: No such file or directory
ls: /Users/mrh/Downloads/Welcome: No such file or directory
ls: /Users/mrh/Downloads/Welcome: No such file or directory
ls: /Users/mrh/Downloads/Welcome: No such file or directory
ls: /Users/mrh/Downloads/Welcome: No such file or directory
ls: TaxBrain: No such file or directory
ls: TaxBrain: No such file or directory
ls: TaxBrain: No such file or directory
ls: TaxBrain: No such file or directory
ls: TaxBrain: No such file or directory
ls: TaxBrain: No such file or directory
ls: TaxBrain: No such file or directory
ls: TaxBrain.csv: No such file or directory
ls: to: No such file or directory
ls: to: No such file or directory
ls: to: No such file or directory
ls: to: No such file or directory
iMac2:tax-calculator mrh$ 
```
Can we get rid of all the spaces in the downloaded file names?

Second, the file name is the same for every downloaded file.  How is a user supposed to know what is in each file?  They can't look inside the file because there no table title to tell them what it is.

I'm trying to write up some TaxBrain user documentation, but honestly I don't see how a user could do any serious tax analysis and save it to a local computer without going through a lot of work renaming files and adding the table titles into each downloaded file.  I don't think this is the ease-of-use level we are trying to provide users.  Over the past month or so, enhancement requests like this have been assigned a low priority.  If we don't fix these (what I consider) serious problems soon, we'll end up having TaxBrain user documentation that spends much of its time advising users how to work around these kinds of problems.  I don't think that is a situation we want to be in.

@MattHJensen @PeterDSteinberg @brittainhard

**Comment by MattHJensen** [comment]
Moving to milestone 3. Thanks @martinholmer for opening.

**Comment by MattHJensen** [comment]
Summary

- [ ] TOTAL LIABILITIES TABLES: should automatically print all 10 years onto the page (to 2026). Now only 9 (to 2025). Either shrink cols, or if possible, have the browser default to printing landscape. 
![image](https://cloud.githubusercontent.com/assets/8301092/25304873/26f64eb4-273e-11e7-97c7-d1d24b1c90af.png)

- [ ] TOTAL LIABILITIES CHANGE TABLE: when I click "reform" or "current law" the output options disappear. I should still be able to print etc. 
![image](https://cloud.githubusercontent.com/assets/8301092/25304881/49ad3d0a-273e-11e7-99e7-9d95fc55361d.png)

- [ ] BUILD A TABLE TABLES: Print option should not include an extra blank page.
![image](https://cloud.githubusercontent.com/assets/8301092/25304900/d095a80c-273e-11e7-8c11-a62e4e5ff3c9.png)

- [ ] ALL TABLES: the Copy, CSV, and Excel options should keep the title of the table in the top row. Currently the title of the table is not included. 

- [ ] TOTAL LIABILITIES TABLES: Should not include the year in the table name. Currently the "Change" and "Current Law" tables include the start year in parenthesis. 

- [ ] TOTAL LIABILITIES CHANGE TABLE: TOTAL LIABILITIES CHANGE BY CALENDAR YEAR (2017) should be TOTAL LIABILITIES BY CALENDAR YEAR (CHANGE)

Will update this summary with a title naming scheme after we finalize in more conversation.

**Comment by MattHJensen** [comment]
@martinholmer, thanks for suggesting better filenames. 

Here's a possible file naming scheme:

TOTAL LIABILITIES TABLES

Formula
[run#]_liabilities_[change/reform/currentlaw]

Examples:
10000_liabilities_change
10000_liabilities_reform
10000_liabilities_currentlaw

BUILD A TABLE TABLES

Formula
[run#]_[year]_[1st selection]_[2nd selection]_[4th selection] 

Examples
10000_2017_diagnostic_currentlaw_bins
10000_2017_diagnostic_reform_deciles
10000_2017_difference_payroll_bins
10000_2017_difference_payroll-income_deciles

Very much welcome feedback and other suggestions.

**Comment by martinholmer** [comment]
@MattHJensen, This would be a big improvement. Thanks.
Why don't we go with this (or some refinement of your devising) for now and see how it works.

**Comment by MattHJensen** [comment]
@GoFroggyRun, could you open a PR that closes this issue? See this [overview comment](https://github.com/OpenSourcePolicyCenter/webapp-public/issues/534#issuecomment-296374381).

**Comment by martinholmer** [comment]
There has been some progress on this issues identified in #534, but some problems still remain.
The remaining problems present in TaxBrain 1.0.1 are described in the new issue #629.

Perhaps open pull requests #545 and #564 will fix some (or all) of these problems.

@MattHJensen @brittainhard @GoFroggyRun
