### ISSUE TITLE
TaxBrain input boxes too narrow

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#537]
The boxes are too narrow for the default values of some parameters in the Surtaxes : New Minimum Tax section.  Either make boxes wider or use scientific notation to show the default values (as is done in the Surtaxes : New AGI Surtax section).

**Comment by MattHJensen** [comment]
Thanks @martinholmer. 

I think this will be resolved by #536:

> We should only display the first four fields for parameters indexed by MARS (longstanding convention for TaxBrain. 

But if not good to have a separate issue. Adding this to 2.5.

**Comment by martinholmer** [comment]
@MattHJensen said:
> I think [issue #537] will be resolved by #536

Yes, probably so.  But the more I look at TaxBrain the more I think very large numbers should be shown in scientific notation because it is not that easy to count all the zeros.

**Comment by MattHJensen** [comment]
> Yes, probably so. But the more I look at TaxBrain the more I think very large numbers should be shown in scientific notation because it is not that easy to count all the zeros.

I that case we should move this issue to tax-calculator as that is  determined by current_law_policy.json. But I'm not sure that it is easier for people to read scientific notation than it is for them to count zeroes.

**Comment by martinholmer** [comment]
@MattHJensen said:
> But I'm not sure that it is easier for people to read scientific notation than it is for them to count zeroes.

You're absolutely right.  Just widen the boxes so 2000000 fits in.

**Comment by brittainhard** [comment]
Solved in PR #538 . Closing
