### ISSUE TITLE
More enhancements needed for TaxBrain results tables

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#544]
The tax analysis described in [Tax-Calculator issue 1335](https://github.com/open-source-economics/Tax-Calculator/issues/1335) reveals the need for several more enhancements to the TaxBrain results page.

1. For some reason the terminology for the diagnostic tables and the difference tables are different. 
 The difference tables sensibly use "by" (as in "by income decile") while the diagnostic tables use the strange terminology "per" (as in "per income decile").  Can we standardize on "by"?

2. The Print|Copy|CSV|Excel boxes just below the upper Total Liabilities section disappear when users change from Change to either Current Law or Reform.  And the boxes don't come back when clicking on Change.  This means there is no way to download the Current Law or Reform Total Liabilities.  Surely this is not by design.  Can we make it so the four boxes don't disappear?

3. When clicking on either Current Law or Reform the row labels in the Total Liabilities table don't switch to a more appropriate label.  In all three versions of the table the row label ends in Change, which is appropriate in only one of the three cases.  Can we drop Change from the end of each of the table row labels?

4. The title of the Total Liabilities table ends with (2017) --- when that is the Start Year --- in the Current Law and Change version of the Total Liabilities table even though all ten years are shown in the table.  Can we remove the (2017) at the end of those two table titles?

5. A key statistic is missing from the Total Liabilities tables: the ten-year totals.  Most users will want the ten-year total for each row in the Total Liabilities table, but it is not there at the end of the row where most users would expect to see it.  Can we add a ten-year total column on the far right?

6. The downloaded CSV file has all the numerical values enclosed in quotation marks (like "1,234.5").  This is a problem for users who have uploaded reform/assumption files to TaxBrain and want to download TaxBrain results for analysis on their local computer using command-line tools.  Can the commas and enclosing quotation marks be removed from the downloaded CSV file?

7. Has anyone used the Excel download capability successfully?  Whatever is downloaded will not import into the OpenOffice spreadsheet.  I don't have Excel on my computer, does everything work smoothly when you do have Excel?  I'm curious, why this option is available in an open-source project.  What capability is the Excel download providing that the CSV download is not providing?

@MattHJensen @feenberg @PeterDSteinberg @brittainhard @enelson1995

**Comment by MattHJensen** [comment]
@martinholmer, I added Point 1 and Point 4 to #534. Point 2 was already listed in #534. 

Would you mind closing this issue and opening a new one for the 10-year totals? I would be happy to do so if you'd prefer.
