### ISSUE TITLE
Default values are no longer displayed after editing parameters

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#555]
![image](https://cloud.githubusercontent.com/assets/8301092/26162305/5d677f26-3af4-11e7-9657-fece8f515b9d.png)

No default is displayed.

**Comment by brittainhard** [comment]
@MattHJensen is this on the main app?

**Comment by MattHJensen** [comment]
Yes.

**Comment by brittainhard** [comment]
@MattHJensen a push for this has been push to the test app.

**Comment by MattHJensen** [comment]
Yes, this looks fixed on the test app. Thanks @brittainhard
