### ISSUE TITLE
Remove Year Dropdown from File Upload Page

### ISSUE THREAD

**Issue by brittainhard** [OpenSourcePolicyCenter/webapp-public#557]
Currently has a dropdown for adding a start year, but doesn't seem to
change the outcome of the data sent forward, since the data provided
contains the year directly. Should probably remove this UI element.

Of course, there may be some code that allows for a differently formatted
file -- indeed, there is really no indication that I can see where
a format has been specified.

If there were format specifications, I think they would be on the server,
but from looking at the code, it doesn't look like there is anything there.

**Comment by MattHJensen** [comment]
@brittainhard the year drop down specifies the start of the 10-year budget window. The reform files themselves specify the year that various prvisions of the reform are implemented. 

Here is an example of a reform where the year drop down was set to 2013. http://www.ospc.org/taxbrain/13557/

**Comment by martinholmer** [comment]
There has been no discussion of issue #557 over the past four weeks.
So, I'm assuming this issue can be closed.
