### ISSUE TITLE
news displayed improperly on about page

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#56]
![image](https://cloud.githubusercontent.com/assets/8301092/10204877/3917e7f6-678c-11e5-8e02-e3d1e5795f61.png)

This should look like the home page. 

cc @talumbau

**Comment by talumbau** [comment]
Just looking at this now. What should this section look like? Should there be this "What People are Saying" section? If yes, I guess it would have to pull content from news.ospc.org. That's a bit more involved. To me, it's still a useful page even w/o this "What People are Saying" section.

**Comment by MattHJensen** [comment]
The analagous section on the home page looks like this ("updates from the field" rather than "what people are saying".):

![image](https://cloud.githubusercontent.com/assets/8301092/10587130/bfa7472c-766d-11e5-995d-6b7d12778858.png)

I remember that @zrisher (i think) had to link manually to get the welcome to ospc post to show, however, and obviously that hasn't been done for the new TaxBrain is live post. 

Ideally on both the about page and home page we could pull the last few blog posts (for now two, then three, then six in two rows) automatically. In the meantime, I'd be fine just hiding this section on the about page. Keeping the updates from the field section on the home page seems important.

**Comment by MattHJensen** [comment]
I've been thinking more about this. Let's just drop this "what people are saying" section and make life easier for ourselves.
