### ISSUE TITLE
Cannot Run TaxBrain Locally

### ISSUE THREAD

**Issue by GoFroggyRun** [OpenSourcePolicyCenter/webapp-public#565]
After [#563](https://github.com/OpenSourcePolicyCenter/webapp-public/pull/563) being merged, I updated my local master, as well as taxcalc, btax and ogusa packages, to run TaxBrain locally. However, I got the following error message:

<img width="871" alt="screen shot 2017-06-19 at 4 51 16 pm" src="https://user-images.githubusercontent.com/13324931/27305418-8ec3c5cc-550f-11e7-92c1-43073c8451f3.png">

The error message reads: 
```
OperationalError at /taxbrain/
table taxbrain_taxsaveinputs has no column named ID_Medical_c_0
```

Could you advice @brittainhard ?

cc @MattHJensen

**Comment by martinholmer** [comment]
@GoFroggyRun,  What is the status of webapp-public issue #565?
Did you get any advice?  Have you been able to resolve the problem?

**Comment by GoFroggyRun** [comment]
@martinholmer, I switched to previous environment variable setting as well as master version so that I could continue working on development and testing locally. So I am not quite updated on the status of this issue. 

@brittainhard, could you advice?

**Comment by talumbau** [comment]
Looks to me like you need to run migrations, since the code refers to a table that doesn't exist in your local database.

**Comment by GoFroggyRun** [comment]
@talumbau thanks for your comment T.J.. I was on master branch and pretty sure all static changes were collected at that moment.

**Comment by MattHJensen** [comment]
@GoFroggyRun, should this issue be closed?

**Comment by GoFroggyRun** [comment]
@MattHJensen Yep. Closing.

**Comment by MattHJensen** [comment]
Thanks @GoFroggyRun.
