### ISSUE TITLE
* operator not documented

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#585]
We do not currently document the * operator on www.ospc.org/taxbrain in the user tips section. 

![image](https://user-images.githubusercontent.com/8301092/28367104-86280f1c-6c5d-11e7-9114-4e0aab65294c.png)

I plan to add the following (bold) bullets tomorrow. Would appreciate any improvements to the wordings. The last bullet in particular is somewhat complex. I also think there is a word that describes operators like our * operator, but I can't remember what it is. 

- **By default, the policy parameter boxes contain Start Year values. You can change the Start Year of the analysis in the upper left.** 
- Enter comma-separated values into a field to indicate the multiple years of tax law. DO NOT use commas as thousands separators.
- Toggle the CPI control to indicate whether a parameter should be adjusted for inflation.
- Express rates as decimals.
- **You can represent a value that would otherwise manifest itself in a year with the `*` operator. So, for example, if you enter `0.1, *, 0.2` in a tax rate field, the rate will be 10 percent in the Start Year, 10 percent a year after the start year, and 20 percent two years after the Start Year and forward. If you enter `100, *, 200` in a CPI-indexed field for a credit amount, the credit will be $100 in the Start Year, `$100*(1+CPI)` the next year, and $200 the following year.** 

cc @martinholmer @ecbrown5 @feenberg

**Comment by martinholmer** [comment]
@MattHJensen,  TaxBrain issue #585 (with respect to the * symbol) would be a welcome addition to the TaxBrain documentation.  I think your proposed wording is fine.

**Comment by MattHJensen** [comment]
This is updated on TaxBrain. Thanks @martinholmer for the feedback.

**Comment by martinholmer** [comment]
@MattHJensen, So how did this new documentation get added to TaxBrain?
I can't see any pull request that made the change.  If we want TaxBrain development to be more transparent, changes like this need to be more visible.

**Comment by MattHJensen** [comment]
I updated a [django flatblock](https://pypi.python.org/pypi/django-flatblocks) via the Django admin. I agree this is not an ideal system and will open an issue to address it.
