### ISSUE TITLE
Small reform file character limit

### ISSUE THREAD

**Issue by hdoupe** [OpenSourcePolicyCenter/webapp-public#591]
I tried to upload a json file to the webapp that contains all of the default taxbrain parameters and is about 8,000 characters long.  I received an error when I tried to upload it to the test webapp and the production webap, but I did not have any problems running it on my machine using a local instance of the webapp.

1. It looks like the `JSONReformTaxCalculator` class in `webapp/taxbrain/models.py` places a 4,000 character limit on the reform file.  Why is there a 4,000 character limit versus something like a 10,000 character limit?
2. Why does this work on a local instance of the webapp but not on the webapp when it's on a server?

The production webapp gave me a 500 error.  Here is the test webapp error:

```
Request Method: | POST
-- | --
http://ospc-taxes7.herokuapp.com/taxbrain/file/?start_year=2017
1.8.2
DataError
value too long for type character varying(4000)
/app/.heroku/miniconda/lib/python2.7/site-packages/newrelic-2.58.2.45/newrelic/hooks/database_dbapi2.py in execute, line 22
/app/.heroku/miniconda/bin/python
2.7.13
['/app/.heroku/miniconda/bin',  '/app/.heroku/miniconda/lib/python2.7/site-packages/newrelic-2.58.2.45/newrelic/bootstrap',  '/app/.heroku/miniconda/lib/python27.zip',  '/app/.heroku/miniconda/lib/python2.7',  '/app/.heroku/miniconda/lib/python2.7/plat-linux2',  '/app/.heroku/miniconda/lib/python2.7/lib-tk',  '/app/.heroku/miniconda/lib/python2.7/lib-old',  '/app/.heroku/miniconda/lib/python2.7/lib-dynload',  '/app/.heroku/miniconda/lib/python2.7/site-packages',  '/app/src/django-flatblocks',  '/app/.heroku/miniconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg',  '/app']
Tue, 25 Jul 2017 14:50:32 +0000
```

Here is the code to generate the default data file:
```
dd = Policy.default_data(metadata=False, start_year=2017)

reform = {"policy": {}}
for param in dd:
    reform["policy"][param] = {"2017": dd[param]}

with open('default_reform.json', 'w') as js:
    js.write(json.dumps(reform))
```

Here is the code to test `taxcalc`:
```
puf = pd.read_csv("puf.csv")

rec_1= Records(data=puf)
pol_1 = Policy()
calc_1 = Calculator(records = rec_1, policy = pol_1)

rec_2= Records(data=puf)
pol_2 = Policy()
calc_2 = Calculator(records=rec_2, policy=pol_2)
formatted = calc_2.read_json_param_files("default_reform.json", None)
pol_2.implement_reform(formatted["policy"])

res1 = multiyear_diagnostic_table(calc_1, num_years = 8)
res2 = multiyear_diagnostic_table(calc_2, num_years = 8)

diff = res1 - res2
i, j = len(res1), len(res1.columns)
assert(np.allclose(diff, np.zeros(i * j).reshape(i, j))) # passes
```
@PeterDSteinberg @brittainhard

**Comment by brittainhard** [comment]
@hdoupe I think the limit we set might be arbitrary.  If its accepting files then it should be much larger. I don't know Postgres or SQLite intimately, but it could be the case that Postgres is much more strict in this regard. Why SQLite isn't complaining and Postgres is, I don't know.

The fix here is just to increase the character limit. We can add this into the version fully test version of webapp working with taxcalc 0.9.1.

**Comment by hdoupe** [comment]
@brittainhard Thanks, that makes sense.  With tabs, the reform file is about 26,000 characters.  I would imagine that that's pretty close to the upper limit sense this file contains each parameter.

**Comment by brittainhard** [comment]
@hdoupe I can make a PR that changes the models. It's running fine locally, right? Does the file itself contain tab characters?

**Comment by hdoupe** [comment]
@brittainhard 
> It's running fine locally, right?

Yes, it runs fine locally.  Like you said, I think it has something to do with SQLite vs Postgres.  

> Does the file itself contain tab characters?

No, it uses a soft tab, so 4 spaces.  The soft tabs are not necessary but they help with the readability of the file.  This type of file would be generated using this command: 
```
with open('default_reform.json', 'w') as js:
    js.write(json.dumps(reform, indent=4))
```

**Comment by brittainhard** [comment]
@hdoupe out of curiosity, can you send me the reform file you used?

**Comment by martinholmer** [comment]
@brittainhard,  Is there any reason to delay merging pull request #592?
If not please merge it, so that #591 can be resolved.

**Comment by brittainhard** [comment]
@martinholmer going to go through the whole test deploy process tomorrow. Will merge it then.
