### ISSUE TITLE
Return to 0.9.0 TaxCalc as Default

### ISSUE THREAD

**Issue by brittainhard** [OpenSourcePolicyCenter/webapp-public#595]
As per request from @MattHJensen, we need to keep the default taxcalc version at 0.9.0 for now. Next release will be done with version 0.9.0.

**Comment by martinholmer** [comment]
@brittainhard said:
> As per request from @MattHJensen, we need to keep the default taxcalc version at 0.9.0 for now. Next release will be done with version 0.9.0.

OK.  But a little explanation about why we are doing this would help the whole team understand what's going on.

**Comment by MattHJensen** [comment]
@martinholmer, I plan to send out a note to the policybrains-modelers mailing list later this afternoon on this topic, but here is the preview preview:

I think it we should go through two rounds of the release process (see the updated version in #594). The first would release a webapp-public update that fixes the file upload bugs. The second would release a webapp-public update that upgrades to taxcalc 0.9.2. 

@brittainhard would kick off the first round at step 3, by mailing the mailing list with the commit that is slated to be tagged 1.0.1. 

After the first round is complete, @hdoupe would pick up the 0.9.2 release process at step 4, by testing 0.9.2 with webapp-public locally.

**Comment by martinholmer** [comment]
@MattHJensen,  Thanks for the explanation in webapp-public #595.  Seems reasonable.
