### ISSUE TITLE
Updates from the field section should be hidden or should contain welcome-to-ospc post

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#6]
_From @MattHJensen on July 22, 2015 19:20_

The updates from the field section on the homepage currently shows two fake blog posts. Ideally, this section would show the welcome to ospc post that I just published, ideally centered since there is only one blog post up right now. As an alternative, we could hide this section entirely until we have two posts. 

![image](https://cloud.githubusercontent.com/assets/8301092/8834903/39a19336-3085-11e5-9b54-23d863e6b45e.png)

_Copied from original issue: OpenSourcePolicyCenter/webapp#243_

**Comment by ospc-auto** [comment]
_From @zrisher on July 24, 2015 14:49_

I submitted a hotfix for this and am opening a new issue to discuss a better long-term solution:
https://github.com/OpenSourcePolicyCenter/webapp/issues/247

**Comment by talumbau** [comment]
this is now resolved. The News section no longer features "Updates from the field".
