### ISSUE TITLE
new 'payroll tax' section

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#60]
- [x] We should add a new payroll tax section to the input page. 
    -     Subsections would be Social Security FICA, Medicare FICA, and Additional Medicare FICA (see image below). 
- [x] We should rename the "Social Security and Medicare" section to "Social Security Taxability" 
- [x] We should remove the max taxable earnings for social security param from the Social Security Taxability section since it will now be in the Payroll tax section. 
- [x] Likewise, we should remove the Additional Medicare section from the other taxes section since it will now be in the payroll tax section. 

@mistakevin, could you also take this one? 

![image](https://cloud.githubusercontent.com/assets/8301092/10403038/fcf450a4-6e96-11e5-9215-dc97f54abaf1.png)

cc @feenberg

**Comment by MattHJensen** [comment]
@talumbau @mistakevin, we should either do what is above or the following before we bump versions tomorrow. Here would be the alternative:

- [ ] Remove Additional Medicare from the other taxes section completely, 
- [ ] Remove the max taxable earnings for social security from the Social Security and Medicare section
- [ ] Rename the Social Security and Medicare section to Social Security taxability. 

Which of these we do will depend on whether @Amy-Xu  opens a PR to dropq today that makes it possible to produce the tables described in #62, and your reaction to how hard it will be to get those tables incorporated on the output page per the guidlines in #62. If @Amy-Xu decides it is hard to open the dropq PR or you decide it would be hard to take advantage of the dropq pr on the webapp output page, then we should go with the "alternative" outlined in this comment.

**Comment by talumbau** [comment]
@MattHJensen in your figure above, I think you wanted "_SS_Earnings_c" instead of what you have written ("_SS_Income_c"), correct? Reference:

https://github.com/OpenSourcePolicyCenter/Tax-Calculator/blob/master/taxcalc/current_law_policy.json#L435

**Comment by MattHJensen** [comment]
Ahh, yes, thanks @talumbau

**Comment by talumbau** [comment]
resolved via https://github.com/OpenSourcePolicyCenter/webapp-public/pull/81
