### ISSUE TITLE
New economic baseline section. 

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#61]
There should be a new section on the TaxBrain input page that gives the users access to the economic growth rate work that @Amy-Xu is conducting in #383 (previously #368). I'm hoping that @PeterDSteinberg or @talumbau take this one. 

![image](https://cloud.githubusercontent.com/assets/8301092/10428679/2ca45a16-70c1-11e5-94da-d231a48ba32b.png)

This feature is a bit different than others because the growth update should be applied to both the plan x and plan y calculators. Also, only one of these parameters should be changed at a time. Susan suggested a radio button, which is what I display in the sketch above. 

Note that I suspect #383 will need some refactoring, which @amy-xu is taking care of today, before it will work seemlessly with dropq. See this comment: https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/368#issuecomment-146283814.

**Comment by talumbau** [comment]
So, there would be two radio button sections? One with the title "Deviation from CBO..." and then some choices, and then another with the title "Replacement for... " and then choices. Is that correct? Is the initial state of each radio button "unselected" for both? What should happen if a selection is made in both radio button areas?

**Comment by MattHJensen** [comment]
>So, there would be two radio button sections? One with the title "Deviation from CBO..." and then some choices, and then another with the title "Replacement for... " and then choices. Is that correct? 

Yes. 

>Is the initial state of each radio button "unselected" for both? What should happen if a selection is made in both radio button areas?

The initial selection should be "Deviation from CBO" and the default value will be 0, so there will be no deviation from CBO. 

If someone clicks the other radio button, it should automatically unselect the Deviation from CBO radio button and vice versa.

**Comment by talumbau** [comment]
OK, got it.

SOS @mistakevin is the above a quick surgical strike for you?

**Comment by MattHJensen** [comment]
(just to clarify, the displayed names of the parameters and all other meta data should com from the attributes in current_law_policy.json as with the other fields on the input page. )

**Comment by talumbau** [comment]
@MattHJensen I think everything is clear here now except for how to populate the radio button choices. `growth.json` from @Amy-Xu 's PR https://github.com/OpenSourcePolicyCenter/Tax-Calculator/pull/383 shows the `_factor_adjustment` and `_factor_target` at 0.0 for both. Should we set constants in this repo for the radio button choices - e.g. 1% above CBO, 2% above CBO, 1% below CBO, 2% below CBO for growth adjustment, and then 1%, 2%, -1%, -2% real GDP growth. Something like that?

**Comment by MattHJensen** [comment]
Actually I think we're not on the same page w the radio buttons. I anticipate just two selections: one choice is _factor_target and one choice is _factor_adjustment. The user uses text boxes to enter values, just like other params.

**Comment by talumbau** [comment]
OK. I think I got it now. So something like this:

<img width="534" alt="screen shot 2015-10-13 at 6 12 29 pm" src="https://cloud.githubusercontent.com/assets/1891418/10470875/0ff8b75c-71d6-11e5-8bb5-e503491faf3e.png">

except with a text box next to each radio button populated with the default values for _factor_adjustment and _factor_growth.

Correct?

**Comment by MattHJensen** [comment]
That's right. And the 'information i' pulling in the description attribute.

**Comment by MattHJensen** [comment]
Resolved and closing.
