### ISSUE TITLE
Using BTAX DataFrames for Dynamic Plotting

### ISSUE THREAD

**Issue by brittainhard** [OpenSourcePolicyCenter/webapp-public#634]
@hdoupe @MattHJensen @PeterDSteinberg

The central problem is that the data returned from BTAX to CCC cannot be used for plotting -- specifically the plots that Haylee and Dora have created.

BTAX serializes the original DataFrames for use in the HTML table, but it doesn't preserve the original structure of the many DataFrames that BTAX returns. They need to change the BTAX code to return serialized versions of those DataFrames alongside the JSON to be used for the HTML table.

If they can have access to the original DataFrames, then they can use them to create dynamic plots to be put onto the CCC results page alongside the HTML table.

They need to change the BTAX function to return the DataFrames, and we need to include that new version into our next release. Their deadline is the end of this week.

**Comment by jdebacker** [comment]
@brittainhard I think this issue can be closed.  Can you confirm?

**Comment by brittainhard** [comment]
@jdebacker does it still apply to the bubble plot PR?

**Comment by jdebacker** [comment]
@brittainhard I think the fix to B-Tax noted here was completed with B-Tax [PR #171](https://github.com/open-source-economics/B-Tax/pull/171).

With that, I think Haylee should be able to complete Web-app Public PR #642.

**Comment by brittainhard** [comment]
Ok, I'll close it.
