### ISSUE TITLE
Express filing unit count in million rounded to one decimal place

### ISSUE THREAD

**Issue by martinholmer** [OpenSourcePolicyCenter/webapp-public#647]
After reviewing the dropq documentation and code, it seems clear that part of our IRS-SOI PUF privacy-protection strategy is to show dollar amounts in billions rounded to one decimal point.  However, the distribution and difference tables show the number of filing units in a bin in whole thousands.  This seems like much more precision than is scientifically reasonable and excessive precision when considering privacy-protection issues.

**I suggest that all the filing unit count columns have units `Millions` (instead of `Thousands`) and that the entries in those columns be rounded to one decimal place.**

So, for example, a table entry that currently says `17,005` in a column labeled `Thousands` would be shown as `17.0` and the column unit label would be changed to `Millions`.

This change has the added advantage of making it easier (at least for me) to do mental arithmetic to get the average dollar amount in each bin.  For me it is easier to divide billions by millions to get an average that is expressed in thousands of dollars.

But even if others don't find that mental arithmetic argument compelling, the privacy-protection argument is very important.

@MattHJensen @feenberg @GoFroggyRun @hdoupe @brittainhard

**Comment by feenberg** [comment]
On Fri, 1 Sep 2017, Martin Holmer wrote:

> 
> After reviewing the dropq documentation and code, it seems clear that part
> of our IRS-SOI PUF privacy-protection strategy is to show dollar amounts in
> billions rounded to one decimal point. However, the distribution and
> difference tables show the number of filing units in a bin in whole
> thousands. This seems like much more precision than is scientifically
> reasonable and excessive precision when considering privacy-protection
> issues.
> 
> I suggest that all the filing unit count columns have units Millions
> (instead of Thousands) and that the entries in those columns be rounded to
> one decimal place.
> 
> So, for example, a table entry that currently says 17,005 in a column
> labeled Thousands would be shown as 17.0 and the column unit label would be
> changed to Millions.
> 
> This change has the added advantage of making it easier (at least for me) to
> do mental arithmetic to get the average dollar amount in each bin. For me it
> is easier to divide billions by millions to get an average that is expressed
> in thousands of dollars.
> 
> But even if others don't find that mental arithmetic argument compelling,
> the privacy-protection argument is very important.

Recall that between drop-q and the fact that the base file is already a 
public use file, I don't think we should be worrying about privacy. Also, 
the privacy aspect depends on the number of records, not the weighted 
count.

It looks like our smallest category by AGI only would go from "715" to 
".7". That is just a single digit of precision. The tax-increase and 
tax-decrease cells would show even more loss of precision. I can certainly 
see a congressperson not wanting to see 400 thousand rounded down to zero.

There is a tradition going back nearly a hundred years of showing 
returns in thousands, and it is to our advantage to respect this 
tradition.

dan

**Comment by martinholmer** [comment]
@feenberg said:
>  I can certainly see a congressperson not wanting to see 400 thousand rounded down to zero.

You didn't read or understand my proposal, I'm not sure which.

I'm suggesting that 400 thousand be represented as 0.4 million.

Or, at the greatest loss of precision, 449 thousand being represented as 0.4 million.
Will "congresspeople" really think it is important to know whether 449 thousand are affected, rather than being told about 0.4 million will be affected?

**Comment by martinholmer** [comment]
@feenberg said in issue #647:
> There is a tradition going back nearly a hundred years of showing returns in thousands, and it is to our advantage to respect this tradition.

I'm not sure what "hundred year" "tradition" you're referring to here.  Certainly when IRS has **all** the tax returns, IRS can in complete confidence show the number of filing units in a table cell in thousands.  But in our simulation work, we have only a small sample of tax returns (very roughly a one-in-a-thousand sample).  And we are also trying to simulate the effects of tax reforms (not just tabulate returns under current law).  Also we are projecting to future years with uncertain growth projections.  All these things imply to me that it is not scientifically prudent to express the number of tax returns in a table cell in thousands.  Why aren't we expressing dollar amount in whole millions of dollars?

**Comment by MattHJensen** [comment]
I am sympathetic to the concern that expressing returns in thousands is overly precise and better suited for an agency like SOI with a larger dataset than what we have. However, it also feels misleading to round 49,000 to 0.0. Having those situations expressed as 0+ or similar seems nice, but implementing it doesn't.

**Comment by martinholmer** [comment]
@MattHJensen said:
> I am sympathetic to the concern that expressing returns in thousands is overly precise and better suited for an agency like SOI with a larger dataset than what we have. However, it also feels misleading to round 49,000 to 0.0. Having those situations expressed as 0+ or similar seems nice, but implementing it doesn't.

OK, if you honestly think the TaxBrain decile bin filing-unit counts have standard errors small enough to detect the difference between 49 thousand units and zero units, then maintain the current practice of showing unit-count results in the whole number of thousands.

**Comment by feenberg** [comment]
On Wed, 6 Sep 2017, Martin Holmer wrote:

> 
> @MattHJensen said:
>
>       I am sympathetic to the concern that expressing returns in thousands is overly precise and
>       better suited for an agency like SOI with a larger dataset than what we have. However, it
>       also feels misleading to round 49,000 to 0.0. Having those situations expressed as 0+ or
>       similar seems nice, but implementing it doesn't.
> 
> OK, if you honestly think the TaxBrain decile bin filing-unit counts have standard errors small enough
> to detect the difference between 49 thousand units and zero units, then maintain the current practice
> of showing unit-count results in the whole number of thousands.

At high incomes, 49 thousand units could be several thousand records. 
Please don't even consider anything non-numeric such as "0+" - a nightmare 
for anyone who expects machine readable output.

dan
