### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#7]
_From @MattHJensen on July 22, 2015 19:17_

- [ ] on ospc.org homepage, the "see all news" link is broken.
![image](https://cloud.githubusercontent.com/assets/8301092/8834818/a54f15be-3084-11e5-8bff-e5c2b556e1ef.png)

- [ ] On http://news.ospc.org/welcome-to-ospc.html, the "see all news" link is broken.
![image](https://cloud.githubusercontent.com/assets/8301092/8834833/bcf699e4-3084-11e5-81d8-cc5824a32650.png)

I believe both of these should redirect to news.ospc.org

_Copied from original issue: OpenSourcePolicyCenter/webapp#242_

**Comment by MattHJensen** [comment]
This is resolved. Closing.
