### ISSUE TITLE
allow users to set start-year to 2013

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#72]
If users could set the start year to 2013 on TaxBrain, it would greatly increase their ability to assess the model for themselves, which we are asking that they do. The reason is that they could compare the results to the IRS Statistics of Income Division [2013 tables](https://www.irs.gov/uac/SOI-Tax-Stats-Individual-Income-Tax-Returns-Publication-1304-(Complete-Report)).

I view this as a high-priority issue.

**Comment by talumbau** [comment]
I suppose we could offer a drop down with the options of 2013, 2014, 2015, and 2016. However, the default values would have to re-populate with the defaults for the selected year, correct? To do this in the browser would require some additional front end work. @zrisher @mistakevin. An alternative would be to put a button next to the drop-down that says "Reset Defaults to Year: ", and then the user could click the button which would trigger a reload of the page. The re-loaded page would populate with defaults for whatever year was chosen in the drop down. The default year in the drop down would be 2015.

**Comment by talumbau** [comment]
resolved by https://github.com/OpenSourcePolicyCenter/webapp-public/pull/97
