### ISSUE TITLE
Restore parameters to default/baseline values

### ISSUE THREAD

**Issue by jdebacker** [OpenSourcePolicyCenter/webapp-public#78]
On the TaxBrain user input screen, consider offering a button for each section of parameters to "restore to baseline values".  While the default is the baseline, if the user write over these, she must remember the default value if she wishes to restore them (or refresh the entire page, which would wipe out all other changes in the parameters).

**Comment by talumbau** [comment]
If the user clears all input from a text box, this is the same as "use the default value". Does that handle the use case you are referring to? If yes, perhaps we should say that explicitly in the instructions.

**Comment by jdebacker** [comment]
@talumbau yes, that is the functionality I was looking for.  I think that is intuitive, but until trying it just now, I didn't see the defaults restored when deleting other values that were entered.  Maybe I missed something, but with what I see now I don't think you need any further explanation and I think we can close this issue.

**Comment by jdebacker** [comment]
@talumbau One more thought - I guess the type of button I was suggesting would still have at least one advantage over what is done now-  that is the case of the user changing a number of related parameters (e.g. all the AMT Extension parameters), but then deciding to undo those changes.  It may be useful to have a single button to undo all those changes rather than having to delete the values from a number of cells (up to 9 in the case of the AMT Extension parameters).

**Comment by MattHJensen** [comment]
It seems like a midground would be to have a "return to defaults" button, which would just take the user to ospc.org/taxbrain. This would erase everything, rather than section by section. This would work if the user had been editing params on ospc.org/taxbrain, and it would also work if the user were on a page like this: http://www.ospc.org/taxbrain/edit/557/

**Comment by MattHJensen** [comment]
This could be part of it. If I add a number without toggling radio button like this
![image](https://cloud.githubusercontent.com/assets/8301092/10731746/3b8bd650-7bcd-11e5-847d-78fc57171662.png)
Then when I toggle the radio button it erases the change I had made. 
![image](https://cloud.githubusercontent.com/assets/8301092/10731768/50b69d80-7bcd-11e5-9322-f82b08e2567a.png)

**Comment by MattHJensen** [comment]
I just verified that the above comment is not the only problem.

**Comment by MattHJensen** [comment]
This is resolved. Closing.
