### ISSUE TITLE
Successful registration doesn't result in a success email

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#8]
_From @talumbau on July 21, 2015 18:21_

When you successfully register, you should get an email that includes your new password, but it turns out you just get a second email that looks just like the first one (so it doesn't include your new password). 

_Copied from original issue: OpenSourcePolicyCenter/webapp#239_

**Comment by ospc-auto** [comment]
_From @mistakevin on July 29, 2015 22:4_

taking this per @talumbau request

**Comment by mistakevin** [comment]
I don't believe this is fixed

**Comment by talumbau** [comment]
this is a duplicate of https://github.com/OpenSourcePolicyCenter/webapp-public/issues/4
