### ISSUE TITLE
Economic growth parameters not working

### ISSUE THREAD

**Issue by MattHJensen** [OpenSourcePolicyCenter/webapp-public#83]
A user said:
>(2) Tried to change growth rate (first .005, then .01). No change in results. (What am I doing wrong?)

Upon testing, I find neither economic growth parameter changes results. 

@talumbau, my preference would be to fix this before the next release, but if that isn't possible then we should hide or disable ('coming soon') the fields.

**Comment by MattHJensen** [comment]
At first I thought this was because the radio button doesn't get selected automatically when you enter a new number, and so the user needed to select the radio button automatically. But it turns out that the problem exists with and without selecting the radio button.

**Comment by talumbau** [comment]
Did the user click the radio button next to growth parameter? Which growth parameter was chosen so I can attempt to reproduce? If the radio button is not selected for one of the growth parameters, the value is ignored. What was the ID of the processed result?

**Comment by MattHJensen** [comment]
I'll generate a few examples, but so far it has been impossible for me to get the results to change with any usage of either of the economic baseline parameters (change one by itself; pair it with a different policy change; select radio button; don't select radio button). IDs coming soon.

**Comment by talumbau** [comment]
Hmm.. I just ran locally for three budget years starting in 2015 with `user_mods` as follows:

```
{2015: {'_factor_target': [0.01]}}
```

this produces no revenue change. Is there a notebook or a code snippet of a PlanX/PlanY calculation with taxcalc that shows using either `_factor_adjustment` or `_factor_target` that produces a revenue change. If I had such a script, I could start there and successively add steps to the calculation to discover the bad behavior.

**Comment by MattHJensen** [comment]
http://www.ospc.org/taxbrain/540/  Personal exemption == 8000
http://www.ospc.org/taxbrain/539/ Personal exemption == 8000, CBO replacement growth = 0.06
http://www.ospc.org/taxbrain/541/ Personal exemption == 8000, Deviation from CBO baseline = .1

All results exactly the same.

**Comment by MattHJensen** [comment]
@Amy-Xu, could you post a script here for this:
https://github.com/OpenSourcePolicyCenter/webapp-public/issues/83#issuecomment-150583535

**Comment by talumbau** [comment]
If the proper way to handle the specification of `_factor_target` and `_factor_adjustment` is to create `Growth` objects as is done in:

https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/tests/test_growth.py

could @Amy-Xu or other knowledgeable party advise on if/how this should be done in dropq?

**Comment by Amy-Xu** [comment]
@talumbau I'm looking into the problem right now. Want to make sure you're using `{2015: {'_factor_adjustment': [[0.01]]}}`, which has double square brackets around 0.01 right? Don't have a complete answer at this point yet. The baseline from OSPC master doesn't look quiet right and some other surtax handle is not working properly either. But in my notebook, there's indeed a difference between zero and 0.01 adjustment.

**Comment by Amy-Xu** [comment]
@talumbau Here's the script I used for local testing, which is basically the same as `test_growth.py`. And I do see some difference for both `_factor_target` and `_factor_adjustment`.

```
tax_dta1 = pd.read_csv("/Users/Amy/Documents/2009 Public Use File/cps-puf.csv")
policy1 = Policy(start_year = 2013)
records1 = Records(tax_dta1)
growth1 = Growth()

tax_dta2 = pd.read_csv("/Users/Amy/Documents/2009 Public Use File/cps-puf.csv")
policy2 = Policy(start_year = 2013)
records2 = Records(tax_dta1)
growth2 = Growth()

reform = {2015:{"_ID_BenefitSurtax_crt": [0.02]}}
policy2.implement_reform(reform)

calc1 = Calculator(records=records1, policy=policy1, growth = growth1)
calc2 = Calculator(records=records2, policy=policy2, growth = growth2)

calc1.diagnostic_table(10)
calc2.diagnostic_table(10)

factor = {2015: {'_factor_target': [[0.0]], '_factor_adjustment':[[0.01]]}}
growth1.update_economic_growth(factor)
growth2.update_economic_growth(factor)

calc1.diagnostic_table(10)
calc2.diagnostic_table(10)
```

**Comment by talumbau** [comment]
Well, there are no `Growth` objects created in dropq, so these kinds of calculations are not done on the web app. Can you show me code such that, if someone hands you an arbitrary reform dictionary, you would either create or not create the `Growth` object and do the calculation? For example, if the arbitrary reform dictionary is called `reform`, would you have code like this:

```

if '_factor_adjustment' or `_factor_target` in reform:
    <code like in test_growth.py>
else:
    <make calculator objects without making a Growth object>
```

Is that the correct way to think about this? If yes, this logic should be added to dropq.

**Comment by Amy-Xu** [comment]
@talumbau Generally yes. 

- If these two parameters were updated to Policy object, nothing would be changed. They should be a part of the Growth object.

- Correct me if I understand [this line](https://github.com/open-source-economics/Tax-Calculator/blob/master/taxcalc/calculate.py#L48) wrong: I thought this meant all calculator would have a default form of Growth object. So the logic would look more like: if `reform` has any growth related parameters, then update those parameters to Growth object. Otherwise, all reforms go to Policy object.

- One last thing worth attention is that these two parameters should be applied to both default calculator and reform calculator, instead of just the reform calculator.

**Comment by talumbau** [comment]
yes, you are right about the default Growth object built when a Calculator object is constructed. So, in that sense, we do build Growth objects in dropq. However, in order to get the desired behavior, it looks like we would have to look inside the reform dictionary, look for the desired keys, and then manually call:

```
calc1. growth.update_economic_growth(...)
```

Is that correct?

**Comment by Amy-Xu** [comment]
Yep that sounds right. But I got confused a bit because if this is the case, then we should already have something similar (searching reform and find the relevant parameters) for Behavior object in dropq if behavior is functioning well. But haven't been able to find the search step in drop q. @talumbau Do we have it for Behavior now? @MattHJensen Do we need a similar process for behavior?

**Comment by talumbau** [comment]
@Amy-Xu you have access to dropq, correct? Peter added code for Behavior, but it is only done for the user-defined plan, so based on what you wrote above about Growth, I wonder if Behavior code should execute for Plan X as well. Please @MattHJensen or @Amy-Xu review this code and let me know:

https://github.com/OpenSourcePolicyCenter/dropQ/blob/master/dropq/dropq.py#L181-L211

I will begin looking at how to incorporate growth and based on what you have written above, I will make sure that plan X and plan Y calculators get the same treatment.

**Comment by MattHJensen** [comment]
Behavior should only apply to plan Y. Growth should apply to both X and Y.

**Comment by talumbau** [comment]
ok great thanks

**Comment by MattHJensen** [comment]
The idea here is that the taxpayer might change his behavior if policy changes, and so the behavior change should only be reflected in the plan Y data. The growth parameters on the other hand allow the user to test "what if baseline growth is different than CBO expects it to be", in which case both the plan X and the plan Y data would be affected.

**Comment by MattHJensen** [comment]
Resolved. Thanks @talumbau
