### ISSUE TITLE
Seed data should be included in repo

### ISSUE THREAD

**Issue by zrisher** [OpenSourcePolicyCenter/webapp-public#86]
Currently there is no seed data included in the application. I believe it would help contributors see how styles and flatblocks are meant to be used, and assist them in detecting bugs, if this information was included in the app.

The Django documentation server is currently dead right now, so I don't have the perfect syntax here, but I know we can use the `dumpdata` command to export existing data ala 

`manage.py dumpdata [app_name] > [app_name]/fixtures/initial_data.json`

on the production machine, commit the fixtures to the repo, and then from a local install use the `syncdb` or `loaddata` commands, e.g. 

`python manage.py loaddata /full/path/to/data.json`

We would want to occasionally commit the latest fixtures from master.

In my mind flatblocks are the main targets for export right now, but other data may be useful now or down the line.

**Comment by talumbau** [comment]
+1 on this. Having this feature would have helped to test the JS issue you resolved. If I am going to implement it, the time to completion on this might be significant due to other priorities on the web app. What is your assessment on the level of effort here?

**Comment by zrisher** [comment]
I think this would be really simple actually, we just need to run the above-mentioned command on the heroku server to dump the data from the DB to a file, add it to git, then include that commit into master. There might be some occasional maintenance work updating it, but I think overall effort should be quite low. It just needs to be done by someone with direct access to the Heroku server.

**Comment by talumbau** [comment]
resolved via #117

**Comment by zrisher** [comment]
Very nice!
