### ISSUE TITLE
It's not always clear what user you are logged in as...

### ISSUE THREAD

**Issue by ospc-auto** [OpenSourcePolicyCenter/webapp-public#9]
_From @talumbau on July 21, 2015 18:20_

If you are currently logged in as a user, then you successfully register as some other user, then you go to the TaxBrain app, the user for your TaxBrain session will be logged as the original user, not the new user you just registered. So for now, if you want to use multiple user accounts, you need to use an Incognito session on your browser. A fix for this would give someone a 'log out' button (or some other idea that I haven't thought of).

_Copied from original issue: OpenSourcePolicyCenter/webapp#238_

**Comment by talumbau** [comment]
this is resolved with recent improvements.
